'use client'; import {useEffect,useState} from 'react'; import {errMsg} from '@/lib/errMsg'; import ContentTable from './ContentTable'; import ContentForm from './ContentForm'; import TypeBuilder from './TypeBuilder'; import MediaLibrary from './MediaLibrary'; import {CategoriesAdmin,LocationsAdmin} from './Taxonomy';
// CMS tab shell (owner menu): All Content · Add New · Categories · Locations · Media
// Library · Drafts · Pending Review · Published · Archived · Trash · Content Types ·
// Content Settings. Status tabs reuse the same table pre-filtered; refreshKey remounts data.
export default function ContentManager({types:types0,categories:cats0,locations:locs0,settings,perms,initialTab,canSettings}:{types:any[],categories:any[],locations:any[],settings:any,perms:any,initialTab:string,canSettings:boolean}){ const [tab,setTab]=useState(initialTab||'all'); const [types,setTypes]=useState(types0); const [categories,setCategories]=useState(cats0); const [locations,setLocations]=useState(locs0); const [editing,setEditing]=useState<any>(null); const [st,setSt]=useState(settings); const [msg,setMsg]=useState(''); const [refreshKey,setRefreshKey]=useState(0);
 const refresh=async()=>{ try{ const [t,c,l]=await Promise.all([fetch('/api/admin/content-types').then(r=>r.json()).catch(()=>({})),fetch('/api/admin/categories').then(r=>r.json()).catch(()=>({})),fetch('/api/admin/locations').then(r=>r.json()).catch(()=>({}))]); if(t.types) setTypes(t.types); if(c.categories) setCategories(c.categories.map((x:any)=>({...x,posts:x.posts||0,contents:x.contents||0}))); if(l.locations) setLocations(l.locations); }catch{} setRefreshKey(k=>k+1); };
 useEffect(()=>{ if(tab==='edit'&&!editing) setTab('all'); },[tab,editing]);
 const openEdit=async(c:any)=>{ try{ const r=await fetch('/api/admin/contents/'+c.id); const j=await r.json().catch(()=>({})); if(r.ok){ setEditing(j.content); setTab('edit'); } else alert(j.message||errMsg(j.error)); }catch{ alert(errMsg('NETWORK')); } };
 const saveSettings=async()=>{ try{ const r=await fetch('/api/admin/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({settings:st})}); const j=await r.json().catch(()=>({})); if(r.ok) setMsg('সেটিংস সংরক্ষণ হয়েছে'); else alert(j.message||errMsg(j.error)); }catch{ alert(errMsg('NETWORK')); } };
 const TABS:any[]=[['all','🗂️ সব কনটেন্ট',true],['add','➕ নতুন কনটেন্ট',perms.create],['DRAFT','📝 খসড়া',true],['PENDING','⏳ পর্যালোচনা',true],['PUBLISHED','✅ প্রকাশিত',true],['ARCHIVED','🗄️ আর্কাইভ',true],['TRASHED','🗑️ ট্র্যাশ',true],['categories','📂 ক্যাটাগরি',perms.cats],['locations','📍 লোকেশন',perms.cats],['media','🖼️ মিডিয়া লাইব্রেরি',perms.media],['types','🧩 কনটেন্ট টাইপ',perms.types],['settings','⚙️ কনটেন্ট সেটিংস',canSettings]];
 return <div><div className="flex flex-wrap items-center gap-2 mb-4"><h1 className="font-black text-xl">🗂️ কনটেন্ট ম্যানেজমেন্ট</h1><span className="chip bg-emerald-100">{types.length}টি টাইপ</span></div>
 <div className="flex gap-1.5 flex-wrap mb-4">{TABS.filter((t:any)=>t[2]).map((t:any)=>(<button key={t[0]} onClick={()=>{ setTab(t[0]); if(t[0]==='add') setEditing(null); }} className={`chip press ${tab===t[0]||(tab==='edit'&&t[0]==='add')?'bg-emerald-600 text-white':''}`}>{t[1]}</button>))}</div>
 {msg&&<p className="text-emerald-700 text-sm mb-2">{msg}</p>}
 {(tab==='all'||['DRAFT','PENDING','PUBLISHED','ARCHIVED','TRASHED'].includes(tab))&&<ContentTable key={tab+refreshKey} types={types} categories={categories} perms={perms} fixedStatus={tab==='all'?undefined:tab} onEdit={openEdit}/>}
 {tab==='add'&&perms.create&&<ContentForm types={types} categories={categories} locations={locations} perms={perms} onDone={()=>{ setMsg('কনটেন্ট তৈরি হয়েছে'); setTab('all'); refresh(); }}/>}
 {tab==='edit'&&editing&&<div><h2 className="font-black mb-3">✎ কনটেন্ট সম্পাদনা</h2><ContentForm types={types} categories={categories} locations={locations} initial={editing} perms={perms} onDone={()=>{ setMsg('কনটেন্ট আপডেট হয়েছে'); setEditing(null); setTab('all'); refresh(); }}/></div>}
 {tab==='categories'&&perms.cats&&<CategoriesAdmin categories={categories} onChanged={refresh}/>}
 {tab==='locations'&&perms.cats&&<LocationsAdmin locations={locations} onChanged={refresh}/>}
 {tab==='media'&&perms.media&&<MediaLibrary/>}
 {tab==='types'&&perms.types&&<TypeBuilder types={types} onChanged={refresh}/>}
 {tab==='settings'&&canSettings&&<div className="card max-w-xl"><h2 className="font-black mb-3">⚙️ কনটেন্ট সেটিংস</h2><div className="grid gap-3"><div><label className="block text-sm font-bold">প্রতি পেজে কনটেন্ট সংখ্যা (অ্যাডমিন তালিকা)</label><input type="number" min={5} max={100} value={st.cmsContentsPerPage} onChange={e=>setSt({...st,cmsContentsPerPage:Number(e.target.value)})} className="!w-28"/></div><div><label className="block text-sm font-bold">প্রকাশের অনুমতি ছাড়া তৈরি করলে ডিফল্ট অবস্থা</label><select value={st.cmsEditorDefaultStatus} onChange={e=>setSt({...st,cmsEditorDefaultStatus:e.target.value})} className="!w-auto"><option value="DRAFT">খসড়া (Draft)</option><option value="PENDING">পর্যালোচনার অপেক্ষায় (Pending)</option></select><p className="text-xs text-gray-500 mt-1">content.publish অনুমতি নেই এমন এডিটর কনটেন্ট তৈরি করলে এই অবস্থায় যাবে।</p></div></div><button className="btn mt-4" onClick={saveSettings}>✓ সংরক্ষণ করুন</button></div>}
 </div>; }
