'use client'; import {useEffect,useRef,useState} from 'react'; import {errMsg} from '@/lib/errMsg'; import {STATUS_LABELS} from '@/lib/cmsShared';
// Management table: debounced search, type/category/status/location/date filters, sort,
// pagination, bulk select + bulk actions. fixedStatus locks the status filter (status tabs).
export default function ContentTable({types,categories,perms,fixedStatus,onEdit}:{types:any[],categories:any[],perms:any,fixedStatus?:string,onEdit:(c:any)=>void}){ const [items,setItems]=useState<any[]>([]); const [total,setTotal]=useState(0); const [page,setPage]=useState(1); const [pages,setPages]=useState(1); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState(''); const [sel,setSel]=useState<Set<string>>(new Set()); const [f,setF]=useState({q:'',type:'',category:'',status:fixedStatus||'',location:'',from:'',to:'',sort:'updated_desc'}); const deb=useRef<any>(null);
 const load=async(p=page,ff=f)=>{ setLoading(true); try{ const sp=new URLSearchParams(); Object.entries(ff).forEach(([k,v])=>{ if(v) sp.set(k,String(v)); }); sp.set('page',String(p)); const r=await fetch('/api/admin/contents?'+sp.toString()); const j=await r.json().catch(()=>({})); if(r.ok){ setItems(j.items||[]); setTotal(j.total||0); setPage(j.page||1); setPages(j.pages||1); } else setMsg(j.message||errMsg(j.error)); }catch{ setMsg(errMsg('NETWORK')); } setLoading(false); };
 useEffect(()=>{ load(1,f); },[]);
 const setFilter=(k:string,v:string)=>{ const nf={...f,[k]:v}; setF(nf); if(k==='q'){ clearTimeout(deb.current); deb.current=setTimeout(()=>load(1,nf),400); } else load(1,nf); };
 const act=async(c:any,action:string)=>{ if(['trash','delete'].includes(action)&&!confirm(action==='trash'?`"${c.titleBn||c.titleEn}" ট্র্যাশে পাঠাবেন?`:`"${c.titleBn||c.titleEn}" স্থায়ীভাবে মুছে ফেলবেন? এটি ফেরানো যাবে না।`)) return; try{ const url=action==='delete'?'/api/admin/contents/'+c.id:'/api/admin/contents/'+c.id+'/action'; const r=await fetch(url,{method:action==='delete'?'DELETE':'POST',headers:{'content-type':'application/json'},body:action==='delete'?undefined:JSON.stringify({action})}); const j=await r.json().catch(()=>({})); if(r.ok){ setMsg(action==='duplicate'?'কপি তৈরি হয়েছে (খসড়া হিসেবে)':'হয়ে গেছে'); load(page,f); } else alert(j.message||errMsg(j.error)); }catch{ alert(errMsg('NETWORK')); } };
 const bulk=async(action:string)=>{ const ids=Array.from(sel); if(!ids.length) return alert('আগে কিছু কনটেন্ট নির্বাচন করুন'); if(['trash','delete'].includes(action)&&!confirm(`নির্বাচিত ${ids.length}টি কনটেন্টে এই কাজটি করবেন?`)) return; try{ const r=await fetch('/api/admin/content-bulk',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,ids})}); const j=await r.json().catch(()=>({})); if(r.ok){ setSel(new Set()); setMsg(`${j.done}টিতে সফল, ${j.skipped}টি বাদ গেছে`); load(page,f); } else alert(j.message||errMsg(j.error)); }catch{ alert(errMsg('NETWORK')); } };
 const chip=(s:string)=>({DRAFT:'bg-gray-200',PENDING:'bg-amber-100 text-amber-800',PUBLISHED:'bg-emerald-100 text-emerald-800',UNPUBLISHED:'bg-slate-200',ARCHIVED:'bg-indigo-100 text-indigo-800',TRASHED:'bg-red-100 text-red-700'} as any)[s]||'bg-gray-100';
 const toggleSel=(id2:string)=>{ const n=new Set(sel); if(n.has(id2)) n.delete(id2); else n.add(id2); setSel(n); };
 return <div>{msg&&<p className="text-emerald-700 text-sm mb-2">{msg}</p>}
 <div className="card mb-3 grid gap-2 md:grid-cols-4"><input value={f.q} onChange={e=>setFilter('q',e.target.value)} placeholder="🔍 শিরোনাম খুঁজুন"/><select value={f.type} onChange={e=>setFilter('type',e.target.value)}><option value="">সব টাইপ</option>{types.map((t:any)=><option key={t.slug} value={t.slug}>{t.icon} {t.nameBn||t.nameEn}</option>)}</select><select value={f.category} onChange={e=>setFilter('category',e.target.value)}><option value="">সব ক্যাটাগরি</option>{categories.map((c:any)=><option key={c.slug} value={c.slug}>{c.name}</option>)}</select>{!fixedStatus&&<select value={f.status} onChange={e=>setFilter('status',e.target.value)}><option value="">সব অবস্থা</option>{Object.keys(STATUS_LABELS).map(s=><option key={s} value={s}>{(STATUS_LABELS as any)[s]}</option>)}</select>}<input value={f.location} onChange={e=>setFilter('location',e.target.value)} placeholder="এলাকা (যেমন: কধুরখীল)"/><input type="date" value={f.from} onChange={e=>setFilter('from',e.target.value)} title="শুরুর তারিখ"/><input type="date" value={f.to} onChange={e=>setFilter('to',e.target.value)} title="শেষ তারিখ"/><select value={f.sort} onChange={e=>setFilter('sort',e.target.value)}><option value="updated_desc">সর্বশেষ আপডেট আগে</option><option value="updated_asc">সর্বশেষ আপডেট পরে</option><option value="created_desc">নতুন আগে</option><option value="title">শিরোনাম অনুযায়ী</option></select></div>
 {sel.size>0&&<div className="card mb-3 flex flex-wrap items-center gap-2 !py-2"><b className="text-sm">{sel.size}টি নির্বাচিত</b>{perms.publish&&<button className="btn !py-1 !px-3 text-xs" onClick={()=>bulk('publish')}>প্রকাশ</button>}{perms.archive&&<button className="btn !py-1 !px-3 text-xs" onClick={()=>bulk('archive')}>আর্কাইভ</button>}{perms.del&&<button className="btn !py-1 !px-3 text-xs" onClick={()=>bulk('trash')}>ট্র্যাশ</button>}{perms.del&&fixedStatus==='TRASHED'&&<button className="btn !py-1 !px-3 text-xs !bg-red-600" onClick={()=>bulk('delete')}>স্থায়ী মুছুন</button>}<button className="chip" onClick={()=>setSel(new Set())}>নির্বাচন ছাড়ুন</button></div>}
 {loading?<p className="text-sm text-gray-500">লোড হচ্ছে…</p>:items.length===0?<div className="card text-center text-gray-500">কোনো কনটেন্ট পাওয়া যায়নি</div>:<div className="space-y-2">{items.map((c:any)=>(<div key={c.id} className="card flex gap-3 items-start"><input type="checkbox" className="mt-1.5 !w-4" checked={sel.has(c.id)} onChange={()=>toggleSel(c.id)}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="truncate">{c.titleBn||c.titleEn}</b>{c.featured&&<span title="ফিচার্ড">⭐</span>}<span className={'chip '+chip(c.status)}>{(STATUS_LABELS as any)[c.status]||c.status}</span></div><p className="text-xs text-gray-500">{types.find((t:any)=>t.slug===c.typeSlug)?.icon} {c.typeName} • {c.categorySlug||'—'} • {c.locationText||'এলাকা নেই'} • আপডেট {String(c.updatedAt||'').slice(0,10)} • {c.createdByName}</p></div><div className="flex flex-wrap gap-1 shrink-0">{c.status==='PUBLISHED'&&<a className="btn !py-1 !px-2 text-xs" target="_blank" href={'/content/'+c.typeSlug+'/'+c.slug}>👁️</a>}{perms.edit&&c.status!=='TRASHED'&&<button className="btn !py-1 !px-2 text-xs" onClick={()=>onEdit(c)}>✎ সম্পাদনা</button>}{perms.create&&<button className="btn !py-1 !px-2 text-xs" onClick={()=>act(c,'duplicate')}>⧉ কপি</button>}{perms.publish&&['DRAFT','PENDING','UNPUBLISHED','ARCHIVED'].includes(c.status)&&<button className="btn !py-1 !px-2 text-xs" onClick={()=>act(c,'publish')}>প্রকাশ</button>}{perms.publish&&c.status==='PUBLISHED'&&<button className="btn !py-1 !px-2 text-xs" onClick={()=>act(c,'unpublish')}>অপ্রকাশ</button>}{perms.archive&&!['ARCHIVED','TRASHED'].includes(c.status)&&<button className="btn !py-1 !px-2 text-xs" onClick={()=>act(c,'archive')}>আর্কাইভ</button>}{perms.restore&&['ARCHIVED','TRASHED'].includes(c.status)&&<button className="btn !py-1 !px-2 text-xs" onClick={()=>act(c,'restore')}>পুনরুদ্ধার</button>}{perms.del&&c.status!=='TRASHED'&&<button className="btn !py-1 !px-2 text-xs !bg-red-500" onClick={()=>act(c,'trash')}>ট্র্যাশ</button>}{perms.del&&c.status==='TRASHED'&&<button className="btn !py-1 !px-2 text-xs !bg-red-700" onClick={()=>act(c,'delete')}>স্থায়ী মুছুন</button>}</div></div>))}</div>}
 <div className="flex items-center gap-2 mt-3 text-sm"><span>মোট {total}টি</span><button className="btn !py-1 !px-3 text-xs" disabled={page<=1} onClick={()=>load(page-1,f)}>← আগে</button><span>{page}/{pages}</span><button className="btn !py-1 !px-3 text-xs" disabled={page>=pages} onClick={()=>load(page+1,f)}>পরে →</button></div></div>; }
