'use client'; import {useEffect,useState} from 'react'; import {errMsg} from '@/lib/errMsg';
// Media Library: every stored image with size + real usage references. Delete is blocked by
// the server while any content/post/ad references the image (button explains why).
export default function MediaLibrary(){ const [images,setImages]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [msg,setMsg]=useState('');
 const load=async()=>{ setLoading(true); try{ const r=await fetch('/api/admin/media'); const j=await r.json().catch(()=>({})); if(r.ok) setImages(j.images||[]); else setMsg(j.message||errMsg(j.error)); }catch{ setMsg(errMsg('NETWORK')); } setLoading(false); };
 useEffect(()=>{ load(); },[]);
 const del=async(im:any)=>{ if(im.usedBy.length) return alert('এই ছবি ব্যবহৃত হচ্ছে:\n'+im.usedBy.join('\n')+'\nআগে সেখান থেকে ছবিটি সরান।'); if(!confirm(`"${im.name}" ছবিটি স্থায়ীভাবে মুছে ফেলবেন?`)) return; try{ const r=await fetch('/api/admin/media',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({name:im.name})}); const j=await r.json().catch(()=>({})); if(r.ok){ setMsg('ছবি মোছা হয়েছে'); load(); } else alert(j.message||errMsg(j.error)); }catch{ alert(errMsg('NETWORK')); } };
 if(loading) return <p className="text-sm text-gray-500">লোড হচ্ছে…</p>;
 return <div>{msg&&<p className="text-emerald-700 text-sm mb-2">{msg}</p>}<h2 className="font-black mb-3">মিডিয়া লাইব্রেরি ({images.length}টি ছবি, {images.filter((i:any)=>i.usedBy.length).length}টি ব্যবহৃত)</h2>{images.length===0?<div className="card text-center text-gray-500">কোনো ছবি নেই — কনটেন্ট ফর্ম থেকে ছবি আপলোড করলেই এখানে আসবে</div>:<div className="grid grid-cols-2 md:grid-cols-4 gap-3">{images.map((im:any)=>(<div key={im.name} className="card !p-2"><img src={im.url} alt={im.name} loading="lazy" className="w-full h-28 object-cover rounded-lg"/><p className="text-[11px] mt-1 truncate" dir="ltr">{im.name}</p><p className="text-[11px] text-gray-500">{Math.max(1,Math.round((im.size||0)/1024))} KB</p>{im.usedBy.length>0?<p className="text-[11px] text-amber-700">ব্যবহৃত: {im.usedBy.slice(0,2).join('; ')}{im.usedBy.length>2?'…':''}</p>:<p className="text-[11px] text-gray-400">অব্যবহৃত</p>}<button disabled={im.usedBy.length>0} title={im.usedBy.length?'ব্যবহৃত ছবি মোছা যাবে না':''} className={'btn !py-1 !px-2 text-xs mt-1 '+(im.usedBy.length?'opacity-40':'!bg-red-500')} onClick={()=>del(im)}>🗑️ মুছুন</button></div>))}</div>}</div>; }
