'use client'; import {useState} from 'react'; import {errMsg} from '@/lib/errMsg';
// Categories + Subcategories and Locations editors (categories.manage). Deletes go through
// the API dependency checks — in-use entries are refused with a Bengali reason, never orphaned.
export function CategoriesAdmin({categories,onChanged}:{categories:any[],onChanged:()=>void}){ const [edit,setEdit]=useState<any>(null); const [msg,setMsg]=useState('');
 const call=async(url:string,method:string,body?:any)=>{ try{ const r=await fetch(url,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined}); const j=await r.json().catch(()=>({})); if(r.ok){ onChanged(); return true; } alert(j.message||errMsg(j.error)); }catch{ alert(errMsg('NETWORK')); } return false; };
 const save=async()=>{ if(!edit.name) return alert('নাম আবশ্যক'); const ok=edit.__new?await call('/api/admin/categories','POST',edit):await call('/api/admin/categories','PATCH',edit); if(ok){ setEdit(null); setMsg('ক্যাটাগরি সংরক্ষণ হয়েছে'); } };
 const del=async(c:any)=>{ if(confirm(`"${c.name}" ক্যাটাগরি মুছবেন? কনটেন্ট/পোস্ট থাকলে সার্ভার বাধা দেবে।`)) await call('/api/admin/categories?slug='+encodeURIComponent(c.slug),'DELETE'); };
 if(edit) return <div className="card"><h3 className="font-black mb-3">{edit.slug?'✎ ক্যাটাগরি সম্পাদনা':'➕ নতুন ক্যাটাগরি'}</h3><div className="grid md:grid-cols-3 gap-3"><div><label className="block text-sm font-bold">নাম *</label><input value={edit.name||''} onChange={e=>setEdit({...edit,name:e.target.value})}/></div><div><label className="block text-sm font-bold">Slug {edit.slug?'(বদলানো যাবে না)':'(খালি রাখলে নাম থেকে হবে)'}</label><input value={edit.slug||''} disabled={!!edit.slug&&!!edit.id} onChange={e=>setEdit({...edit,slug:e.target.value})} dir="ltr"/></div><div><label className="block text-sm font-bold">আইকন (emoji)</label><input value={edit.icon||'📌'} onChange={e=>setEdit({...edit,icon:e.target.value})}/></div><div><label className="block text-sm font-bold">রং</label><input type="color" value={edit.color||'#0a7a54'} onChange={e=>setEdit({...edit,color:e.target.value})} className="!w-16"/></div><div><label className="block text-sm font-bold">ক্রম</label><input type="number" value={edit.order||0} onChange={e=>setEdit({...edit,order:Number(e.target.value)})}/></div><label className="flex items-center gap-2 text-sm font-bold mt-5"><input type="checkbox" className="!w-4" checked={edit.enabled!==false} onChange={e=>setEdit({...edit,enabled:e.target.checked})}/>সক্রিয়</label><div className="md:col-span-3"><label className="block text-sm font-bold">বিবরণ</label><input value={edit.desc||''} onChange={e=>setEdit({...edit,desc:e.target.value})}/></div></div>
 <div className="mt-3"><label className="block text-sm font-bold">সাবক্যাটাগরি</label><div className="flex flex-wrap gap-2">{(edit.subcategories||[]).map((s:any,i:number)=>(<span key={i} className="chip">{s.name}<button type="button" className="ml-1 text-red-600" onClick={()=>setEdit({...edit,subcategories:edit.subcategories.filter((_:any,j:number)=>j!==i)})}>✕</button></span>))}</div><div className="flex gap-2 mt-2"><input id="cms-newsub" placeholder="নতুন সাবক্যাটাগরির নাম" className="!w-64"/><button type="button" className="btn !py-1 !px-3 text-xs" onClick={()=>{ const inp=document.getElementById('cms-newsub') as HTMLInputElement; const name=inp.value.trim(); if(name){ setEdit({...edit,subcategories:[...(edit.subcategories||[]),{name,slug:''}]}); inp.value=''; } }}>যোগ করুন</button></div></div>
 <div className="flex gap-2 mt-4"><button className="btn" onClick={save}>✓ সংরক্ষণ করুন</button><button className="btn !bg-gray-400" onClick={()=>setEdit(null)}>বাতিল</button></div></div>;
 return <div>{msg&&<p className="text-emerald-700 text-sm mb-2">{msg}</p>}<div className="flex items-center mb-3"><h2 className="font-black">ক্যাটাগরি ({categories.length}টি)</h2><button className="btn !py-1.5 !px-3 text-xs ml-auto" onClick={()=>setEdit({__new:true,name:'',slug:'',icon:'📌',color:'#0a7a54',order:categories.length+1,enabled:true,subcategories:[]})}>➕ নতুন ক্যাটাগরি</button></div><div className="space-y-2">{categories.map((c:any)=>(<div key={c.slug} className="card flex items-center gap-3"><span className="text-xl">{c.icon||'📌'}</span><div className="flex-1 min-w-0"><b className="block truncate">{c.name} <span className="text-xs text-gray-400" dir="ltr">/{c.slug}</span></b><p className="text-xs text-gray-500">ক্রম {c.order} • পোস্ট {c.posts||0}টি • কনটেন্ট {c.contents||0}টি • সাব {c.subcategories?.length||0}টি</p></div><span className={'chip '+(c.enabled?'bg-emerald-100':'bg-red-100 text-red-700')}>{c.enabled?'সক্রিয়':'নিষ্ক্রিয়'}</span><button className="btn !py-1 !px-2 text-xs" onClick={async()=>await call('/api/admin/categories','POST',{slug:c.slug,enabled:!c.enabled})}>{c.enabled?'বন্ধ':'চালু'}</button><button className="btn !py-1 !px-2 text-xs" onClick={()=>setEdit(JSON.parse(JSON.stringify(c)))}>✎</button><button className="btn !py-1 !px-2 text-xs !bg-red-500" onClick={()=>del(c)}>🗑️</button></div>))}</div></div>; }
export function LocationsAdmin({locations,onChanged}:{locations:any[],onChanged:()=>void}){ const [edit,setEdit]=useState<any>(null); const [msg,setMsg]=useState('');
 const call=async(url:string,method:string,body?:any)=>{ try{ const r=await fetch(url,{method,headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined}); const j=await r.json().catch(()=>({})); if(r.ok){ onChanged(); return true; } alert(j.message||errMsg(j.error)); }catch{ alert(errMsg('NETWORK')); } return false; };
 const save=async()=>{ if(!edit.name) return alert('এলাকার নাম আবশ্যক'); const ok=edit.id?await call('/api/admin/locations','PATCH',edit):await call('/api/admin/locations','POST',edit); if(ok){ setEdit(null); setMsg('এলাকা সংরক্ষণ হয়েছে'); } };
 if(edit) return <div className="card"><h3 className="font-black mb-3">{edit.id?'✎ এলাকা সম্পাদনা':'➕ নতুন এলাকা'}</h3><div className="grid md:grid-cols-3 gap-3">{[['name','এলাকার নাম *'],['area','এলাকা / গ্রাম'],['road','সড়ক'],['landmark','ল্যান্ডমার্ক']].map(([k,l])=>(<div key={k}><label className="block text-sm font-bold">{l}</label><input value={edit[k]||''} onChange={e=>setEdit({...edit,[k]:e.target.value})}/></div>))}<div><label className="block text-sm font-bold">Latitude</label><input type="number" step="any" value={edit.lat??''} onChange={e=>setEdit({...edit,lat:e.target.value})} dir="ltr"/></div><div><label className="block text-sm font-bold">Longitude</label><input type="number" step="any" value={edit.lng??''} onChange={e=>setEdit({...edit,lng:e.target.value})} dir="ltr"/></div></div><div className="flex gap-2 mt-4"><button className="btn" onClick={save}>✓ সংরক্ষণ করুন</button><button className="btn !bg-gray-400" onClick={()=>setEdit(null)}>বাতিল</button></div></div>;
 return <div>{msg&&<p className="text-emerald-700 text-sm mb-2">{msg}</p>}<div className="flex items-center mb-3"><h2 className="font-black">এলাকা / লোকেশন ({locations.length}টি)</h2><button className="btn !py-1.5 !px-3 text-xs ml-auto" onClick={()=>setEdit({name:'',area:'',road:'',landmark:'',lat:'',lng:''})}>➕ নতুন এলাকা</button></div><div className="space-y-2">{locations.map((l:any)=>(<div key={l.id} className="card flex items-center gap-3"><span>📍</span><div className="flex-1 min-w-0"><b className="block truncate">{l.name}</b><p className="text-xs text-gray-500">{[l.area,l.road,l.landmark].filter(Boolean).join(' • ')}</p></div><button className="btn !py-1 !px-2 text-xs" onClick={()=>setEdit({...l})}>✎</button><button className="btn !py-1 !px-2 text-xs !bg-red-500" onClick={async()=>{ if(confirm(`"${l.name}" এলাকা মুছবেন? ব্যবহৃত হলে সার্ভার বাধা দেবে।`)) await call('/api/admin/locations?id='+encodeURIComponent(l.id),'DELETE'); }}>🗑️</button></div>))}</div></div>; }
