'use client'; import {useState} from 'react'; import {errMsg} from '@/lib/errMsg'; import {FIELD_TYPES,FIELD_TYPE_LABELS} from '@/lib/cmsShared';
// Content Type Builder: create/rename/reorder/deactivate types and design their field
// schemas (add/remove/reorder fields, required, card/detail visibility, select options).
const blankField=(n:number)=>({key:'',label:'',type:'Text',required:false,options:[],order:n,showInCard:false,showInDetail:true,defaultValue:''});
export default function TypeBuilder({types,onChanged}:{types:any[],onChanged:()=>void}){ const [editing,setEditing]=useState<any>(null); const [err,setErr]=useState(''); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
 const startNew=()=>setEditing({id:'',slug:'',nameBn:'',nameEn:'',description:'',icon:'📁',publicListing:true,enabled:true,order:types.length+1,fields:[],builtin:false});
 const startEdit=(t:any)=>setEditing(JSON.parse(JSON.stringify(t)));
 const setF=(k:string,v:any)=>setEditing((p:any)=>({...p,[k]:v}));
 const setField=(i:number,k:string,v:any)=>setEditing((p:any)=>({...p,fields:p.fields.map((f:any,j:number)=>j===i?{...f,[k]:v}:f)}));
 const move=(i:number,d:number)=>setEditing((p:any)=>{ const fs=[...p.fields]; const j=i+d; if(j<0||j>=fs.length) return p; [fs[i],fs[j]]=[fs[j],fs[i]]; fs.forEach((f:any,k:number)=>f.order=k+1); return {...p,fields:fs}; });
 const save=async()=>{ if(busy) return; setBusy(true); setErr(''); const body={...editing,fields:editing.fields.map((f:any,i:number)=>({...f,options:typeof f.options==='string'?f.options.split(',').map((x:string)=>x.trim()).filter(Boolean):f.options,order:i+1}))}; try{ const r=await fetch(editing.id?'/api/admin/content-types/'+editing.id:'/api/admin/content-types',{method:editing.id?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const j=await r.json().catch(()=>({})); if(r.ok){ setEditing(null); setMsg('টাইপ সংরক্ষণ হয়েছে'); onChanged(); } else setErr(j.message||errMsg(j.error)); }catch{ setErr(errMsg('NETWORK')); } setBusy(false); };
 const del=async(t:any)=>{ if(!confirm(`"${t.nameBn||t.nameEn}" টাইপটি মুছে ফেলবেন? (কনটেন্ট থাকলে সার্ভার বাধা দেবে)`)) return; try{ const r=await fetch('/api/admin/content-types/'+t.id,{method:'DELETE'}); const j=await r.json().catch(()=>({})); if(r.ok){ setMsg('টাইপ মোছা হয়েছে'); onChanged(); } else alert(j.message||errMsg(j.error)); }catch{ alert(errMsg('NETWORK')); } };
 const toggle=async(t:any,k:string)=>{ try{ const r=await fetch('/api/admin/content-types/'+t.id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({...t,[k]:!t[k]})}); if(r.ok) onChanged(); else { const j=await r.json().catch(()=>({})); alert(j.message||errMsg(j.error)); } }catch{ alert(errMsg('NETWORK')); } };
 if(editing) return <div className="card"><h2 className="font-black mb-3">{editing.id?'✎ টাইপ সম্পাদনা':'➕ নতুন কনটেন্ট টাইপ'}</h2>{err&&<p className="bg-red-50 text-red-700 text-sm rounded-xl px-3 py-2 mb-3">{err}</p>}
 <div className="grid md:grid-cols-3 gap-3"><div><label className="block text-sm font-bold">বাংলা নাম *</label><input value={editing.nameBn} onChange={e=>setF('nameBn',e.target.value)} placeholder="যেমন: লাইব্রেরি"/></div><div><label className="block text-sm font-bold">English Name</label><input value={editing.nameEn} onChange={e=>setF('nameEn',e.target.value)} dir="ltr" placeholder="Library"/></div><div><label className="block text-sm font-bold">Slug *</label><input value={editing.slug} onChange={e=>setF('slug',e.target.value)} dir="ltr" placeholder="library"/></div>
 <div><label className="block text-sm font-bold">আইকন (emoji)</label><input value={editing.icon} onChange={e=>setF('icon',e.target.value)} className="!w-24"/></div><div><label className="block text-sm font-bold">ক্রম</label><input type="number" value={editing.order} onChange={e=>setF('order',Number(e.target.value))} className="!w-24"/></div><div className="flex flex-col gap-1 mt-5"><label className="text-sm flex items-center gap-2"><input type="checkbox" className="!w-4" checked={!!editing.publicListing} onChange={e=>setF('publicListing',e.target.checked)}/>পাবলিক তালিকায় দেখাবে</label><label className="text-sm flex items-center gap-2"><input type="checkbox" className="!w-4" checked={!!editing.enabled} onChange={e=>setF('enabled',e.target.checked)}/>সক্রিয়</label></div>
 <div className="md:col-span-3"><label className="block text-sm font-bold">বিবরণ</label><textarea rows={2} value={editing.description} onChange={e=>setF('description',e.target.value)}/></div></div>
 <h3 className="font-black mt-5 mb-2">ফিল্ডসমূহ ({editing.fields.length}টি)</h3><div className="space-y-2">{editing.fields.map((f:any,i:number)=>(<div key={i} className="bg-slate-50 rounded-xl p-2 grid md:grid-cols-12 gap-2 items-end"><div className="md:col-span-2"><label className="text-[11px] font-bold">Key (ইংরেজি)</label><input value={f.key} onChange={e=>setField(i,'key',e.target.value)} dir="ltr" placeholder="establishedYear"/></div><div className="md:col-span-3"><label className="text-[11px] font-bold">Label</label><input value={f.label} onChange={e=>setField(i,'label',e.target.value)} placeholder="প্রতিষ্ঠার সাল"/></div><div className="md:col-span-2"><label className="text-[11px] font-bold">ধরন</label><select value={f.type} onChange={e=>setField(i,'type',e.target.value)}>{FIELD_TYPES.map((t:string)=><option key={t} value={t}>{(FIELD_TYPE_LABELS as any)[t]}</option>)}</select></div>{['Select','MultiSelect'].includes(f.type)&&<div className="md:col-span-3"><label className="text-[11px] font-bold">অপশন (কমা দিয়ে)</label><input value={Array.isArray(f.options)?f.options.join(', '):f.options} onChange={e=>setField(i,'options',e.target.value)} dir="ltr"/></div>}<div className="md:col-span-2 flex flex-wrap gap-x-2 gap-y-1 text-[11px]"><label className="flex items-center gap-1"><input type="checkbox" className="!w-3.5" checked={!!f.required} onChange={e=>setField(i,'required',e.target.checked)}/>আবশ্যক</label><label className="flex items-center gap-1"><input type="checkbox" className="!w-3.5" checked={!!f.showInCard} onChange={e=>setField(i,'showInCard',e.target.checked)}/>কার্ডে</label><label className="flex items-center gap-1"><input type="checkbox" className="!w-3.5" checked={f.showInDetail!==false} onChange={e=>setField(i,'showInDetail',e.target.checked)}/>ডিটেইলে</label></div><div className="flex gap-1"><button type="button" className="btn !py-0.5 !px-2 text-xs" onClick={()=>move(i,-1)}>↑</button><button type="button" className="btn !py-0.5 !px-2 text-xs" onClick={()=>move(i,1)}>↓</button><button type="button" className="btn !py-0.5 !px-2 text-xs !bg-red-500" onClick={()=>setEditing((p:any)=>({...p,fields:p.fields.filter((_:any,j:number)=>j!==i)}))}>✕</button></div></div>))}</div>
 <button type="button" className="btn !py-1.5 !px-3 text-xs mt-3" onClick={()=>setEditing((p:any)=>({...p,fields:[...p.fields,blankField(p.fields.length+1)]}))}>+ ফিল্ড যোগ করুন</button>
 <div className="flex gap-2 mt-5"><button disabled={busy} onClick={save} className="btn">{busy?'সংরক্ষণ হচ্ছে…':'✓ সংরক্ষণ করুন'}</button><button className="btn !bg-gray-400" onClick={()=>setEditing(null)}>বাতিল</button></div></div>;
 return <div>{msg&&<p className="text-emerald-700 text-sm mb-2">{msg}</p>}<div className="flex items-center gap-2 mb-3"><h2 className="font-black">কনটেন্ট টাইপসমূহ ({types.length}টি)</h2><button className="btn !py-1.5 !px-3 text-xs ml-auto" onClick={startNew}>➕ নতুন টাইপ</button></div><div className="space-y-2">{types.map((t:any)=>(<div key={t.id} className="card flex items-center gap-3"><span className="text-2xl">{t.icon}</span><div className="min-w-0 flex-1"><b className="block truncate">{t.nameBn||t.nameEn} <span className="text-xs text-gray-400" dir="ltr">/content/{t.slug}</span>{t.builtin&&<span className="chip ml-2">বিল্ট-ইন</span>}</b><p className="text-xs text-gray-500">{t.fields.length}টি ফিল্ড • {t.contents||0}টি কনটেন্ট • {t.publicListing?'পাবলিক':'পাবলিক নয়'}</p></div><span className={'chip '+(t.enabled?'bg-emerald-100':'bg-red-100 text-red-700')}>{t.enabled?'সক্রিয়':'নিষ্ক্রিয়'}</span><button className="btn !py-1 !px-2 text-xs" onClick={()=>toggle(t,'enabled')}>{t.enabled?'নিষ্ক্রিয়':'সক্রিয়'}</button><button className="btn !py-1 !px-2 text-xs" onClick={()=>toggle(t,'publicListing')}>👁️</button><button className="btn !py-1 !px-2 text-xs" onClick={()=>startEdit(t)}>✎</button><button className="btn !py-1 !px-2 text-xs !bg-red-500" onClick={()=>del(t)}>🗑️</button></div>))}</div></div>; }
