import {readDBAsync,mutateDBAsync} from '@/lib/db'; import {Shell,bn} from '@/components/ui'; import {sanitizeContentType,sanitizeContent,seedBuiltinTypesIfEmpty,contentTitle,locationText,featuredImage,fieldDisplay,isPublishedVisible} from '@/lib/cms'; import {SITE_URL} from '@/lib/site'; import Link from 'next/link'; import {notFound} from 'next/navigation'; export const dynamic='force-dynamic';
// Public detail: renders ONLY a PUBLISHED item of an enabled publicListing type — every
// other status (draft/pending/unpublished/archived/trashed) is a hard 404. Fields render
// per the type's own schema (showInDetail), gallery, maps link/embed, SEO/OG + JSON-LD
// built exclusively from stored values — nothing is invented.
const dec=(s:string)=>{ try{ return decodeURIComponent(s); }catch{ return s; } };
async function load(typeSlug:string,slug:string){ typeSlug=dec(typeSlug); slug=dec(slug); let db=await readDBAsync(); if(!db.content_types.length){ await mutateDBAsync((d:any)=>{ seedBuiltinTypesIfEmpty(d,'system'); }); db=await readDBAsync(); } const type=sanitizeContentType(db.content_types.find((x:any)=>x.slug===typeSlug)); const c=sanitizeContent((db.contents||[]).find((x:any)=>x.typeSlug===typeSlug&&x.slug===slug)); return {db,type,c}; }
const abs=(u:string)=>u?(u.startsWith('http')?u:SITE_URL+u):'';
export async function generateMetadata({params}:{params:{typeSlug:string,slug:string}}){ const {type,c}=await load(params.typeSlug,params.slug); if(!isPublishedVisible(c,type)) return {title:'পাওয়া যায়নি — বোয়ালখালী কানেক্ট'}; const title=c.seo.title||contentTitle(c)+' — বোয়ালখালী কানেক্ট'; const desc=c.seo.description||c.shortDesc||String(c.fullDesc||'').slice(0,160); const og=c.seo.ogImage||(featuredImage(c)?.url||''); const m:any={title,description:desc,openGraph:{title,description:desc}}; if(og) m.openGraph.images=[{url:abs(og),alt:contentTitle(c)}]; if(c.seo.canonical) m.alternates={canonical:c.seo.canonical}; return m; }
export default async function P({params}:{params:{typeSlug:string,slug:string}}){ const {db,type,c}=await load(params.typeSlug,params.slug); if(!isPublishedVisible(c,type)) notFound(); const title=contentTitle(c); const img=featuredImage(c); const detailFields=type.fields.filter((f:any)=>f.showInDetail); const loc=c.location||{}; const hasLoc=!!(locationText(c)||loc.address||loc.mapsUrl||(loc.lat!==null&&loc.lng!==null)); const cats:any={}; db.categories.forEach((x:any)=>{ cats[x.slug]=x.name; }); const ld:any={'@context':'https://schema.org','@type':'Thing',name:title}; if(c.shortDesc||c.fullDesc) ld.description=c.shortDesc||String(c.fullDesc).slice(0,300); if(img) ld.image=abs(img.url); if(hasLoc){ ld.address={'@type':'PostalAddress',addressLocality:[loc.area,loc.union,loc.upazila].filter(Boolean).join(', ')||undefined,streetAddress:loc.address||undefined,addressRegion:loc.district||undefined,addressCountry:'BD'}; if(loc.lat!==null&&loc.lng!==null) ld.geo={'@type':'GeoCoordinates',latitude:loc.lat,longitude:loc.lng}; } const paras=String(c.fullDesc||'').split(/\n\s*\n/).map((s:string)=>s.trim()).filter(Boolean);
 return <Shell><main className="max-w-3xl mx-auto p-4"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(ld)}}/><nav className="text-xs text-gray-500"><Link href="/content" className="font-bold text-brand-700">তথ্য ভাণ্ডার</Link> / <Link href={'/content/'+type.slug} className="font-bold text-brand-700">{type.nameBn||type.nameEn}</Link></nav>
 <h1 className="font-black text-2xl mt-2 font-display">{title}</h1>{c.titleEn&&c.titleBn&&<p className="text-sm text-gray-400" dir="ltr">{c.titleEn}</p>}
 {img&&<figure className="mt-3"><img src={img.url} alt={img.alt||title} className="w-full max-h-80 object-cover rounded-2xl"/>{img.caption&&<figcaption className="text-xs text-gray-400 mt-1">{img.caption}</figcaption>}</figure>}
 {c.tags.length>0&&<div className="flex flex-wrap gap-1.5 mt-3">{c.tags.map((t:string)=><span key={t} className="chip bg-brand-50">#{t}</span>)}</div>}
 {c.shortDesc&&<p className="mt-3 text-gray-700 font-medium">{c.shortDesc}</p>}
 {paras.map((p:string,i:number)=><p key={i} className="mt-3 leading-relaxed whitespace-pre-line">{p}</p>)}
 {detailFields.length>0&&<dl className="mt-5 grid md:grid-cols-2 gap-x-4 gap-y-3 rounded-2xl bg-slate-50 p-4">{detailFields.map((f:any)=>{ const v=c.fields[f.key]; if(f.type==='Image') return v?<div key={f.key}><dt className="text-xs text-gray-400">{f.label}</dt><dd><img src={v} alt={f.label} loading="lazy" className="mt-1 h-28 rounded-xl object-cover"/></dd></div>:null; if(f.type==='MultipleImages') return Array.isArray(v)&&v.length?<div key={f.key} className="md:col-span-2"><dt className="text-xs text-gray-400">{f.label}</dt><dd className="mt-1 flex flex-wrap gap-2">{v.map((u:string,i:number)=><img key={i} src={u} alt={f.label} loading="lazy" className="h-24 w-32 rounded-xl object-cover"/>)}</dd></div>:null; const d=fieldDisplay(f,v); if(!d||v===false) return null; let val:any=d; if(f.type==='URL'||f.type==='GoogleMapsURL'||f.type==='File') val=<a href={String(v)} target="_blank" rel="noreferrer" className="text-brand-700 font-bold break-all">{d} ↗</a>; else if(f.type==='Phone') val=<a href={'tel:'+String(v).replace(/\s/g,'')} className="text-brand-700 font-bold">📞 {d}</a>; else if(f.type==='Email') val=<a href={'mailto:'+v} className="text-brand-700 font-bold">{d}</a>; return <div key={f.key}><dt className="text-xs text-gray-400">{f.label}</dt><dd className="font-bold text-sm whitespace-pre-line">{val}</dd></div>; })}</dl>}
 {c.images.length>1&&<div className="mt-5"><h2 className="font-black mb-2">🖼️ গ্যালারি</h2><div className="grid grid-cols-2 md:grid-cols-3 gap-2">{c.images.map((im:any,i:number)=>(<figure key={i}><img src={im.url} alt={im.alt||title} loading="lazy" className="h-36 w-full rounded-xl object-cover"/>{im.caption&&<figcaption className="text-[11px] text-gray-400 mt-0.5">{im.caption}</figcaption>}</figure>))}</div></div>}
 {hasLoc&&<div className="card mt-5"><h2 className="font-black">📍 ঠিকানা ও অবস্থান</h2>{loc.address&&<p className="text-sm mt-1">{loc.address}</p>}{locationText(c)&&<p className="text-sm text-gray-500">{locationText(c)}</p>}{(loc.lat!==null&&loc.lng!==null)?<><div className="mt-3 overflow-hidden rounded-xl"><iframe title="Google Maps" loading="lazy" className="h-64 w-full" src={'https://www.google.com/maps?q='+loc.lat+','+loc.lng+'&output=embed'}/></div><a className="btn mt-3" target="_blank" rel="noreferrer" href={'https://www.google.com/maps/search/?api=1&query='+loc.lat+','+loc.lng}>🗺️ Google Maps-এ দেখুন</a></>:loc.mapsUrl?<a className="btn mt-3" target="_blank" rel="noreferrer" href={loc.mapsUrl}>🗺️ Google Maps-এ দেখুন</a>:null}</div>}
 <p className="text-xs text-gray-400 mt-5">তথ্যটি সর্বশেষ আপডেট: {c.updatedAt?new Date(c.updatedAt).toLocaleDateString('bn-BD'):''}{c.categorySlug&&cats[c.categorySlug]?` • ক্যাটাগরি: ${cats[c.categorySlug]}`:''}</p>
 <Link href={'/content/'+type.slug} className="btn mt-4">← {type.nameBn||type.nameEn} তালিকায় ফিরুন</Link></main></Shell>; }
