'use client'; import {useState} from 'react'; const cats=[['house','বাসা ভাড়া'],['market','বাই-সেল'],['doctor','ডাক্তার'],['blood','রক্তদাতা'],['secret','গোপন তথ্য'],['food','রেস্টুরেন্ট ও খাবার'],['transport','বাস ও ট্রেন'],['jobs','চাকরি ও নিয়োগ'],['lost','হারানো ও প্রাপ্তি'],['legal','আইনি সহায়তা'],['event','অনুষ্ঠান ও ডেকোর'],['electrician','ইলেকট্রিশিয়ান'],['plumber','প্লাম্বার'],['ac','এসি/ফ্রিজ'],['driver','ড্রাইভার'],['tutor','গৃহশিক্ষক'],['vet','পশু চিকিৎসক'],['mason','রাজমিস্ত্রি'],['mobile','মোবাইল মেকার']];
function Switch({v,onClick}:{v:boolean;onClick:()=>void}){ return <button type="button" onClick={onClick} className={`w-14 h-8 rounded-full p-1 shrink-0 ${v?'bg-emerald-500':'bg-gray-300'}`}><span className={`block w-6 h-6 bg-white rounded-full ${v?'ml-auto':''}`}/></button>; }
export default function P({initial,settings}:{initial:Record<string,boolean>;settings:any}){const [tab,setTab]=useState('general'); const [on,setOn]=useState<Record<string,boolean>>(()=>Object.fromEntries(cats.map(c=>[c[0],initial[c[0]]!==false]))); const [s,setS]=useState<any>({...settings}); const [cm,setCm]=useState(''); const [tm,setTm]=useState(''); const [gm,setGm]=useState(''); const [nm,setNm]=useState('');
 const saveSettings=async(patch:any)=>{ const r=await fetch('/api/admin/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({settings:patch})}); if(r.ok){ const j=await r.json(); if(j.settings) setS(j.settings); else setS((p:any)=>({...p,...patch})); return true; } return false; };
 const changeCreds=async(ev:any)=>{ev.preventDefault(); const f=new FormData(ev.currentTarget); const body:any=Object.fromEntries(f); Object.keys(body).forEach(k=>{if(!body[k]) delete body[k]}); const r=await fetch('/api/admin/credentials',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const j=await r.json(); setCm(r.ok?'✅ অ্যাডমিন লগইন তথ্য পরিবর্তন হয়েছে — পরের লগইনে নতুন তথ্য ব্যবহার করুন':('❌ '+j.error)); if(r.ok) ev.currentTarget.reset()};
 const toggle=async(slug:string)=>{const v=!on[slug]; const r=await fetch('/api/admin/features',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug,enabled:v})}); if(r.ok){ setOn(prev=>({...prev,[slug]:v})); setTm(''); } else setTm('❌ টগল সংরক্ষণ করা যায়নি — আবার চেষ্টা করুন'); };
 const saveGeneral=async(ev:any)=>{ev.preventDefault(); const ok=await saveSettings({siteName:s.siteName||'',tagline:s.tagline||'',contactEmail:s.contactEmail||'',contactPhone:s.contactPhone||'',maintenanceMode:!!s.maintenanceMode}); setGm(ok?'✅ সাধারণ সেটিংস সংরক্ষিত হয়েছে':'❌ সংরক্ষণ করা যায়নি — আবার চেষ্টা করুন'); };
 const flipNotif=async(k:string)=>{ const v=!s[k]; const ok=await saveSettings({[k]:v}); setNm(ok?'':'❌ সংরক্ষণ করা যায়নি — আবার চেষ্টা করুন'); };
 const notifRows:[string,string,string][]=[['notifyPostModeration','পোস্ট মডারেশন নোটিফিকেশন','পোস্ট অনুমোদিত/বাতিল/লুকানো হলে পোস্টদাতাকে জানানো হবে'],['notifyAdminOnPending','নতুন পোস্টের অ্যালার্ট (টিম)','নতুন পোস্ট এলে অ্যাডমিন/মডারেটরদের অনুমোদনের জন্য নোটিফিকেশন যাবে'],['sirenHomeBanner','হোমে জরুরি সাইরেন ব্যানার','সক্রিয় জরুরি সাইরেন হোমপেজের LIVE অংশে দেখানো হবে']];
 const tabs:[string,string][]=[['general','সাধারণ সেটিংস'],['features','ফিচার কন্ট্রোল'],['notif','নোটিফিকেশন']];
 return <div><div className="flex gap-2 mb-3">{tabs.map(([k,l])=>(<button key={k} type="button" onClick={()=>setTab(k)} className={`chip border ${tab===k?'bg-slate-900 text-white':''}`}>{l}</button>))}</div>
 {tab==='general'&&<><form className="card space-y-3" onSubmit={saveGeneral}><h1 className="font-black text-xl">সাধারণ সেটিংস</h1><p className="text-sm text-gray-500">সাইটের নাম ও ট্যাগলাইন হেডার/ফুটারে সঙ্গে সঙ্গে বদলে যাবে।</p>{gm&&<p className="text-sm">{gm}</p>}<label>সাইটের নাম<input value={s.siteName||''} onChange={e=>setS({...s,siteName:e.target.value})} required/></label><label>ট্যাগলাইন<input value={s.tagline||''} onChange={e=>setS({...s,tagline:e.target.value})}/></label><label>যোগাযোগের ইমেইল<input value={s.contactEmail||''} onChange={e=>setS({...s,contactEmail:e.target.value})} placeholder="যেমন: help@example.com"/></label><label>যোগাযোগের ফোন<input value={s.contactPhone||''} onChange={e=>setS({...s,contactPhone:e.target.value})} placeholder="যেমন: 01XXXXXXXXX"/></label><div className="flex items-center justify-between border rounded-2xl p-3"><div><b>রক্ষণাবেক্ষণ মোড</b><p className="text-xs text-gray-500">চালু থাকলে পুরো সাইটে ব্যানার দেখাবে এবং সাধারণ ইউজাররা নতুন পোস্ট করতে পারবেন না (টিম পারবে)।</p></div><Switch v={!!s.maintenanceMode} onClick={()=>setS({...s,maintenanceMode:!s.maintenanceMode})}/></div><button className="btn">সংরক্ষণ করুন</button></form><form className="card mt-4 space-y-3" onSubmit={changeCreds}><h2 className="font-black text-lg">অ্যাডমিন লগইন পরিবর্তন</h2><p className="text-sm text-gray-500">বর্তমান পাসওয়ার্ড যাচাই করে অ্যাডমিনের ইমেইল/ইউজারনেম ও পাসওয়ার্ড বদলান। ইউজারনেম <b>admin</b> দিয়েও লগইন করা যায়।</p>{cm&&<p className="text-sm">{cm}</p>}<label>বর্তমান পাসওয়ার্ড *<input name="currentPassword" type="password" required/></label><label>নতুন ইমেইল/ইউজারনেম (ঐচ্ছিক)<input name="newEmail" placeholder="খালি রাখলে আগেরটাই থাকবে"/></label><label>নতুন পাসওয়ার্ড (ঐচ্ছিক)<input name="newPassword" type="password" minLength={5} placeholder="কমপক্ষে ৫ অক্ষর"/></label><label>নতুন পাসওয়ার্ড আবার লিখুন<input name="confirmPassword" type="password"/></label><button className="btn">সংরক্ষণ করুন</button></form></>}
 {tab==='features'&&<div className="card"><h1 className="font-black text-xl">ফিচার কন্ট্রোল (Feature Toggles)</h1><p className="text-sm text-gray-500">যেকোনো সার্ভিস বা ক্যাটাগরি যেকোনো সময় অন বা অফ করুন। অফ করা ফিচার ইউজাররা দেখতে পারবে না। Disabled হলে citizen nav থেকে hide + নতুন সাবমিশন block, পুরনো রেকর্ড থাকে।</p>{tm&&<p className="text-sm mt-2">{tm}</p>}{cats.map(([slug,name])=>(<div key={slug} className="flex justify-between border rounded-2xl p-3 mt-2"><b>{name}</b><Switch v={!!on[slug]} onClick={()=>toggle(slug)}/></div>))}</div>}
 {tab==='notif'&&<div className="card"><h1 className="font-black text-xl">নোটিফিকেশন সেটিংস</h1><p className="text-sm text-gray-500">কোন নোটিফিকেশন যাবে তা এখান থেকে নিয়ন্ত্রণ করুন — বদল সঙ্গে সঙ্গে সংরক্ষিত হয়।</p>{nm&&<p className="text-sm mt-2">{nm}</p>}{notifRows.map(([k,l,d])=>(<div key={k} className="flex justify-between gap-3 border rounded-2xl p-3 mt-2"><div><b>{l}</b><p className="text-xs text-gray-500">{d}</p></div><Switch v={!!s[k]} onClick={()=>flipNotif(k)}/></div>))}</div>}
 </div>}
