'use client'; import {useCallback,useEffect,useState} from 'react'; import {errMsg} from '@/lib/errMsg';
// IP-log browser (§44/§45): renders only when the server says this role holds analytics.ip.view;
// the API re-checks the permission anyway, so this UI is never the security boundary. Every log
// view/export is audit-logged server-side (ADMIN_VIEWED/EXPORTED_VISITOR_IP_LOG).
const TYPES:[string,string][]=[['','সব ধরন'],['ANONYMOUS','বেনামি ভিজিটর'],['USER','লগইন করা ইউজার'],['ADMIN','অ্যাডমিন']];
const typeLabel=(t:string)=>(TYPES.find(x=>x[0]===t)||['',t])[1];
const dk=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
const bnN=(n:any)=>String(n??'').replace(/\d/g,d=>'০১২৩৪৫৬৭৮৯'[+d]);
function rangeOf(p:string){ const t=new Date(); const today=dk(t); if(p==='TODAY') return {from:today,to:today}; if(p==='YESTERDAY'){ const y=dk(new Date(Date.now()-864e5)); return {from:y,to:y}; } if(p==='LAST7') return {from:dk(new Date(Date.now()-6*864e5)),to:today}; if(p==='LAST30') return {from:dk(new Date(Date.now()-29*864e5)),to:today}; if(p==='THIS_MONTH') return {from:today.slice(0,7)+'-01',to:today}; return {from:'',to:''}; }
export default function Client({canIp,canExport,retentionDays}:{canIp:boolean,canExport:boolean,retentionDays:number}){ const [q,setQ]=useState(''); const [type,setType]=useState(''); const [preset,setPreset]=useState('LAST30'); const [from,setFrom]=useState(rangeOf('LAST30').from); const [to,setTo]=useState(rangeOf('LAST30').to); const [page,setPage]=useState(1); const [data,setData]=useState<any>(null); const [err,setErr]=useState(''); const [busy,setBusy]=useState(false); const [ret,setRet]=useState(retentionDays); const [retMsg,setRetMsg]=useState('');
 const load=useCallback(async(p:number)=>{ setBusy(true); setErr(''); try{ const qs=new URLSearchParams({q,type,from,to,page:String(p),pageSize:'25'}); const r=await fetch('/api/admin/analytics/logs?'+qs.toString()); const j=await r.json(); if(!r.ok) throw new Error(j.error||'FORBIDDEN'); setData(j); }catch(e:any){ setErr(errMsg(e.message)); setData(null); } finally{ setBusy(false); } },[q,type,from,to]);
 useEffect(()=>{ if(canIp) load(1); },[canIp,type,from,to]); // eslint-disable-line react-hooks/exhaustive-deps
 const pickPreset=(p:string)=>{ setPreset(p); if(p!=='CUSTOM'){ const r=rangeOf(p); setFrom(r.from); setTo(r.to); } setPage(1); };
 const go=(p:number)=>{ const np=Math.min(Math.max(1,p),data?data.pages:1); setPage(np); load(np); };
 const qsExport=new URLSearchParams({q,type,from,to}).toString();
 const saveRet=async()=>{ setRetMsg(''); try{ const r=await fetch('/api/admin/analytics/settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({retentionDays:Number(ret)})}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'RETENTION_RANGE'); setRetMsg('সংরক্ষিত হয়েছে'+(j.purged?' • মেয়াদোত্তীর্ণ '+bnN(j.purged)+'টি IP লগ মুছে গেছে':'')); }catch(e:any){ setRetMsg(errMsg(e.message)); } };
 if(!canIp) return <div className="card mt-3"><b>ভিজিটর লগ (IPসহ)</b><p className="text-sm mt-2 text-amber-700 font-bold">🔒 IP লগ দেখার অনুমতি আপনার রোলে নেই।</p><p className="text-xs text-gray-500 mt-1">উপরের মোট পরিসংখ্যান সব অ্যাডমিন রোল দেখতে পারে; কাঁচা IP লগ শুধু <span className="font-mono">analytics.ip.view</span> অনুমতিপ্রাপ্তদের জন্য (অ্যাডমিন ও সুপার অ্যাডমিন)।</p></div>;
 return <div className="card mt-3"><div className="flex flex-wrap items-center justify-between gap-2"><b>ভিজিটর লগ (IPসহ — সংবেদনশীল)</b>{canExport&&<a className="chip bg-brand-50 text-brand-700 font-bold" href={'/api/admin/analytics/export?'+qsExport}>⬇ CSV এক্সপোর্ট</a>}</div>
 <p className="text-[11px] text-gray-400 mt-1">প্রতিটি IP লগ দেখা/এক্সপোর্ট অডিট লগে নথিভুক্ত হয়।</p>
 <div className="flex flex-wrap gap-2 mt-3"><input value={q} onChange={e=>setQ(e.target.value)} onBlur={()=>{setPage(1);load(1);}} onKeyDown={e=>{ if(e.key==='Enter'){ setPage(1); load(1); } }} placeholder="IP (হুবহু) বা ইউজার আইডি দিয়ে খুঁজুন" className="border rounded-xl px-3 py-2 text-sm flex-1 min-w-[180px]"/><select value={type} onChange={e=>{setType(e.target.value);setPage(1);}} className="border rounded-xl px-3 py-2 text-sm">{TYPES.map(([v,l])=>(<option key={v} value={v}>{l}</option>))}</select><select value={preset} onChange={e=>pickPreset(e.target.value)} className="border rounded-xl px-3 py-2 text-sm"><option value="TODAY">আজ</option><option value="YESTERDAY">গতকাল</option><option value="LAST7">গত ৭ দিন</option><option value="LAST30">গত ৩০ দিন</option><option value="THIS_MONTH">এই মাস</option><option value="CUSTOM">তারিখ বেছে নিন</option></select>{preset==='CUSTOM'&&<><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}} className="border rounded-xl px-3 py-2 text-sm"/><input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}} className="border rounded-xl px-3 py-2 text-sm"/></>}</div>
 {err&&<p className="text-sm text-red-600 mt-3">{err}</p>}
 {busy&&<p className="text-sm text-gray-500 mt-3">লোড হচ্ছে…</p>}
 {data&&(<><div className="overflow-x-auto mt-2"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="py-2 pe-2">তারিখ/সময়</th><th className="pe-2">IP ঠিকানা</th><th className="pe-2">ভিজিটর</th><th className="pe-2">ইউজার আইডি</th><th className="pe-2">ডিভাইস</th><th className="pe-2">ব্রাউজার</th><th className="pe-2">OS</th><th>দেশ</th></tr></thead><tbody>{data.logs.map((l:any)=>(<tr key={l.id} className="border-b"><td className="py-1.5 pe-2 whitespace-nowrap">{new Date(l.at).toLocaleString('bn-BD',{timeZone:'Asia/Dhaka'})}</td><td className="pe-2 font-mono text-[13px]">{l.ip||'অজানা'}</td><td className="pe-2">{typeLabel(l.type)}</td><td className="pe-2 font-mono text-xs">{l.userId||'—'}</td><td className="pe-2">{l.device}</td><td className="pe-2">{l.browser}</td><td className="pe-2">{l.os}</td><td>{l.country||'অজানা'}</td></tr>))}{!data.logs.length&&(<tr><td colSpan={8} className="py-4 text-center text-gray-500">এই ফিল্টারে কোনো লগ নেই</td></tr>)}</tbody></table></div>
 <div className="flex items-center justify-between mt-3 text-sm"><span>মোট {bnN(data.total)}টি লগ • পৃষ্ঠা {bnN(page)}/{bnN(data.pages)}</span><span className="flex gap-2"><button disabled={page<=1} onClick={()=>go(page-1)} className="chip bg-gray-100 disabled:opacity-40">‹ আগের</button><button disabled={page>=data.pages} onClick={()=>go(page+1)} className="chip bg-gray-100 disabled:opacity-40">পরের ›</button></span></div></>)}
 <div className="mt-4 border-t pt-3"><b className="text-sm">IP লগ সংরক্ষণের মেয়াদ</b><div className="flex flex-wrap items-center gap-2 mt-2"><input type="number" min={30} max={90} value={ret} onChange={e=>setRet(Number(e.target.value))} className="border rounded-xl px-3 py-2 text-sm w-24"/><span className="text-sm">দিন (৩০–৯০)</span><button onClick={saveRet} className="chip bg-emerald-600 text-white font-bold">সংরক্ষণ করুন</button>{retMsg&&<span className="text-sm text-emerald-700">{retMsg}</span>}</div><p className="text-[11px] text-gray-400 mt-1">মেয়াদ শেষে কাঁচা IP লগ মুছে যায়; মোট ভিজিটর হিসাব থেকে যায়।</p></div></div>; }
