import {readDBAsync} from '@/lib/db'; import {requireAdminPage} from '@/lib/auth'; import {hasPermission} from '@/lib/permissions'; import {bn} from '@/components/ui'; import {getAnalyticsSummary,getRetentionDays,purgeOldIpLogs} from '@/lib/analytics'; import Client from './Client'; export const dynamic='force-dynamic';
// Admin analytics (§42/§58): real unique-visitor counters only. Raw IP logs render solely for
// analytics.ip.view holders (Client fetches them from the permission-gated API — nothing IP-like
// is in this page payload). Loading this page also runs one bounded retention purge (§46).
const MONTHS=['জানুয়ারি','ফেব্রুয়ারি','মার্চ','এপ্রিল','মে','জুন','জুলাই','আগস্ট','সেপ্টেম্বর','অক্টোবর','নভেম্বর','ডিসেম্বর'];
export default async function P(){ const u=await requireAdminPage('analytics.view'); const retention=await getRetentionDays(); try{ await purgeOldIpLogs(retention); }catch{} const s=await getAnalyticsSummary(); const canIp=hasPermission(u.role,'analytics.ip.view'); const canExport=hasPermission(u.role,'analytics.ip.export'); const db=await readDBAsync(); const legacy:Array<any>=db.visits||[]; const legacyTotal=(db.visitStats&&db.visitStats.total)||0;
 const max30=Math.max(...s.last30.map(d=>d.count),1); const maxM=Math.max(...s.monthly.map(d=>d.count),1);
 const kpi=(v:any,l:string)=>(<div className="card"><p className="text-3xl font-black num">{bn(v)}</p><p className="text-sm font-bold">{l}</p></div>);
 return <div><h1 className="font-black text-xl">অ্যানালিটিক্স — ভিজিটর পরিসংখ্যান (রিয়েল হিসাব)</h1>
 <p className="text-xs text-gray-500 mt-1">অনন্য ভিজিটর পদ্ধতি চালুর পর থেকে হিসাব{s.since?<> • শুরু: {new Date(s.since).toLocaleDateString('bn-BD',{timeZone:'Asia/Dhaka'})}</>:null}</p>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-3">{kpi(s.today,'আজকের ভিজিটর')}{kpi(s.month,'এই মাসে')}{kpi(s.year,'এই বছর')}{kpi(s.total,'সর্বমোট ভিজিটর')}</div>
 <div className="card mt-3"><b>গত ৩০ দিনের ভিজিটর ট্রেন্ড</b><div className="flex items-end gap-[3px] h-36 mt-3">{s.last30.map((d,i)=>(<div key={d.day} className="flex-1 flex flex-col items-center justify-end h-full" title={`${d.day}: ${bn(d.count)}`}><span className="text-[9px] text-gray-500">{d.count?bn(d.count):''}</span><div style={{height:Math.max(2,d.count/max30*100)+'%'}} className={`w-full rounded-t ${i===s.last30.length-1?'bg-emerald-600':'bg-emerald-200'}`}/><span className="text-[9px] text-gray-400">{i%5===0||i===s.last30.length-1?bn(d.day.slice(8)):''}</span></div>))}</div></div>
 <div className="card mt-3"><b>মাসভিত্তিক ট্রেন্ড (গত ১২ মাস)</b><div className="flex items-end gap-2 h-32 mt-3">{s.monthly.map((m)=>(<div key={m.ym} className="flex-1 text-center"><p className="text-[10px] font-bold">{bn(m.count)}</p><div style={{height:Math.max(3,m.count/maxM*90)+'px'}} className="rounded-t-xl bg-brand-100 border border-brand-200 mx-0.5"/><p className="text-[10px] text-gray-500 mt-1">{MONTHS[Number(m.ym.slice(5))-1]} {bn(m.ym.slice(0,4))}</p></div>))}</div></div>
 <div className="card mt-3 text-sm"><b>ভিজিটর গণনা নীতি</b><ul className="list-disc ms-5 mt-2 space-y-1 text-gray-600 text-[13px]"><li>প্রতিদিনে (এশিয়া/ঢাকা) একজন ভিজিটর <b>একবারই</b> গণনা হয় — রিফ্রেশ, একাধিক ট্যাব বা অনেক পেজ ঘুরলেও বাড়ে না।</li><li>পরিচয়: লগইন থাকলে ইউজার আইডি, নাহলে ব্রাউজারের সার্ভার-ইস্যু করা কুকি; সংরক্ষিত কীটি একমুখী হ্যাশ — তা থেকে পরিচয় বা IP বের করা যায় না।</li><li>পরিচিত বট/ক্রলার/মনিটরিং ট্রাফিক গণনা হয় না। অ্যাডমিন প্যানেলের (/admin) ভিজিট কখনোই গণনায় আসে না।</li><li>কাঁচা IP শুধু নিরাপত্তা পর্যালোচনার জন্য সর্বোচ্চ {bn(retention)} দিন থাকে এবং শুধু <b>analytics.ip.view</b> অনুমতিপ্রাপ্তরা দেখতে পারেন; মোট হিসাব (aggregate) স্থায়ীভাবে থাকে।</li></ul></div>
 <Client canIp={canIp} canExport={canExport} retentionDays={retention}/>
 <div className="card mt-3"><b>প্ল্যাটফর্মের অন্যান্য রিয়েল হিসাব</b><p className="text-sm mt-1">মোট নিবন্ধিত ইউজার {bn(db.users.length)} জন • মোট পোস্ট {bn(db.posts.length)}টি • পেন্ডিং পোস্ট {bn(db.posts.filter((p:any)=>p.status==='PENDING').length)}টি</p></div>
 <div className="card mt-3"><b>পুরনো পেজভিউ-রেকর্ড (শুধু ইতিহাস)</b><p className="text-xs text-gray-500 mt-1">আগের পদ্ধতির মোট পেজভিউ ছিল {bn(legacyTotal)} — নতুন ভিজিট এখন থেকে উপরের অনন্য-ভিজিটর হিসাবেই যোগ হয়; এই তালিকাটি শুধু পড়ার জন্য রাখা হয়েছে (IP এখানে কখনো ছিল না)।</p>{legacy.slice(0,15).map((v:any)=>(<div key={v.id} className="text-sm py-1.5 border-b flex flex-wrap gap-x-3"><span className="text-gray-500">{new Date(v.ts).toLocaleString('bn-BD')}</span><b className="font-mono">{v.path}</b><span>{v.device} • {v.browser} • {v.os}</span><span>📍 {v.city||v.country?((v.city?v.city+', ':'')+(v.country||'')):'অজানা'}</span></div>))}</div></div>}
