import {readDBAsync} from '@/lib/db'; import {requireAdminPage} from '@/lib/auth'; import {bn} from '@/components/ui'; export const dynamic='force-dynamic';
const dayKey=(d:Date)=>d.toISOString().slice(0,10);
export default async function P(){ await requireAdminPage('analytics.view');const db=await readDBAsync(); const visits:Array<any>=db.visits||[]; const stats:any=db.visitStats&&typeof db.visitStats==='object'?db.visitStats:{total:0,byDay:{}}; const today=dayKey(new Date()); let last7=0; for(let i=0;i<7;i++){ last7+=stats.byDay[dayKey(new Date(Date.now()-i*86400000))]||0; }
 const devCount=(n:string)=>visits.filter(v=>v.device===n).length; const pct=(n:number)=>visits.length?Math.round(n/visits.length*100):0;
 const topPages=Object.entries(visits.reduce((a:any,v:any)=>{a[v.path]=(a[v.path]||0)+1;return a},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,10);
 const cats=db.posts.reduce((a:any,p:any)=>{a[p.categorySlug]=(a[p.categorySlug]||0)+1;return a},{}); const totalViews=db.posts.reduce((a:any,p:any)=>a+(p.views||0),0);
 const wd=['রবি','সোম','মঙ্গল','বুধ','বৃহস্পতি','শুক্র','শনি']; const byDay=wd.map((_,i)=>db.posts.filter((p:any)=>new Date(p.createdAt).getDay()===i).length); const max=Math.max(...byDay,1);
 const newToday=db.users.filter((u:any)=>u.createdAt&&dayKey(new Date(u.createdAt))===today).length; const new7=db.users.filter((u:any)=>u.createdAt&&Date.now()-new Date(u.createdAt).getTime()<7*86400000).length;
 return <div><h1 className="font-black text-xl">অ্যানালিটিক্স ও ভিজিটর হিস্ট্রি (রিয়েল হিসাব)</h1>
 <div className="grid md:grid-cols-4 gap-3 mt-3"><div className="card"><p className="text-3xl font-black">{bn(stats.total||0)}</p><p className="text-sm font-bold">সর্বমোট ভিজিট (ট্র্যাকিং চালুর পর থেকে)</p></div><div className="card"><p className="text-3xl font-black">{bn(stats.byDay[today]||0)}</p><p className="text-sm font-bold">আজকের ভিজিট</p></div><div className="card"><p className="text-3xl font-black">{bn(last7)}</p><p className="text-sm font-bold">গত ৭ দিনে ভিজিট</p></div><div className="card"><p className="text-3xl font-black">{bn(visits.length)}</p><p className="text-sm font-bold">সংরক্ষিত সাম্প্রতিক ভিজিট (সর্বোচ্চ ৩০০)</p></div></div>
 <div className="card mt-3"><b>ডিভাইস অনুযায়ী ভাগ (সাম্প্রতিক {bn(visits.length)}টি ভিজিটের মধ্যে)</b><div className="grid grid-cols-3 gap-2 mt-2 text-center text-sm"><div className="bg-gray-50 rounded-xl p-3">📱 মোবাইল<b className="block text-lg">{bn(devCount('মোবাইল'))} ({bn(pct(devCount('মোবাইল')))}%)</b></div><div className="bg-gray-50 rounded-xl p-3">💻 ডেস্কটপ<b className="block text-lg">{bn(devCount('ডেস্কটপ'))} ({bn(pct(devCount('ডেস্কটপ')))}%)</b></div><div className="bg-gray-50 rounded-xl p-3">📟 ট্যাবলেট<b className="block text-lg">{bn(devCount('ট্যাবলেট'))} ({bn(pct(devCount('ট্যাবলেট')))}%)</b></div></div></div>
 <div className="card mt-3"><b>সবচেয়ে বেশি দেখা পেজ (টপ {bn(topPages.length)})</b>{topPages.length?topPages.map(([p,c]:any)=>(<p key={p} className="text-sm py-1.5 border-b flex justify-between"><span className="font-mono">{p}</span><b>{bn(c)}বার</b></p>)):<p className="text-sm text-gray-500 mt-2">এখনো কোনো ভিজিট রেকর্ড হয়নি — সাইটে ভিজিট এলেই এখানে দেখা যাবে।</p>}</div>
 <div className="card mt-3"><b>সাম্প্রতিক {bn(Math.min(30,visits.length))}টি ভিজিট</b><p className="text-xs text-gray-500">লোকেশন শুধুমাত্র হোস্টিং প্ল্যাটফর্মের দেওয়া তথ্য থাকলেই দেখানো হয়; না থাকলে "অজানা"। কোনো IP সংরক্ষণ করা হয় না।</p>{visits.slice(0,30).map((v:any)=>(<div key={v.id} className="text-sm py-1.5 border-b flex flex-wrap gap-x-3"><span className="text-gray-500">{new Date(v.ts).toLocaleString('bn-BD')}</span><b className="font-mono">{v.path}</b><span>{v.device} • {v.browser} • {v.os}</span><span>📍 {v.city||v.country?((v.city?v.city+', ':'')+(v.country||'')):'অজানা'}</span></div>))}</div>
 <div className="card mt-3"><b>সর্বাধিক সক্রিয় ক্যাটাগরি — মোট পোস্ট ভিউ {bn(totalViews)} বার (সংরক্ষিত হিসাব)</b>{Object.entries(cats).map(([k,v]:any)=>(<p key={k} className="text-sm">{k}: {bn(v)} পোস্ট</p>))}</div>
 <div className="card mt-3"><b>সপ্তাহের দিন অনুযায়ী পোস্ট প্রকাশের রিয়েল গ্রাফ — মোট {bn(db.posts.length)}টি</b><div className="flex items-end gap-2 h-40 mt-3">{byDay.map((v,i)=>(<div key={i} className="flex-1 text-center"><div style={{height:(v/max*120+8)+'px'}} className={`rounded-t-xl ${v===max&&v>0?'bg-emerald-600':'bg-gray-200'}`}/><p className="text-xs">{bn(v)}<br/>{wd[i]}</p></div>))}</div></div>
 <div className="card mt-3"><b>ইউজার গ্রোথ (রিয়েল)</b><p>মোট নিবন্ধিত {bn(db.users.length)} জন • আজ নিবন্ধিত {bn(newToday)} জন • গত ৭ দিনে নতুন {bn(new7)} জন</p><b className="block mt-3">পোস্ট অনুমোদন লেটেন্সি (Moderation Response Latency)</b><p className="text-sm">গড় অনুমোদন সময় মিনিটে — moderation timestamps থেকে হিসাব করা হবে। পেন্ডিং: {bn(db.posts.filter((p:any)=>p.status==='PENDING').length)}টি</p></div></div>}
