import {NextResponse} from 'next/server'; import type {NextRequest} from 'next/server';
// Real 404 status for non-public detail URLs (A-CMS gate + post gate). The detail pages call
// notFound(), but the root app/loading.tsx Suspense boundary makes Next.js flush an HTTP 200
// shell before the page render throws — the streamed not-found UI can never change the status
// code afterwards (proven: removing root loading.tsx restored 404s). The gate therefore runs
// here, before streaming starts, for exactly /content/<type>/<slug>, /boalkhali/<slug>
// (the CMS-driven place details, type 'place') and /post/<id> (citizen posts: APPROVED is
// public, owner/staff preview keeps working via the forwarded session cookie); the listings,
// index, admin and every other route keep the friendly loading skeleton untouched.
const NF='<!doctype html><html lang="bn"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>পাওয়া যায়নি — বোয়ালখালী কানেক্ট</title><style>body{margin:0;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;background:#f6f8f7;color:#11352a;display:grid;place-items:center;min-height:100vh;padding:24px;box-sizing:border-box}.card{max-width:420px;text-align:center;background:#fff;border:1px solid #d8e6df;border-radius:20px;padding:32px 24px;box-shadow:0 8px 30px rgba(6,78,59,.08)}h1{margin:0 0 8px;font-size:22px}.p{color:#52665e;font-size:15px;line-height:1.6;margin:0 0 20px}a{display:inline-block;background:#0a7a54;color:#fff;text-decoration:none;font-weight:700;padding:10px 18px;border-radius:999px}</style></head><body><div class="card"><h1>দুঃখিত, পেজটি পাওয়া যায়নি</h1><p class="p">আপনি যে তথ্যটি খুঁজছেন তা হয়তো সরিয়ে ফেলা হয়েছে, অথবা এখনো প্রকাশিত হয়নি।</p><a href="/content">তথ্য ভাণ্ডারে ফিরুন</a></div></body></html>';
// Harmless 308 aliases (ROUTE_MAP §5.2, owner-approved vocabulary): the spec's URL
// names permanently redirect to the existing canonical URLs — old URLs are untouched
// and nothing is renamed. Aliases were checked against the app tree first: none of
// them shadows a real route (/businesses is deliberately absent — it is a real hub
// page now, and /events + /lost-found keep their own index pages; only their detail
// sub-paths alias). Checked BEFORE the CMS gate below.
const ALIAS_EXACT:any={'/places':'/boalkhali','/volunteer':'/volunteers','/marketplace':'/category/market','/collections':'/saved','/stories':'/content/local-news','/explore':'/categories','/dashboard':'/admin','/analytics':'/admin/analytics'};
function aliasTarget(parts:string[]):string|null{ const p='/'+parts.join('/'); if(ALIAS_EXACT[p]) return ALIAS_EXACT[p]; if(parts.length===2){ if(parts[0]==='places') return '/boalkhali/'+parts[1]; if(parts[0]==='marketplace') return '/post/'+parts[1]; if(parts[0]==='stories') return '/content/local-news/'+parts[1]; if(parts[0]==='events') return '/content/event/'+parts[1]; if(parts[0]==='lost-found') return '/post/'+parts[1]; } return null; }
export async function middleware(req:NextRequest){ const parts=req.nextUrl.pathname.split('/').filter(Boolean); const target=aliasTarget(parts); if(target){ const url=req.nextUrl.clone(); url.pathname=target; url.search=''; return NextResponse.redirect(url,308); } // Gated detail routes: /content/<type>/<slug>, /boalkhali/<slug> (type 'place'), /post/<id>.
 let gate:{type:string;slug:string;home:string;cta:string}|null=null; if(parts.length===3&&parts[0]==='content') gate={type:parts[1],slug:parts[2],home:'/content',cta:'তথ্য ভাণ্ডারে ফিরুন'}; else if(parts.length===2&&parts[0]==='boalkhali') gate={type:'place',slug:parts[1],home:'/boalkhali',cta:'সব দর্শনীয় স্থান দেখুন'}; else if(parts.length===2&&parts[0]==='post') gate={type:'post',slug:parts[1],home:'/',cta:'হোমে ফিরুন'}; if(!gate) return NextResponse.next(); let visible:boolean|null=null; try{ const probe=gate.type==='post'?'/api/post-status?id='+encodeURIComponent(gate.slug):'/api/content-status?type='+encodeURIComponent(gate.type)+'&slug='+encodeURIComponent(gate.slug); const r=await fetch(req.nextUrl.origin+probe,{cache:'no-store',headers:{cookie:req.headers.get('cookie')||''}}); if(r.ok){ const j=await r.json(); visible=!!j.visible; } }catch{} if(visible===null||visible) return NextResponse.next(); const html=NF.replace('<a href="/content">তথ্য ভাণ্ডারে ফিরুন</a>','<a href="'+gate.home+'">'+gate.cta+'</a>'); return new NextResponse(html,{status:404,headers:{'content-type':'text/html; charset=utf-8','x-robots-tag':'noindex'}}); }
// NOTE: the matcher is intentionally broad — Next 14.2 mis-compiled '/content/:type/:slug'
// to a single-segment pattern in the middleware manifest, so the exact two-segment scope is
// enforced by the parts guard inside (anything else passes straight through).
export const config={matcher:['/content/:path*','/boalkhali/:path*','/post/:path*','/places','/places/:path*','/volunteer','/marketplace','/marketplace/:path*','/collections','/stories','/stories/:path*','/events/:path*','/lost-found/:path*','/explore','/dashboard','/analytics']};
