import Link from 'next/link'; import {readDBAsync} from '@/lib/db'; import {requireAdminPage} from '@/lib/auth'; import {hasPermission} from '@/lib/permissions'; import ApprovalsClient from './ApprovalsClient'; export const dynamic='force-dynamic';
// অনুমোদন কেন্দ্র: only genuinely-pending queues from the data model — PENDING posts
// (quick approve/reject via the existing /api/admin/moderate), NEW complaints and
// NEW secret reports (counts + link to their desks; secret section is only rendered
// for roles holding secret.view, so a moderator never sees secret report data here).
const fmt=(s:any)=>s?new Date(s).toLocaleString('bn-BD'):'—';
export default async function P(){ const u=await requireAdminPage('approvals.view'); const db=await readDBAsync(); const nameOf=(uid:string)=>db.users.find((x:any)=>x.id===uid)?.name||'অজ্ঞাত'; const catOf=(slug:string)=>db.categories.find((c:any)=>c.slug===slug)?.name||slug;
 const posts=db.posts.filter((p:any)=>p.status==='PENDING').sort((a:any,b:any)=>String(b.createdAt).localeCompare(String(a.createdAt)));
 const complaints=db.complaints.filter((c:any)=>c.status==='NEW').sort((a:any,b:any)=>String(b.createdAt).localeCompare(String(a.createdAt)));
 const canSecret=hasPermission(u.role,'secret.view'); const secrets=canSecret?db.secret_reports.filter((s:any)=>s.status==='NEW').sort((a:any,b:any)=>String(b.createdAt).localeCompare(String(a.createdAt))):[];
 const postRows=posts.map((p:any)=>({id:p.id,title:p.title,categorySlug:catOf(p.categorySlug),location:p.location||'',price:p.price||0,image:p.image||'',author:nameOf(p.userId),createdAt:p.createdAt}));
 return <div><h1 className="font-black text-xl">✅ অনুমোদন কেন্দ্র</h1><p className="text-sm text-gray-500">অপেক্ষমাণ কাজের সারি — পোস্ট এখান থেকেই অনুমোদন/বাতিল করা যায়; অভিযোগ ও গোপন রিপোর্ট তাদের ডেস্কে গিয়ে দেখুন।</p>
 <div className="grid grid-cols-3 gap-3 mt-4"><div className="card text-center"><p className="text-3xl font-black">{posts.length}</p><p className="text-xs text-gray-500">অপেক্ষমাণ পোস্ট</p></div><div className="card text-center"><p className="text-3xl font-black">{complaints.length}</p><p className="text-xs text-gray-500">নতুন অভিযোগ</p></div>{canSecret&&<div className="card text-center"><p className="text-3xl font-black">{secrets.length}</p><p className="text-xs text-gray-500">নতুন গোপন রিপোর্ট</p></div>}</div>
 <h2 className="font-black mt-6 mb-2">📝 অপেক্ষমাণ পোস্ট ({posts.length}টি)</h2><ApprovalsClient posts={postRows}/>
 <h2 className="font-black mt-6 mb-2">🚩 নতুন অভিযোগ ({complaints.length}টি)</h2>{complaints.length?<div className="space-y-2">{complaints.slice(0,10).map((c:any)=>(<div key={c.id} className="card"><b>{c.type||'অভিযোগ'}</b> <span className="text-xs text-gray-500">{c.location||''} • {nameOf(c.userId)} • {fmt(c.createdAt)}</span><p className="text-sm mt-1">{c.desc}</p></div>))}</div>:<p className="text-sm text-gray-500">কোনো নতুন অভিযোগ নেই 🎉</p>}<Link href="/admin/complaints" className="btn mt-3">অভিযোগ ডেস্কে যান</Link>
 {canSecret&&<><h2 className="font-black mt-6 mb-2">🔒 নতুন গোপন রিপোর্ট ({secrets.length}টি)</h2>{secrets.length?<div className="space-y-2">{secrets.slice(0,10).map((s:any)=>(<div key={s.id} className="card flex items-center gap-2"><span className={`chip ${s.priority==='HIGH'?'bg-red-100 text-red-700':'bg-emerald-100'}`}>{s.priority||'সাধারণ'}</span><b className="truncate">{s.title||'শিরোনামহীন রিপোর্ট'}</b><span className="text-xs text-gray-500 ml-auto shrink-0">{fmt(s.createdAt)}</span></div>))}</div>:<p className="text-sm text-gray-500">কোনো নতুন গোপন রিপোর্ট নেই 🎉</p>}<Link href="/admin/secret" className="btn mt-3">গোপন ডেস্কে যান</Link></>}
 </div>; }
