export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,mutateDBAsync,sanitize,sanitizeBusinessVerification,id,now,audit} from '@/lib/db'; import {requireRole} from '@/lib/auth'; import {hasPermission} from '@/lib/permissions';
// Business verification — admin review queue (Wave 3). Gated by the 'business.verify'
// permission (ADMIN + SUPER_ADMIN via the RBAC matrix; MODERATOR does not have it).
// Approving is the ONLY code path that ever writes `verified` on a content record.
async function guard(){ const r:any=await requireRole(['ADMIN','SUPER_ADMIN','MODERATOR']); if(r.error) return r; if(!hasPermission(r.user.role,'business.verify')) return {error:'FORBIDDEN',status:403}; return r; }
const fail=(r:any)=>NextResponse.json({error:r.error||'FORBIDDEN'},{status:r.status||403});
export async function GET(){ const r=await guard(); if(r.error) return fail(r); const db=await readDBAsync(); const users:any={}; db.users.forEach((u:any)=>{ users[u.id]=u; }); const byId:any={}; (db.contents||[]).forEach((c:any)=>{ byId[c.id]=c; }); const items=(db.business_verifications||[]).map(sanitizeBusinessVerification).filter(Boolean).map((v:any)=>({ ...v,ownerName:(users[v.userId]||{}).name||'',ownerEmail:(users[v.userId]||{}).email||'',contentSlug:byId[v.contentId]?byId[v.contentId].slug:'',contentStatus:byId[v.contentId]?byId[v.contentId].status:'' })).sort((a:any,b:any)=>(a.status==='PENDING'?0:1)-(b.status==='PENDING'?0:1)||String(b.createdAt).localeCompare(String(a.createdAt))); return NextResponse.json({items}); }
export async function POST(req:Request){ const r=await guard(); if(r.error) return fail(r); const b=await req.json().catch(()=>({})); const action=String(b.action||''); if(!['approve','reject'].includes(action)) return NextResponse.json({error:'INVALID_ACTION'},{status:400}); const reqId=String(b.id||''); if(!reqId) return NextResponse.json({error:'ID_REQUIRED'},{status:400});
 const out:any=await mutateDBAsync((db:any)=>{ const rec=(db.business_verifications||[]).find((x:any)=>x.id===reqId); if(!rec) return {e:404,error:'REQUEST_NOT_FOUND'}; if(rec.status!=='PENDING') return {e:409,error:'ALREADY_DECIDED',message:'এই আবেদনটি আগেই সিদ্ধান্তিত হয়েছে'}; rec.status=action==='approve'?'APPROVED':'REJECTED'; rec.reviewerId=r.user.id; rec.reviewNote=sanitize(b.note).slice(0,500); rec.reviewedAt=now(); let contentMissing=false; if(action==='approve'){ const c=(db.contents||[]).find((x:any)=>x.id===rec.contentId); if(c){ c.verified=true; c.verifiedAt=now(); } else contentMissing=true; } audit(db,r.user.email,action==='approve'?'BUSINESS_VERIFY_APPROVE':'BUSINESS_VERIFY_REJECT',rec.contentId,{request:rec.id}); db.notifications.unshift({id:id('n'),userId:rec.userId,type:action==='approve'?'BUSINESS_VERIFIED':'BUSINESS_VERIFY_REJECTED',contentId:rec.contentId,title:action==='approve'?'✅ আপনার ব্যবসা যাচাইকৃত হয়েছে':'ব্যবসা যাচাইয়ের আবেদন গৃহীত হয়নি',body:rec.businessName+(rec.reviewNote?(' — মন্তব্য: '+rec.reviewNote):''),read:false,createdAt:now()}); return {ok:true,request:sanitizeBusinessVerification(rec),contentMissing}; });
 if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
