export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,writeDBAsync,mutateDBAsync,audit,id,sanitize} from '@/lib/db'; import {requireRole} from '@/lib/auth'; import {slugify} from '@/lib/cms';
// Category management (categories.manage = ADMIN/SUPER_ADMIN): list with post+content
// counts, create, edit (name/icon/color/order/subcategories), enable toggle (legacy POST
// {slug,enabled}), and delete — delete is blocked while posts or CMS contents reference the
// category, so nothing is ever orphaned.
const fail=(r:any)=>NextResponse.json({error:r.error||'FORBIDDEN'},{status:r.status||403});
const subs=(v:any)=>Array.isArray(v)?v.map((s:any)=>typeof s==='string'?{slug:slugify(s),name:s}:{slug:slugify(s&&(s.slug||s.name)),name:sanitize(s&&s.name)}).filter((s:any)=>s.slug&&s.name).slice(0,50):[];
export async function GET(){ const r:any=await requireRole(['ADMIN','SUPER_ADMIN','MODERATOR']); if(r.error) return fail(r); const db=await readDBAsync(); const posts:any={},contents:any={}; db.posts.forEach((p:any)=>{ posts[p.categorySlug]=(posts[p.categorySlug]||0)+1; }); (db.contents||[]).forEach((c:any)=>{ if(c.categorySlug&&c.status!=='TRASHED') contents[c.categorySlug]=(contents[c.categorySlug]||0)+1; }); return NextResponse.json({categories:[...db.categories].sort((a:any,b:any)=>(a.order||0)-(b.order||0)).map((c:any)=>({...c,posts:posts[c.slug]||0,contents:contents[c.slug]||0}))}); }
export async function POST(req:Request){ const r:any=await requireRole(['ADMIN','SUPER_ADMIN']); if(r.error) return fail(r); const b=await req.json().catch(()=>({})); if(b&&'enabled' in b&&!b.name){ const db=await readDBAsync(); const c=db.categories.find((x:any)=>x.slug===String(b.slug||'')); if(!c) return NextResponse.json({error:'NOT_FOUND'},{status:404}); c.enabled=!!b.enabled; audit(db,r.user.email,'CATEGORY_TOGGLE',c.slug,{enabled:c.enabled}); await writeDBAsync(db); return NextResponse.json({ok:true,slug:c.slug,enabled:c.enabled}); } const out:any=await mutateDBAsync((db:any)=>{ const name=sanitize(b.name); if(!name) return {e:400,error:'NAME_REQUIRED'}; const slug=slugify(b.slug||name); if(db.categories.some((c:any)=>c.slug===slug)) return {e:400,error:'SLUG_TAKEN',message:'এই slug-এ আগেই ক্যাটাগরি আছে'}; const c={id:id('cat'),slug,name,icon:sanitize(b.icon||'📌'),color:sanitize(b.color||'#0a7a54'),desc:sanitize(b.desc||''),order:Number.isFinite(+b.order)?+b.order:db.categories.length+1,enabled:b.enabled!==false,subcategories:subs(b.subcategories)}; db.categories.push(c); audit(db,r.user.email,'CATEGORY_CREATE',c.slug,{name}); return {ok:true,category:c}; }); if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
export async function PATCH(req:Request){ const r:any=await requireRole(['ADMIN','SUPER_ADMIN']); if(r.error) return fail(r); const b=await req.json().catch(()=>({})); const out:any=await mutateDBAsync((db:any)=>{ const c=db.categories.find((x:any)=>x.slug===String(b.slug||'')); if(!c) return {e:404,error:'NOT_FOUND'}; if(b.name!==undefined){ const name=sanitize(b.name); if(!name) return {e:400,error:'NAME_REQUIRED'}; c.name=name; } if(b.icon!==undefined) c.icon=sanitize(b.icon||'📌'); if(b.color!==undefined) c.color=sanitize(b.color||'#0a7a54'); if(b.desc!==undefined) c.desc=sanitize(b.desc); if(b.order!==undefined&&Number.isFinite(+b.order)) c.order=+b.order; if(b.enabled!==undefined) c.enabled=!!b.enabled; if(b.subcategories!==undefined) c.subcategories=subs(b.subcategories); audit(db,r.user.email,'CATEGORY_UPDATE',c.slug,{}); return {ok:true,category:c}; }); if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
export async function DELETE(req:Request){ const r:any=await requireRole(['ADMIN','SUPER_ADMIN']); if(r.error) return fail(r); const slug=new URL(req.url).searchParams.get('slug')||''; const out:any=await mutateDBAsync((db:any)=>{ const c=db.categories.find((x:any)=>x.slug===slug); if(!c) return {e:404,error:'NOT_FOUND'}; const inPost=db.posts.some((p:any)=>p.categorySlug===slug); const inContent=(db.contents||[]).some((x:any)=>x.categorySlug===slug&&x.status!=='TRASHED'); if(inPost||inContent) return {e:409,error:'CATEGORY_IN_USE',message:'এই ক্যাটাগরিতে পোস্ট/কনটেন্ট আছে — মোছা যাবে না; চাইলে নিষ্ক্রিয় করুন'}; db.categories=db.categories.filter((x:any)=>x.slug!==slug); audit(db,r.user.email,'CATEGORY_DELETE',slug,{name:c.name}); return {ok:true,deleted:slug}; }); if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
