export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,mutateDBAsync,audit,now} from '@/lib/db'; import {requireRole} from '@/lib/auth'; import {hasPermission} from '@/lib/permissions'; import {sanitizeContent,sanitizeContentType,validateContentBody} from '@/lib/cms';
// Single content: read / edit (type is immutable after creation; status changes go through
// the action endpoint) / permanent delete (Trash only, content.delete).
async function guard(perm:string){ const r:any=await requireRole(['ADMIN','SUPER_ADMIN','MODERATOR']); if(r.error) return r; if(!hasPermission(r.user.role,perm)) return {error:'FORBIDDEN',status:403}; return r; }
const fail=(r:any)=>NextResponse.json({error:r.error||'FORBIDDEN'},{status:r.status||403});
export async function GET(_req:Request,{params}:{params:{id:string}}){ const r=await guard('content.view'); if(r.error) return fail(r); const db=await readDBAsync(); const c=(db.contents||[]).find((x:any)=>x.id===params.id); if(!c) return NextResponse.json({error:'CONTENT_NOT_FOUND'},{status:404}); const type=sanitizeContentType((db.content_types||[]).find((t:any)=>t.slug===c.typeSlug)); return NextResponse.json({content:sanitizeContent(c),type}); }
export async function PATCH(req:Request,{params}:{params:{id:string}}){ const r=await guard('content.edit'); if(r.error) return fail(r); const b=await req.json().catch(()=>({})); const out:any=await mutateDBAsync((db:any)=>{ const c=(db.contents||[]).find((x:any)=>x.id===params.id); if(!c) return {e:404,error:'CONTENT_NOT_FOUND'}; const type=sanitizeContentType((db.content_types||[]).find((t:any)=>t.slug===c.typeSlug)); if(!type) return {e:400,error:'TYPE_NOT_FOUND'}; if(!String(b.slug||'').trim()) b.slug=c.slug; const v:any=validateContentBody(type,b,db,c.id); if(v.error) return {e:400,...v}; Object.assign(c,v.data,{updatedBy:r.user.id,updatedAt:now()}); audit(db,r.user.email,'CONTENT_UPDATE',c.id,{type:c.typeSlug}); return {ok:true,content:sanitizeContent(c)}; }); if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
export async function DELETE(_req:Request,{params}:{params:{id:string}}){ const r=await guard('content.delete'); if(r.error) return fail(r); const out:any=await mutateDBAsync((db:any)=>{ const c=(db.contents||[]).find((x:any)=>x.id===params.id); if(!c) return {e:404,error:'CONTENT_NOT_FOUND'}; if(c.status!=='TRASHED') return {e:400,error:'PERMANENT_DELETE_TRASH_ONLY',message:'স্থায়ীভাবে মুছতে হলে আগে ট্র্যাশে পাঠান'}; db.contents=db.contents.filter((x:any)=>x.id!==params.id); audit(db,r.user.email,'CONTENT_DELETE',params.id,{type:c.typeSlug,slug:c.slug}); return {ok:true,deleted:params.id}; }); if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
