export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,mutateDBAsync,audit,sanitize,id} from '@/lib/db'; import {requireRole} from '@/lib/auth';
// Locations admin (categories.manage): CRUD over db.locations. Delete is blocked while the
// place name is referenced by CMS contents or citizen posts.
async function guard(){ const r:any=await requireRole(['ADMIN','SUPER_ADMIN']); if(r.error) return r; return r; }
const fail=(r:any)=>NextResponse.json({error:r.error||'FORBIDDEN'},{status:r.status||403});
const clean=(b:any)=>({name:sanitize(b.name),area:sanitize(b.area||b.name),road:sanitize(b.road||''),landmark:sanitize(b.landmark||''),lat:(b.lat===''||b.lat===null||b.lat===undefined)?null:Number(b.lat),lng:(b.lng===''||b.lng===null||b.lng===undefined)?null:Number(b.lng)});
export async function GET(){ const r=await guard(); if(r.error) return fail(r); const db=await readDBAsync(); return NextResponse.json({locations:db.locations}); }
export async function POST(req:Request){ const r=await guard(); if(r.error) return fail(r); const b=await req.json().catch(()=>({})); const out:any=await mutateDBAsync((db:any)=>{ const e=clean(b); if(!e.name) return {e:400,error:'NAME_REQUIRED'}; if(db.locations.some((l:any)=>l.name===e.name)) return {e:400,error:'EXISTS',message:'এই নামের এলাকা আগেই আছে'}; const loc={id:id('loc'),...e}; db.locations.push(loc); audit(db,r.user.email,'LOCATION_CREATE',loc.id,{name:e.name}); return {ok:true,location:loc}; }); if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
export async function PATCH(req:Request){ const r=await guard(); if(r.error) return fail(r); const b=await req.json().catch(()=>({})); const out:any=await mutateDBAsync((db:any)=>{ const loc=db.locations.find((l:any)=>l.id===String(b.id||'')); if(!loc) return {e:404,error:'NOT_FOUND'}; const e=clean({...loc,...b}); if(!e.name) return {e:400,error:'NAME_REQUIRED'}; if(db.locations.some((l:any)=>l.name===e.name&&l.id!==loc.id)) return {e:400,error:'EXISTS',message:'এই নামের এলাকা আগেই আছে'}; Object.assign(loc,e); audit(db,r.user.email,'LOCATION_UPDATE',loc.id,{name:e.name}); return {ok:true,location:loc}; }); if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
export async function DELETE(req:Request){ const r=await guard(); if(r.error) return fail(r); const locId=new URL(req.url).searchParams.get('id')||''; const out:any=await mutateDBAsync((db:any)=>{ const loc=db.locations.find((l:any)=>l.id===locId); if(!loc) return {e:404,error:'NOT_FOUND'}; const inContent=(db.contents||[]).some((c:any)=>{ const l=c.location||{}; return [l.area,l.union,l.upazila,l.district].includes(loc.name); }); const inPost=(db.posts||[]).some((p:any)=>String(p.location||'').includes(loc.name)); if(inContent||inPost) return {e:409,error:'LOCATION_IN_USE',message:'এই এলাকার নাম কনটেন্ট/পোস্টে ব্যবহৃত হচ্ছে'}; db.locations=db.locations.filter((l:any)=>l.id!==locId); audit(db,r.user.email,'LOCATION_DELETE',locId,{name:loc.name}); return {ok:true,deleted:locId}; }); if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
