export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,mutateDBAsync,audit,sanitize,id} from '@/lib/db'; import {requireRole} from '@/lib/auth'; import {hasPermission} from '@/lib/permissions';
// Doctor/facility directory admin (business.manage = ADMIN/SUPER_ADMIN). POST accepts one entry
// {name,specialty,chamber,address,hours,fee,phone,verified,emergency} or bulk {entries:[...]}.
// Duplicates (same name) are skipped so re-running an import is safe. DELETE ?id=<id> removes a
// single entry (admins.delete perm, audit-logged) — e.g. scrubbing a leftover demo entry.
function clean(b:any){ const fee=Number(b.fee); return {name:sanitize(b.name),specialty:sanitize(b.specialty||''),chamber:sanitize(b.chamber||''),address:sanitize(b.address||''),hours:sanitize(b.hours||''),fee:Number.isFinite(fee)&&fee>0?fee:undefined,phone:sanitize(b.phone||''),verified:!!b.verified,emergency:!!b.emergency}; }
export async function GET(){ const r=await requireRole(['ADMIN','SUPER_ADMIN']); if((r as any).error) return NextResponse.json(r,{status:(r as any).status}); const db=await readDBAsync(); return NextResponse.json({doctors:db.doctors,count:db.doctors.length}); }
export async function POST(req:Request){ const r=await requireRole(['ADMIN','SUPER_ADMIN']); if((r as any).error) return NextResponse.json(r,{status:(r as any).status}); const b=await req.json().catch(()=>({})); const list=Array.isArray(b.entries)?b.entries:(b.name?[b]:[]); if(!list.length) return NextResponse.json({error:'NO_ENTRIES'},{status:400}); const out:any=await mutateDBAsync((db:any)=>{ let added=0,skipped=0; for(const raw of list){ const e=clean(raw); if(!e.name){ skipped++; continue; } if(db.doctors.some((d:any)=>d.name===e.name)){ skipped++; continue; } db.doctors.push({id:id('d'),...e}); added++; } if(added) audit(db,(r as any).user.email,'DOCTORS_IMPORT','doctors',{added,skipped}); return {added,skipped,total:db.doctors.length}; }); return NextResponse.json({ok:true,...out}); }
export async function DELETE(req:Request){ const r=await requireRole(['ADMIN','SUPER_ADMIN']); if((r as any).error) return NextResponse.json(r,{status:(r as any).status}); if(!hasPermission((r as any).user.role,'admins.delete')) return NextResponse.json({error:'FORBIDDEN'},{status:403}); const docId=new URL(req.url).searchParams.get('id')||''; if(!docId) return NextResponse.json({error:'ID_REQUIRED'},{status:400}); const out:any=await mutateDBAsync((db:any)=>{ const d=db.doctors.find((x:any)=>x.id===docId); if(!d) return {e:404,error:'DOCTOR_NOT_FOUND'}; db.doctors=db.doctors.filter((x:any)=>x.id!==docId); audit(db,(r as any).user.email,'DOCTOR_DELETE',docId,{name:d.name}); return {ok:true,deleted:docId,name:d.name,total:db.doctors.length}; }); if(out.e) return NextResponse.json({error:out.error},{status:out.e}); return NextResponse.json(out); }
