export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,writeDBAsync,sanitize,now,audit} from '@/lib/db'; import {currentUser,rateLimit} from '@/lib/auth';
export async function GET(){ const user=await currentUser(); if(!user) return NextResponse.json({error:'LOGIN_REQUIRED'},{status:401}); const db=await readDBAsync(); const posts=db.posts.filter((p:any)=>p.userId===user.id).sort((a:any,b:any)=>String(b.createdAt).localeCompare(String(a.createdAt))); return NextResponse.json({posts}) }
export async function PATCH(req:Request){ if(!rateLimit('mypost',30)) return NextResponse.json({error:'RATE_LIMIT'},{status:429}); const user=await currentUser(); if(!user) return NextResponse.json({error:'LOGIN_REQUIRED'},{status:401}); const b=await req.json(); const db=await readDBAsync(); const p=db.posts.find((x:any)=>x.id===b.id); if(!p) return NextResponse.json({error:'NOT_FOUND'},{status:404}); if(p.userId!==user.id) return NextResponse.json({error:'FORBIDDEN'},{status:403});
 const title=b.title!==undefined?sanitize(b.title):p.title; const desc=b.desc!==undefined?sanitize(b.desc):p.desc; if(!title) return NextResponse.json({error:'TITLE_REQUIRED'},{status:400}); if(!desc) return NextResponse.json({error:'DESC_REQUIRED'},{status:400}); const price=b.price!==undefined?Number(b.price):p.price; if(price===undefined||isNaN(Number(price))||Number(price)<0) return NextResponse.json({error:'INVALID_PRICE'},{status:400});
 p.title=title; p.desc=desc; p.price=Number(price); if(b.location!==undefined)p.location=sanitize(b.location); if(b.phone!==undefined)p.phone=sanitize(b.phone); if(b.whatsapp!==undefined)p.whatsapp=sanitize(b.whatsapp); if(b.image!==undefined)p.image=String(b.image||'').slice(0,1000); if(b.hidePhone!==undefined)p.hidePhone=!!b.hidePhone; p.updatedAt=now();
 const remoderation=p.status==='APPROVED'||p.status==='REJECTED'; if(remoderation){ p.status='PENDING'; delete p.rejectReason; delete p.approvedAt; }
 audit(db,user.email,'EDIT_POST',p.id); await writeDBAsync(db); return NextResponse.json({ok:true,post:p,remoderation,note:remoderation?'পোস্টটি আবার মডারেশনের জন্য পাঠানো হয়েছে':undefined}) }
export async function POST(req:Request){ const user=await currentUser(); if(!user) return NextResponse.json({error:'LOGIN_REQUIRED'},{status:401}); const b=await req.json(); const db=await readDBAsync(); const p=db.posts.find((x:any)=>x.id===b.id); if(!p) return NextResponse.json({error:'NOT_FOUND'},{status:404}); if(p.userId!==user.id) return NextResponse.json({error:'FORBIDDEN'},{status:403});
 if(b.action==='sold'){ p.sold=true; p.soldAt=now(); }
 else if(b.action==='active'){ p.sold=false; delete p.soldAt; }
 else if(b.action==='delete'){ db.posts=db.posts.filter((x:any)=>x.id!==b.id); db.post_comments=db.post_comments.filter((c:any)=>c.postId!==b.id); audit(db,user.email,'DELETE_POST',b.id); await writeDBAsync(db); return NextResponse.json({ok:true,deleted:true}); }
 else return NextResponse.json({error:'INVALID_ACTION'},{status:400});
 audit(db,user.email,'POST_'+String(b.action).toUpperCase(),p.id); await writeDBAsync(db); return NextResponse.json({ok:true,post:p}) }
