import {Shell} from '@/components/ui'; import {Info,HeartHandshake,Sparkles} from 'lucide-react'; export const dynamic='force-dynamic';
export default function P(){ return <Shell><main className="max-w-3xl mx-auto p-4">
 <h1 className="font-black text-xl flex items-center gap-2"><Info className="text-emerald-700"/>অ্যাপ নির্মাতা ও পরিচিতি</h1>
 <div className="card mt-3 text-center"><div className="w-20 h-20 mx-auto bg-emerald-700 rounded-full grid place-items-center text-white text-3xl font-black">বো</div><h2 className="font-black text-lg mt-3">বোয়ালখালী কানেক্ট</h2><p className="text-sm text-emerald-700">বোয়ালখালী, চট্টগ্রামের ডিজিটাল সিটিজেন সার্ভিস প্ল্যাটফর্ম</p></div>
 <div className="card mt-3"><h2 className="font-black">নির্মাতা ও পরিচালক</h2><p className="mt-1"><b>MD. Habibur Rahman</b></p><p className="text-sm text-gray-600">বোয়ালখালী কানেক্টের প্রতিষ্ঠাতা ও মালিক। এলাকার মানুষের দৈনন্দিন সেবা এক ছাতার নিচে আনার উদ্দেশ্যেই এই প্ল্যাটফর্মের যাত্রা শুরু।</p></div>
 <div className="card mt-3"><h2 className="font-black flex items-center gap-2"><Sparkles size={18} className="text-emerald-700"/>এই অ্যাপে যা যা আছে</h2><ul className="text-sm text-gray-700 mt-2 space-y-1.5 list-disc list-inside"><li>বাসা ভাড়া, বাই-সেলসহ ১৯টি ক্যাটাগরির পোস্ট</li><li>জরুরি রক্তের অনুরোধ ও রক্তদাতা খোঁজা</li><li>ডাক্তার, চাকরি, রেস্টুরেন্ট ও বাস/ট্রেনের সময়সূচী</li><li>জরুরি সিটি ডিরেক্টরি — পুলিশ, ফায়ার সার্ভিস, অ্যাম্বুলেন্স</li><li>পরিচয় গোপন রেখে নিরাপদে তথ্য দেওয়ার ব্যবস্থা</li><li>স্বেচ্ছাসেবীদের মাধ্যমে কমিউনিটি সহায়তা</li></ul></div>
 <div className="card mt-3"><h2 className="font-black flex items-center gap-2"><HeartHandshake size={18} className="text-emerald-700"/>আমাদের অঙ্গীকার</h2><p className="text-sm text-gray-700 mt-1">প্রতিটি পোস্ট যাচাই-বাছাই (মডারেশন) করে প্রকাশ করা হয়, যাতে বোয়ালখালীর মানুষ নিরাপদে ও স্বচ্ছন্দে সেবা নিতে পারেন। আপনার মতামত ও সহযোগিতাই এই প্ল্যাটফর্মকে এগিয়ে নেবে।</p><p className="text-center font-bold text-emerald-700 mt-3">সাথে থাকার জন্য ধন্যবাদ 💚</p></div>
 <p className="text-center text-xs text-gray-400 mt-4">ক্যাটাগরি আইকন: Google Noto Emoji</p>
 </main></Shell> }
