'use client'; import {Shell,PostCard} from '@/components/ui'; import {catIcon,catEmoji} from '@/lib/catIcons'; import {useState} from 'react'; import Link from 'next/link'; import {errMsg} from '@/lib/errMsg';
export default function Client({cats,locs}:{cats:any[];locs:string[]}){
 const [step,setStep]=useState(1); const [cat,setCat]=useState(''); const [title,setTitle]=useState(''); const [sub,setSub]=useState('ফ্যামিলি বাসা'); const [rooms,setRooms]=useState(''); const [price,setPrice]=useState(''); const [desc,setDesc]=useState(''); const [loc,setLoc]=useState(locs[0]||''); const [landmark,setLandmark]=useState(''); const [phone,setPhone]=useState(''); const [wa,setWa]=useState(''); const [hidePhone,setHidePhone]=useState(false); const [exp,setExp]=useState(''); const [img,setImg]=useState(''); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false); const [upBusy,setUpBusy]=useState(false); const [sent,setSent]=useState(false);
 const cObj=cats.find((c:any)=>c.slug===cat);
 const toStep2=()=>{if(!cat){setMsg('আগে ক্যাটাগরি বেছে নিন'); return} setMsg(''); setStep(2)};
 const toStep3=()=>{if(!title.trim()||!desc.trim()||!phone.trim()){setMsg('শিরোনাম, বিস্তারিত বিবরণ ও মোবাইল নম্বর আবশ্যক'); return} setMsg(''); setStep(3)};
 const submit=async()=>{setBusy(true); setMsg(''); try{ const body={categorySlug:cat,title,subcategory:sub,rooms,price,desc,location:loc,landmark,phone,whatsapp:wa,image:img,hidePhone,expiresAt:exp}; const r=await fetch('/api/posts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const j=await r.json(); if(r.ok){setSent(true)} else setMsg('❌ '+errMsg(j.error)) }catch{ setMsg('❌ '+errMsg(null)) } setBusy(false)};
 const upload=async(file?:File)=>{if(!file)return; setUpBusy(true); const fd=new FormData(); fd.append('file',file); try{ const r=await fetch('/api/upload',{method:'POST',body:fd}); const j=await r.json(); if(j.url){setImg(j.url); setMsg('ছবি আপলোড হয়েছে')} else setMsg('আপলোড ব্যর্থ: '+errMsg(j.error)) }catch{ setMsg('আপলোড ব্যর্থ: '+errMsg(null)) } setUpBusy(false)};
 const steps=[['১','ক্যাটাগরি'],['২','বিস্তারিত'],['৩','প্রিভিউ']];
 if(sent) return <Shell><main className="max-w-2xl mx-auto p-4"><div className="card text-center py-10"><div className="text-5xl">✅</div><h2 className="font-black text-xl mt-3">আপনার পোস্ট পর্যালোচনার জন্য পাঠানো হয়েছে</h2><p className="text-sm text-gray-600 mt-2">«{title}» — অনুমোদন হলেই নিউজফিডে দেখা যাবে। আপনার পোস্টের অবস্থা <b>আমার পোস্টসমূহ</b>-এ «অপেক্ষমাণ» হিসেবে দেখতে পাবেন।</p><div className="flex flex-col gap-2 mt-6"><Link href="/my-posts" className="btn w-full !py-3">আমার পোস্টসমূহ দেখুন</Link><button className="w-full bg-gray-100 rounded-2xl py-3 font-bold" onClick={()=>{setSent(false); setStep(1); setCat(''); setTitle(''); setSub('ফ্যামিলি বাসা'); setRooms(''); setPrice(''); setDesc(''); setLoc(locs[0]||''); setLandmark(''); setPhone(''); setWa(''); setHidePhone(false); setExp(''); setImg(''); setMsg('')}}>আরেকটি পোস্ট করুন</button></div></div></main></Shell>;
 return <Shell><main className="max-w-2xl mx-auto p-4">
 <div className="flex gap-2 mb-4">{steps.map(([n,l],i)=>(<button key={n} type="button" disabled={i+1>step} onClick={()=>{if(i+1<step)setStep(i+1)}} className={`chip !py-2 ${step===i+1?'!bg-emerald-600 !text-white':i+1<step?'bg-emerald-50 text-emerald-700':'bg-gray-100 text-gray-400'}`}>ধাপ {n} · {l}</button>))}</div>
 {step===1&&<div className="card"><h2 className="font-black">কী পোস্ট করতে চান? *</h2><div className="grid grid-cols-3 gap-2 mt-3">{cats.map((c:any)=>(<button key={c.slug} type="button" onClick={()=>{setCat(c.slug); setMsg(''); setStep(2)}} className={`rounded-2xl border p-3 text-center ${cat===c.slug?'border-emerald-600 bg-emerald-50':'border-gray-200'}`}><div className="mx-auto w-14 h-14 rounded-2xl grid place-items-center" style={{background:(c.color||'#0a7a54')+'1f'}}>{catIcon(c.slug)?<img src={catIcon(c.slug)} alt={c.name} className="w-10 h-10 object-contain"/>:<span className="text-3xl">{catEmoji(c.slug)}</span>}</div><b className="text-xs block mt-1 leading-snug">{c.name}</b></button>))}</div>{msg&&<p className="text-sm text-red-600 mt-3">{msg}</p>}<button type="button" className="btn w-full !py-3 mt-4" onClick={toStep2}>পরের ধাপ ›</button></div>}
 {step===2&&<div className="space-y-4">
  <div className="card"><h2 className="font-black">পোস্টের মূল বিবরণ ও মূল্য *</h2><label>পোস্টের শিরোনাম *<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="যেমন: কধুরখীল মোড়ে ৩ রুমের ফ্যামিলি বাসা ভাড়া"/></label><label>ধরণ / সাব-ক্যাটাগরি<select value={sub} onChange={e=>setSub(e.target.value)}><option>ফ্যামিলি বাসা</option><option>মোবাইল / গ্যাজেট</option></select></label><label>রুমের বিবরণ<input value={rooms} onChange={e=>setRooms(e.target.value)} placeholder="৩ রুম + ড্রয়িং"/></label><label>মাসিক ভাড়া / দাম (টাকা)<input value={price} onChange={e=>setPrice(e.target.value)} type="number" placeholder="৮,৫০০"/></label><label>বিস্তারিত বিবরণ *<textarea value={desc} onChange={e=>setDesc(e.target.value)} rows={4} placeholder="স্পেস, সুবিধা বা বৈশিষ্ট্য লিখুন..."/></label>{['jobs','house','market'].includes(cat)&&<><label>{cat==='jobs'?'আবেদনের শেষ তারিখ':'মেয়াদ শেষের তারিখ'} (ঐচ্ছিক)<input type="date" value={exp} onChange={e=>setExp(e.target.value)}/></label><p className="text-xs text-gray-500">তারিখ দিলে ওই দিনের পর পোস্টটি সক্রিয় তালিকা ও অনুসন্ধানে আর দেখা যাবে না (সরাসরি লিংকে মেয়াদোত্তীর্ণ নোটিশসহ দেখা যাবে)। খালি রাখলে মেয়াদ থাকবে না।</p></>}</div>
  <div className="card"><h2 className="font-black">বোয়ালখালীর এলাকা ও ঠিকানা *</h2><select value={loc} onChange={e=>setLoc(e.target.value)}>{locs.map((l:string)=><option key={l}>{l}</option>)}</select><input value={landmark} onChange={e=>setLandmark(e.target.value)} placeholder="নির্দিষ্ট ল্যান্ডমার্ক / রোড নম্বর — যেমন: বোয়ালখালী কারখানা গেটের বিপরীতে"/></div>
  <div className="card"><h2 className="font-black">ছবি সংযুক্ত করুন (ঐচ্ছিক)</h2><p className="text-xs">JPG, PNG বা WEBP (ছবি দিলে বেশি ভিউ পাওয়া যায়)</p><input type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>upload(e.target.files?.[0])}/>{upBusy&&<p className="text-xs mt-2">আপলোড হচ্ছে…</p>}{img&&<div className="relative inline-block mt-2"><img src={img} className="h-32 rounded-xl"/><button type="button" onClick={()=>setImg('')} className="chip absolute top-1 right-1 !bg-red-600 !text-white">✕ ছবি সরান</button></div>}</div>
  <div className="card"><h2 className="font-black">যোগাযোগ ও পরিচয় সেটিংস</h2><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="মোবাইল 017XXXXXXXX"/><input value={wa} onChange={e=>setWa(e.target.value)} placeholder="হোয়াটসঅ্যাপ 017XXXXXXXX"/><label className="flex gap-2 items-center bg-emerald-50 p-3 rounded-xl"><input type="checkbox" className="!w-auto"/> বোয়ালখালী কানেক্ট ভেরিফাইড পোস্ট (অ্যাডমিন যাচাই সাপেক্ষে)</label><label className="flex gap-2 items-center bg-slate-50 p-3 rounded-xl mt-2"><input type="checkbox" checked={hidePhone} onChange={e=>setHidePhone(e.target.checked)} className="!w-auto"/> ফোন নম্বর লুকান — পোস্টে কল/WhatsApp বোতাম দেখাবে না</label></div>
  <div className="card !bg-amber-50"><h2 className="font-black">🛡️ নিরাপত্তা টিপস</h2><ul className="text-sm list-disc pl-5 space-y-1"><li>জনসমাগম ও নিরাপদ স্থানে দেখা করুন।</li><li>আগে থেকে অগ্রিম টাকা পাঠাবেন না।</li><li>পণ্য নিজে দেখে যাচাই করে তারপর কিনুন।</li><li>সন্দেহজনক পোস্ট দেখলে রিপোর্ট করুন।</li></ul></div>
  {msg&&<p className="card !text-red-600 text-sm">{msg}</p>}
  <div className="flex gap-2"><button type="button" className="flex-1 bg-gray-100 rounded-2xl py-3 font-bold" onClick={()=>setStep(1)}>‹ ক্যাটাগরি বদলান</button><button type="button" className="btn flex-1 !py-3" onClick={toStep3}>প্রিভিউ দেখুন ›</button></div>
  <a href="/" className="block text-center bg-gray-100 rounded-2xl py-3 font-bold">বাতিল করুন</a></div>}
 {step===3&&<div className="space-y-4">
  <div className="card"><h2 className="font-black">ফিডে যেমন দেখাবে</h2><div className="max-w-sm mx-auto mt-3 pointer-events-none"><PostCard p={{id:'',categorySlug:cat,title:title||'শিরোনাম',desc,price:Number(price||0),location:loc,landmark,phone,whatsapp:wa,image:img,hidePhone,sold:false,verified:false,promoted:false,views:0}} catName={cObj?.name} catColor={cObj?.color}/></div></div>
  <div className="card text-sm space-y-1"><h2 className="font-black">বিস্তারিত পেজে যা থাকবে</h2><p><b>ক্যাটাগরি:</b> {cObj?.name||cat}</p><p><b>বিবরণ:</b> {desc}</p><p><b>এলাকা:</b> {loc}{landmark?' · '+landmark:''}</p><p><b>মোবাইল:</b> {phone}{hidePhone?' (লুকানো থাকবে)':''}</p>{exp&&<p><b>{cat==='jobs'?'আবেদনের শেষ তারিখ':'মেয়াদ শেষের তারিখ'}:</b> {new Date(exp+'T00:00:00').toLocaleDateString('bn-BD')}</p>}{wa&&<p><b>হোয়াটসঅ্যাপ:</b> {wa}</p>}<p className="text-amber-700 bg-amber-50 rounded-xl p-2">প্রকাশের পর পোস্টটি মডারেশনে যাবে — অনুমোদন হলেই ফিডে দেখা যাবে।</p></div>
  {msg&&<p className="card !text-red-600 text-sm">{msg}</p>}
  <div className="flex gap-2"><button type="button" className="flex-1 bg-gray-100 rounded-2xl py-3 font-bold" onClick={()=>setStep(2)}>‹ সম্পাদনা করুন</button><button type="button" disabled={busy} className="btn flex-1 !py-4 text-lg" onClick={submit}>{busy?'পাঠানো হচ্ছে…':'✨ প্রকাশ করুন'}</button></div></div>}
 </main></Shell>}
