'use client'; import {Shell} from '@/components/ui'; import {useState,useEffect} from 'react';
export default function P(){const [cats,setCats]=useState<any[]>([]); const [msg,setMsg]=useState(''); const [img,setImg]=useState('');
 useEffect(()=>{fetch('/api/posts').then(()=>{}); setCats(JSON.parse(document.getElementById('cats')?.textContent||'[]'))},[]);
 return <Shell><main className="max-w-2xl mx-auto p-4"><form className="space-y-4" onSubmit={async(e)=>{e.preventDefault(); const f=new FormData(e.currentTarget); const body=Object.fromEntries(f); (body as any).image=img; (body as any).hidePhone=f.get('hidePhone')==='on'; const r=await fetch('/api/posts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const j=await r.json(); setMsg(r.ok?'✅ পোস্ট জমা হয়েছে — মডারেশন PENDING':('❌ '+j.error+' (লগইন প্রয়োজন হলে /login)'))}}>
 <div className="card"><h2 className="font-black">১. ক্যাটাগরি নির্বাচন করুন *</h2><select name="categorySlug" required>{cats.map((c:any)=><option key={c.slug} value={c.slug}>{c.name} — {c.desc}</option>)}</select></div>
 <div className="card"><h2 className="font-black">২. পোস্টের মূল বিবরণ ও মূল্য *</h2><label>পোস্টের শিরোনাম *<input name="title" required placeholder="যেমন: কধুরখীল মোড়ে ৩ রুমের ফ্যামিলি বাসা ভাড়া"/></label><label>ধরণ / সাব-ক্যাটাগরি<select name="subcategory"><option>ফ্যামিলি বাসা</option><option>মোবাইল / গ্যাজেট</option></select></label><label>রুমের বিবরণ<input name="rooms" placeholder="৩ রুম + ড্রয়িং"/></label><label>মাসিক ভাড়া / দাম (টাকা)<input name="price" type="number" placeholder="৮,৫০০"/></label><label>বিস্তারিত বিবরণ *<textarea name="desc" required rows={4} placeholder="স্পেস, সুবিধা বা বৈশিষ্ট্য লিখুন..."/></label></div>
 <div className="card"><h2 className="font-black">৩. বোয়ালখালীর এলাকা ও ঠিকানা *</h2><select name="location"><option>কধুরখীল</option><option>বোয়ালখালী বাজার</option><option>বোয়ালখালী বাস স্ট্যান্ড</option></select><input name="landmark" placeholder="নির্দিষ্ট ল্যান্ডমার্ক / রোড নম্বর — যেমন: বোয়ালখালী কারখানা গেটের বিপরীতে"/></div>
 <div className="card"><h2 className="font-black">৪. ছবি সংযুক্ত করুন (ঐচ্ছিক)</h2><p className="text-xs">JPG, PNG বা WEBP (ছবি দিলে বেশি ভিউ পাওয়া যায়)</p><input type="file" accept=".jpg,.jpeg,.png,.webp" onChange={async(e)=>{const file=e.target.files?.[0]; if(!file)return; const fd=new FormData(); fd.append('file',file); const r=await fetch('/api/upload',{method:'POST',body:fd}); const j=await r.json(); setImg(j.url||''); setMsg(j.url?'ছবি আপলোড হয়েছে':'আপলোড ব্যর্থ: '+j.error)}}/>{img&&<img src={img} className="h-32 rounded-xl mt-2"/>}</div>
 <div className="card"><h2 className="font-black">৫. যোগাযোগ ও পরিচয় সেটিংস</h2><input name="phone" placeholder="মোবাইল 017XXXXXXXX" required/><input name="whatsapp" placeholder="হোয়াটসঅ্যাপ 017XXXXXXXX"/><label className="flex gap-2 items-center bg-emerald-50 p-3 rounded-xl"><input type="checkbox" className="!w-auto"/> বোয়ালখালী কানেক্ট ভেরিফাইড পোস্ট (অ্যাডমিন যাচাই সাপেক্ষে)</label><label className="flex gap-2 items-center bg-slate-50 p-3 rounded-xl mt-2"><input type="checkbox" name="hidePhone" className="!w-auto"/> ফোন নম্বর লুকান — পোস্টে কল/WhatsApp বোতাম দেখাবে না</label></div>
 <div className="card !bg-amber-50"><h2 className="font-black">🛡️ নিরাপত্তা টিপস</h2><ul className="text-sm list-disc pl-5 space-y-1"><li>জনসমাগম ও নিরাপদ স্থানে দেখা করুন।</li><li>আগে থেকে অগ্রিম টাকা পাঠাবেন না।</li><li>পণ্য নিজে দেখে যাচাই করে তারপর কিনুন।</li><li>সন্দেহজনক পোস্ট দেখলে রিপোর্ট করুন।</li></ul></div>
 {msg&&<p className="card">{msg}</p>}<button className="btn w-full !py-4 text-lg">✨ এখনই পোস্ট প্রকাশ করুন</button><a href="/" className="block text-center bg-gray-100 rounded-2xl py-3 font-bold">বাতিল করুন</a></form><script id="cats" type="application/json" dangerouslySetInnerHTML={{__html:JSON.stringify([{slug:'house',name:'বাসা ভাড়া',desc:'বাসা / মেস / দোকান'},{slug:'market',name:'বাই-সেল',desc:'মোবাইল / পণ্য'},{slug:'doctor',name:'ডাক্তার',desc:''},{slug:'blood',name:'রক্তদান',desc:''},{slug:'food',name:'রেস্টুরেন্ট ও খাবার',desc:''},{slug:'jobs',name:'চাকরি',desc:''},{slug:'lost',name:'হারানো ও প্রাপ্তি',desc:''},{slug:'electrician',name:'ইলেকট্রিশিয়ান',desc:''}])}}/></main></Shell>}
