export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,mutateDBAsync,audit,id,now} from '@/lib/db'; import {requireRole} from '@/lib/auth'; import {hasPermission} from '@/lib/permissions'; import {sanitizeContentType,validateTypeBody,ensureCmsSeeds,needsCmsSeeds} from '@/lib/cms';
// Content types admin (content_types.manage). GET also lazily seeds the 22 built-in types
// (data, editable) the first time the collection is empty — idempotent, never repeated.
async function guard(perm:string){ const r:any=await requireRole(['ADMIN','SUPER_ADMIN','MODERATOR']); if(r.error) return r; if(!hasPermission(r.user.role,perm)) return {error:'FORBIDDEN',status:403}; return r; }
const fail=(r:any)=>NextResponse.json({error:r.error||'FORBIDDEN'},{status:r.status||403});
async function readTypes(){ let db=await readDBAsync(); if(needsCmsSeeds(db)){ await mutateDBAsync((d:any)=>{ ensureCmsSeeds(d,'system'); }); db=await readDBAsync(); } return db; }
export async function GET(){ const r=await guard('content.view'); if(r.error) return fail(r); const db=await readTypes(); const counts:any={}; (db.contents||[]).forEach((c:any)=>{ counts[c.typeSlug]=(counts[c.typeSlug]||0)+1; }); return NextResponse.json({types:db.content_types.map((t:any)=>({...sanitizeContentType(t),contents:counts[t.slug]||0})).sort((a:any,b:any)=>a.order-b.order)}); }
export async function POST(req:Request){ const r=await guard('content_types.manage'); if(r.error) return fail(r); const b=await req.json().catch(()=>({})); const out:any=await mutateDBAsync((db:any)=>{ ensureCmsSeeds(db,r.user.id); const v:any=validateTypeBody(b,db); if(v.error) return v; const t={id:id('ct'),...v.data,builtin:false,createdBy:r.user.id,createdAt:now(),updatedAt:now()}; db.content_types.push(t); audit(db,r.user.email,'CONTENT_TYPE_CREATE',t.id,{slug:t.slug}); return {ok:true,type:sanitizeContentType(t)}; }); if(out.error) return NextResponse.json(out,{status:400}); return NextResponse.json(out); }
