export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,mutateDBAsync,audit,now} from '@/lib/db'; import {requireRole} from '@/lib/auth'; import {hasPermission} from '@/lib/permissions'; import {sanitizeContentType,validateTypeBody} from '@/lib/cms';
// Single content type: read / update (slug locked while contents reference it) / delete
// (blocked while contents reference it — deactivate instead).
async function guard(perm:string){ const r:any=await requireRole(['ADMIN','SUPER_ADMIN','MODERATOR']); if(r.error) return r; if(!hasPermission(r.user.role,perm)) return {error:'FORBIDDEN',status:403}; return r; }
const fail=(r:any)=>NextResponse.json({error:r.error||'FORBIDDEN'},{status:r.status||403});
export async function GET(_req:Request,{params}:{params:{id:string}}){ const r=await guard('content.view'); if(r.error) return fail(r); const db=await readDBAsync(); const t=db.content_types.find((x:any)=>x.id===params.id); if(!t) return NextResponse.json({error:'TYPE_NOT_FOUND'},{status:404}); return NextResponse.json({type:sanitizeContentType(t)}); }
export async function PATCH(req:Request,{params}:{params:{id:string}}){ const r=await guard('content_types.manage'); if(r.error) return fail(r); const b=await req.json().catch(()=>({})); const out:any=await mutateDBAsync((db:any)=>{ const t=db.content_types.find((x:any)=>x.id===params.id); if(!t) return {e:404,error:'TYPE_NOT_FOUND'}; const v:any=validateTypeBody(b,db,t.id); if(v.error) return {e:400,...v}; if(v.data.slug!==t.slug&&(db.contents||[]).some((c:any)=>c.typeSlug===t.slug)) return {e:400,error:'SLUG_IMMUTABLE',message:'এই টাইপে কনটেন্ট আছে — slug বদলানো যাবে না'}; Object.assign(t,v.data,{updatedAt:now()}); audit(db,r.user.email,'CONTENT_TYPE_UPDATE',t.id,{slug:t.slug}); return {ok:true,type:sanitizeContentType(t)}; }); if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
export async function DELETE(_req:Request,{params}:{params:{id:string}}){ const r=await guard('content_types.manage'); if(r.error) return fail(r); const out:any=await mutateDBAsync((db:any)=>{ const t=db.content_types.find((x:any)=>x.id===params.id); if(!t) return {e:404,error:'TYPE_NOT_FOUND'}; if((db.contents||[]).some((c:any)=>c.typeSlug===t.slug)) return {e:409,error:'TYPE_IN_USE',message:'এই টাইপে কনটেন্ট আছে — মোছা যাবে না; চাইলে নিষ্ক্রিয় করুন'}; db.content_types=db.content_types.filter((x:any)=>x.id!==params.id); audit(db,r.user.email,'CONTENT_TYPE_DELETE',params.id,{slug:t.slug}); return {ok:true,deleted:params.id}; }); if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
