import {Shell} from '@/components/ui'; export const metadata={title:'গোপনীয়তা নীতি — বোয়ালখালী কানেক্ট',description:'বোয়ালখালী কানেক্টে আপনার কোন তথ্য কীভাবে সংগ্রহ, ব্যবহার ও সুরক্ষিত রাখা হয়'};
// গোপনীয়তা নীতি — describes ACTUAL current practice only (verified against the
// codebase): Firebase Authentication, hashed/analytics-minimal logging, anonymized
// search logs (term+count+day, no identity), consent-gated donor phones masked for
// anonymous visitors. If a practice changes, this page must change with it.
export default function P(){ return <Shell><main className="max-w-3xl mx-auto p-4"><h1 className="font-black text-2xl">🔒 গোপনীয়তা নীতি</h1><p className="text-sm text-gray-500 mt-1">সর্বশেষ হালনাগাদ: অক্টোবর ২০২৬</p>
<section className="card mt-4"><h2 className="font-black">কোন তথ্য আমরা সংগ্রহ করি</h2><ul className="mt-2 list-disc space-y-1.5 ps-5 text-sm leading-relaxed"><li><b>অ্যাকাউন্ট তথ্য:</b> রেজিস্ট্রেশনের সময় নাম, ইমেইল, মোবাইল নম্বর, এলাকা, ঠিকানা, অ্যাকাউন্টের ধরন এবং (ঐচ্ছিক) রক্তের গ্রুপ।</li><li><b>আপনার দেওয়া কনটেন্ট:</b> পোস্ট, ছবি, অভিযোগ, রক্তদাতা হিসেবে নিবন্ধন (শুধুমাত্র আপনার স্পষ্ট সম্মতিতে) এবং গোপন তথ্য ডেস্কে পাঠানো প্রতিবেদন।</li><li><b>কারিগরি তথ্য:</b> লগইন সেশন কুকি এবং দিনভিত্তিক পরিদর্শন গণনা। সার্চ লগে শুধু খোঁজা শব্দ, ফলাফলের সংখ্যা ও তারিখ থাকে — কে খুঁজেছেন তা সংরক্ষণ করা হয় না।</li></ul></section>
<section className="card mt-3"><h2 className="font-black">তথ্য কীভাবে ব্যবহার হয়</h2><ul className="mt-2 list-disc space-y-1.5 ps-5 text-sm leading-relaxed"><li>সেবা পরিচালনা, পোস্ট প্রকাশের আগে যাচাই (মডারেশন) এবং নিরাপত্তা নিশ্চিত করতে।</li><li>রক্তদাতার তালিকায় মোবাইল নম্বর <b>অপরিচিত দর্শকের কাছে আংশিক লুকানো</b> থাকে; লগইন করা ব্যবহারকারী ও কর্তৃপক্ষ পূর্ণ নম্বর দেখতে পারেন।</li><li>আপনার তথ্য <b>কোনো তৃতীয় পক্ষের কাছে বিক্রি করা হয় না</b>। সেবাটি চালানোর জন্য প্রয়োজনীয় প্রযুক্তিগত অবকাঠামো (Google Firebase) ছাড়া তথ্য বাইরে পাঠানো হয় না।</li></ul></section>
<section className="card mt-3"><h2 className="font-black">লগইন ও নিরাপত্তা</h2><p className="mt-2 text-sm leading-relaxed">লগইন পরিচালিত হয় Firebase Authentication দিয়ে (ইমেইল/পাসওয়ার্ড ও Google)। পাসওয়ার্ড আমাদের সার্ভারে সরাসরি সংরক্ষিত হয় না। লগইন সেশনের জন্য ব্রাউজারে একটি কুকি ব্যবহৃত হয়।</p></section>
<section className="card mt-3"><h2 className="font-black">আপনার অধিকার</h2><p className="mt-2 text-sm leading-relaxed">নিজের তথ্য সংশোধন বা মুছে ফেলার অনুরোধ করতে ফুটারে দেওয়া যোগাযোগের মাধ্যমে অথবা অভিযোগ পেজ থেকে সাইট কর্তৃপক্ষের (অ্যাডমিন) সঙ্গে যোগাযোগ করুন। রক্তদাতা হিসেবে নিজের তথ্য সরাতে চাইলে একই পথে জানান — অনুরোধ পেলে যাচাই করে ব্যবস্থা নেওয়া হবে।</p></section>
</main></Shell>; }
