import Link from 'next/link'; import {readDBAsync} from '@/lib/db'; import {currentUser} from '@/lib/auth'; import {Shell,bn} from '@/components/ui'; import {Phone,Search,Plus,Sparkles,MapPin,Bookmark} from 'lucide-react';
export const dynamic='force-dynamic';
async function Weather(){ try{const r=await fetch('https://api.open-meteo.com/v1/forecast?latitude=22.382&longitude=91.921&current=temperature_2m,relative_humidity_2m,wind_speed_10m,visibility,weather_code&timezone=Asia%2FDhaka',{next:{revalidate:600}}); const j=await r.json(); const c=j.current; return <div className="card !bg-[#0b2e35] text-white"><div className="flex justify-between"><b>🌍 বোয়ালখালী আবহাওয়া ● লাইভ</b><span className="text-yellow-300 text-xs">আপডেট: {new Date(c.time).toLocaleTimeString('bn-BD')}</span></div><div className="text-5xl font-black my-3">{bn(Math.round(c.temperature_2m))}°<span className="text-yellow-400 text-2xl">C</span></div><p>আংশিক মেঘলা • অনুভূত: {bn(Math.round(c.temperature_2m))}°C</p><div className="grid grid-cols-3 gap-2 mt-3 text-center text-sm"><div className="bg-white/10 rounded-xl p-2">আর্দ্রতা<br/><b className="text-yellow-300">{bn(c.relative_humidity_2m)}%</b></div><div className="bg-white/10 rounded-xl p-2">বাতাস<br/><b className="text-yellow-300">{bn(c.wind_speed_10m)} কিমি</b></div><div className="bg-white/10 rounded-xl p-2">দৃশ্যমানতা<br/><b className="text-yellow-300">{bn(Math.round((c.visibility||8000)/1000))} কিমি</b></div></div><p className="text-[10px] opacity-60 mt-2">আবহাওয়া: Open-Meteo</p></div>}catch{return <div className="card">আবহাওয়া লোড হচ্ছে না — API unavailable</div>} }
export default async function Home(){ const db=await readDBAsync(); const u=await currentUser(); const cats=db.categories.filter((c:any)=>c.enabled); const blood=db.blood_requests.find((b:any)=>b.status==='ACTIVE'); const ad=db.advertisements[0]; const posts=db.posts.filter((p:any)=>p.status==='APPROVED').slice(0,6);
 return <Shell><main className="max-w-7xl mx-auto p-3 space-y-4">
 {blood&&<div className="bg-red-600 text-white rounded-3xl p-4 flex gap-3 shadow"><span className="text-3xl">💧</span><div className="flex-1"><span className="bg-white text-red-600 chip">জরুরি রক্ত প্রয়োজন</span> <span className="bg-red-800 chip text-white">{blood.bloodGroup}</span><p className="font-bold mt-1">রোগী: {blood.patient} ({blood.location})</p></div><a href={`tel:${blood.contact}`} className="bg-white text-red-600 w-11 h-11 rounded-full grid place-items-center"><Phone/></a></div>}
 <div className="bg-red-600 text-white rounded-2xl p-3 flex justify-between"><span>⚠️ <b>জরুরি সতর্কতা</b> — প্রয়োজনে যোগাযোগ করুন</span><Link href="/emergency" className="underline">জরুরি সেবা →</Link></div>
 <div className="bg-emerald-800 text-white rounded-2xl p-3">✨ <b>ঘোষণা</b> — আমরা আছি আপনার পাশে। <span className="float-right">স্বাগতম!</span></div>
 <div><p className="text-emerald-700 text-sm">● 📍 বোয়ালখালী, চট্টগ্রাম</p><h1 className="text-2xl font-black">স্বাগতম, {u?u.name:'অতিথি'}</h1><p className="text-gray-500">বোয়ালখালীর সব সেবা এক ঠিকানায় 🌱</p></div>
 <form action="/search" className="flex bg-white rounded-full shadow p-1"><Search className="m-3 text-emerald-600"/><input name="q" placeholder="কি খুঁজছেন? (যেমন: বাসা ভাড়া, ডাক্তার...)" className="!border-0 !bg-transparent"/><button className="btn !rounded-full">খুঁজুন</button></form>
 <div className="rounded-[28px] bg-gradient-to-br from-emerald-800 to-emerald-600 text-white p-5"><div className="flex justify-between"><span>💳 নাগরিক কার্ড: বোয়ালখালী কানেক্ট</span><span className="chip bg-emerald-500/40">● সক্রিয় (Active)</span></div><h2 className="text-xl font-black mt-3">স্মার্ট নাগরিক সেবা ও মার্কেটপ্লেস</h2><p className="text-emerald-100 text-sm">আপনার শহরের বাসা ভাড়া, জরুরি কন্টাক্ট, রক্তদাতা ও লোকাল সেবা</p><div className="flex gap-3 mt-4"><Link href="/create" className="bg-white text-emerald-800 rounded-2xl px-4 py-3 font-bold flex gap-2"><Plus/> নতুন পোস্ট দিন ›</Link><Link href="/emergency" className="border border-emerald-300 rounded-2xl px-4 py-3 font-bold">📞 জরুরি হেল্পলাইন ›</Link></div></div>
 {ad&&<div className="card !bg-emerald-900 text-white"><span className="chip bg-yellow-400 text-black">SPONSORED</span><p className="text-yellow-200 text-sm mt-2">✨ সর্বোচ্চ ৫০% পর্যন্ত মেগা ছাড়</p><h3 className="font-black text-lg">{ad.title}</h3><p className="text-sm opacity-80">{ad.body}</p><Link href="/restaurants" className="btn !bg-white !text-emerald-900 mt-3">বিস্তারিত দেখুন →</Link></div>}
 <Weather/>
 <section><h3 className="font-black">মূল ক্যাটাগরিসমূহ <span className="text-xs text-gray-400">• ক্লিক করে বিস্তারিত দেখুন</span></h3><div className="grid grid-cols-4 md:grid-cols-8 gap-3 mt-3">{cats.map((c:any)=>(<Link key={c.slug} href={`/category/${c.slug}`} className="card !p-3 text-center hover:scale-[1.02] transition"><div className="text-3xl" style={{color:c.color}}>●</div><p className="text-xs font-bold mt-1">{c.name}</p></Link>))}</div></section>
 <section className="card !bg-orange-50"><div className="flex justify-between"><h3 className="font-black">🍴 রেস্টুরেন্ট ও খাবার</h3><Link href="/restaurants" className="text-orange-600 font-bold">সব দেখুন →</Link></div><p className="text-xs text-gray-500">বোয়ালখালীর স্পেশাল স্বাদ</p><div className="grid md:grid-cols-2 gap-3 mt-3">{db.restaurants.map((r:any)=>(<Link key={r.id} href="/restaurants" className="bg-white rounded-2xl overflow-hidden shadow"><img src={r.image} className="h-32 w-full object-cover"/><div className="p-3"><span className="chip bg-orange-100 text-orange-700">{r.category}</span> <span className="chip bg-emerald-100">{r.price}</span><p className="font-bold">{r.name}</p><p className="text-xs text-gray-500">📍 {r.location}</p></div></Link>))}</div></section>
 <section><div className="flex justify-between"><h3 className="font-black">📈 বোয়ালখালী শহরের পোস্টসমূহ</h3><Link href="/categories" className="chip bg-emerald-100">সব দেখুন ›</Link></div><p className="text-xs text-gray-500">শহরের সর্বশেষ বাসা ভাড়া, কেনাবেচা ও জরুরি আপডেট</p><div className="flex gap-2 my-3"><span className="btn !py-2">🕐 নতুন পোস্ট</span><span className="chip border">🔥 জনপ্রিয়</span></div><div className="grid md:grid-cols-2 gap-3">{posts.map((p:any)=>(<Link key={p.id} href={`/post/${p.id}`} className="card flex gap-3"><img src={p.image||'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400'} className="w-24 h-24 rounded-2xl object-cover"/><div className="flex-1"><span className="chip bg-emerald-100">{p.categorySlug}</span> {p.promoted&&<span className="chip bg-orange-500 text-white">PROMOTED</span>}<span className="chip bg-emerald-50 float-right">{bn(p.price)} ৳</span><p className="font-bold line-clamp-2">{p.title}</p><p className="text-xs text-gray-500">📍 {p.location}</p></div><Bookmark size={18}/></Link>))}</div></section>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-center">{[['/complaint','নাগরিক অভিযোগ ডেস্ক'],['/secret','গোপন তথ্য'],['/blood','রক্তদান'],['/transport','বাস ও ট্রেন']].map(([h,l])=>(<Link key={h} href={h} className="card font-bold">{l}</Link>))}</div>
 </main></Shell> }
