'use client'; import {useState} from 'react'; import {useRouter} from 'next/navigation'; import {errMsg} from '@/lib/errMsg';
const BLOOD_GROUPS=['A+','A-','B+','B-','O+','O-','AB+','AB-'];
const TYPES=[['CITIZEN','নাগরিক'],['BUSINESS','ব্যবসায়ী'],['SERVICE_PROVIDER','সেবাদাতা']];
export default function ProfileCompleteForm({locations,initial}:any){const router=useRouter(); const [msg,setMsg]=useState(''); const [err,setErr]=useState(''); const [busy,setBusy]=useState(false);
 const submit=async(ev:any)=>{ev.preventDefault(); setErr(''); setMsg(''); const f=new FormData(ev.currentTarget); const phone=String(f.get('phone')||'').replace(/[\s-]/g,''); if(!/^01[3-9]\d{8}$/.test(phone)){setErr('সঠিক ১১ ডিজিটের মোবাইল নম্বর দিন (01XXXXXXXXX)'); return;} const body:any={phone,area:String(f.get('area')||''),address:String(f.get('address')||''),accountType:String(f.get('accountType')||'CITIZEN'),bloodGroup:String(f.get('bloodGroup')||'')}; setBusy(true); try{const r=await fetch('/api/auth/profile-complete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const j=await r.json(); if(!r.ok){setErr(errMsg(j.error)); return;} setMsg('তথ্য সংরক্ষণ হয়েছে'); router.refresh();}catch{setErr('তথ্য সংরক্ষণ করা যায়নি, আবার চেষ্টা করুন');}finally{setBusy(false);}};
 return <form onSubmit={submit} className="card mt-3 text-left"><h2 className="font-black">আপনার তথ্য সম্পূর্ণ করুন</h2><p className="text-sm text-gray-500">Google দিয়ে লগইন করেছেন — নিচের তথ্যগুলো দিলে রেজিস্ট্রেশন সম্পূর্ণ হবে।</p>
 <label className="block text-sm font-bold mt-3">মোবাইল নম্বর *</label><input name="phone" required inputMode="tel" placeholder="01XXXXXXXXX" defaultValue={initial?.phone||''}/>
 <label className="block text-sm font-bold mt-3">এলাকা *</label><select name="area" required defaultValue={initial?.area||''}><option value="">— এলাকা নির্বাচন করুন —</option>{locations.map((n:string)=><option key={n} value={n}>{n}</option>)}</select>
 <label className="block text-sm font-bold mt-3">ঠিকানা</label><input name="address" placeholder="আপনার ঠিকানা" defaultValue={initial?.address||''}/>
 <label className="block text-sm font-bold mt-3">অ্যাকাউন্টের ধরন</label><select name="accountType" defaultValue={initial?.accountType||'CITIZEN'}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>
 <label className="block text-sm font-bold mt-3">রক্তের গ্রুপ (ঐচ্ছিক)</label><select name="bloodGroup" defaultValue={initial?.bloodGroup||''}><option value="">— নির্বাচন করুন —</option>{BLOOD_GROUPS.map(g=><option key={g} value={g}>{g}</option>)}</select>
 {err&&<p className="text-red-600 text-sm mt-2">{err}</p>}{msg&&<p className="text-emerald-700 text-sm mt-2">{msg}</p>}
 <button className="btn w-full mt-3" disabled={busy}>{busy?'সংরক্ষণ হচ্ছে…':'তথ্য সংরক্ষণ করুন'}</button></form>}
