'use client'; import {bn} from './ui'; import {errMsg} from '@/lib/errMsg'; import {useState} from 'react'; import {useRouter} from 'next/navigation'; import Link from 'next/link';
// Owner mini-dashboard + verification apply (Wave 3). Server (app/businesses) hands
// this component the caller's OWN business contents with their persisted view counts
// and the derived verification state; applying POSTs /api/business/verify and
// refreshes. It can only ever ASK — the badge itself is written by admins.
export type BizItem={id:string,title:string,slug:string,status:string,views:number,verState:'verified'|'pending'|'rejected'|'none',reviewNote:string,verifiedAt:string};
const ST:any={PUBLISHED:['প্রকাশিত','bg-emerald-100 text-emerald-800'],DRAFT:['খসড়া','bg-slate-200 text-slate-700'],PENDING:['অপেক্ষমাণ','bg-amber-100 text-amber-800'],UNPUBLISHED:['অপ্রকাশিত','bg-slate-200 text-slate-700'],ARCHIVED:['আর্কাইভ','bg-slate-200 text-slate-700'],TRASHED:['ট্র্যাশ','bg-red-100 text-red-700']};
export function BusinessOwner({items,canEdit}:{items:BizItem[];canEdit:boolean}){ const router=useRouter(); const [notes,setNotes]=useState<Record<string,string>>({}); const [busy,setBusy]=useState(''); const [msg,setMsg]=useState('');
 const apply=async(it:BizItem)=>{ setBusy(it.id); setMsg(''); const r=await fetch('/api/business/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contentId:it.id,note:notes[it.id]||''})}); const j=await r.json().catch(()=>({})); setBusy(''); if(r.ok){ setMsg('আবেদন পাঠানো হয়েছে — অ্যাডমিন যাচাই করে সিদ্ধান্ত জানাবেন।'); router.refresh(); } else setMsg('ব্যর্থ: '+(j.message||errMsg(j.error))); };
 return <section className="card mt-3"><h2 className="font-black">🏪 আমার ব্যবসা</h2><p className="text-xs text-gray-500 mt-0.5">নিজের ব্যবসাপ্রতিষ্ঠানের অবস্থা, মোট দেখা (ভিউ) ও যাচাইয়ের অগ্রগতি এখানে দেখুন। যাচাইকৃত হলে নামের পাশে ✓ ব্যাজ দেখাবে।</p>
 {msg&&<p className="mt-2 rounded-xl bg-brand-50 p-2 text-sm">{msg}</p>}
 {items.length===0?<p className="mt-3 text-sm text-gray-500">আপনার নামে এখনো কোনো ব্যবসাপ্রতিষ্ঠান নিবন্ধিত নেই। ব্যবসা যোগ করতে <Link href="/about" className="font-bold text-brand-700">অ্যাডমিনের সঙ্গে যোগাযোগ করুন</Link>।</p>:
 <div className="mt-3 grid gap-2">{items.map(it=>{ const st=ST[it.status]||[it.status,'bg-slate-100']; return <div key={it.id} className="rounded-2xl border border-[var(--line)] p-3"><div className="flex flex-wrap items-center gap-2"><Link href={'/content/business/'+it.slug} className="font-bold hover:text-brand-700">{it.title}</Link><span className={'chip '+st[1]}>{st[0]}</span>{it.verState==='verified'&&<span className="chip bg-emerald-600 text-white">✓ যাচাইকৃত</span>}{it.verState==='pending'&&<span className="chip bg-amber-100 text-amber-800">যাচাই অপেক্ষমাণ</span>}{it.verState==='rejected'&&<span className="chip bg-red-100 text-red-700">আবেদন গৃহীত হয়নি</span>}</div>
 <p className="mt-1 text-xs text-gray-500">👁 মোট দেখা হয়েছে {bn(it.views)} বার{it.verState==='verified'&&it.verifiedAt?(' • যাচাইকৃত: '+new Date(it.verifiedAt).toLocaleDateString('bn-BD')):''}</p>
 {it.verState==='rejected'&&it.reviewNote&&<p className="mt-1 text-xs text-red-600">অ্যাডমিনের মন্তব্য: {it.reviewNote}</p>}
 {(it.verState==='none'||it.verState==='rejected')&&<div className="mt-2 flex flex-wrap gap-2"><input value={notes[it.id]||''} onChange={e=>setNotes({...notes,[it.id]:e.target.value})} placeholder="কিছু বলতে চাইলে লিখুন (ঐচ্ছিক)" className="min-w-56 flex-1"/><button className="btn !py-2" disabled={busy===it.id} onClick={()=>apply(it)}>{busy===it.id?'পাঠানো হচ্ছে…':'✓ যাচাইয়ের আবেদন করুন'}</button></div>}
 {it.verState==='pending'&&<p className="mt-1 text-xs text-gray-400">আবেদনটি অ্যাডমিনের পর্যালোচনার অপেক্ষায় আছে।</p>}
 <p className="mt-2 text-xs">{canEdit?<Link href="/admin/content" className="font-bold text-brand-700">✏️ CMS-এ সম্পাদনা করুন →</Link>:<span className="text-gray-400">তথ্য সম্পাদনা অ্যাডমিন প্যানেল থেকে করা হয় — বদল দরকার হলে অ্যাডমিনকে জানান।</span>}</p></div>; })}</div>}
 </section>; }
