import {readDBAsync,mutateDBAsync} from '@/lib/db'; import {Shell,bn,EmptyState,VerifiedBadge} from '@/components/ui'; import {sanitizeContentType,sanitizeContent,ensureCmsSeeds,needsCmsSeeds,featuredImage,locationText,fieldDisplay,contentTitle} from '@/lib/cms'; import {bnNorm} from '@/lib/search'; import Link from 'next/link';
// Shared hub listing over PUBLISHED CMS contents of a fixed set of types (শিক্ষা
// প্রতিষ্ঠান: school/college/university/madrasa; স্থানীয় ব্যবসা: business). Mirrors
// the /directory card + type/area/name filter pattern minus the map. Records come
// only from the CMS — nothing is seeded or invented here; an honest EmptyState
// renders while the admin has published nothing yet.
export async function CmsHub({typeSlugs,title,icon,desc,emptyTitle,emptyDesc,searchParams,below}:{typeSlugs:string[];title:string;icon:string;desc:string;emptyTitle:string;emptyDesc:string;searchParams:any;below?:any}){ let db=await readDBAsync(); if(needsCmsSeeds(db)){ await mutateDBAsync((d:any)=>{ ensureCmsSeeds(d,'system'); }); db=await readDBAsync(); }
 const types=(db.content_types||[]).map((t:any)=>sanitizeContentType(t)).filter((t:any)=>t&&t.enabled&&t.publicListing&&typeSlugs.includes(t.slug)).sort((a:any,b:any)=>a.order-b.order); const tBySlug:any={}; types.forEach((t:any)=>{ tBySlug[t.slug]=t; });
 const all=(db.contents||[]).map((c:any)=>sanitizeContent(c)).filter((c:any)=>c&&c.status==='PUBLISHED'&&tBySlug[c.typeSlug]);
 const fType=String(searchParams.type||''); const fArea=String(searchParams.area||''); const fQ=bnNorm(searchParams.q||'');
 const areaSet=new Set<string>(); all.forEach((c:any)=>{ const a=String((c.location||{}).area||(c.location||{}).union||'').trim(); if(a) areaSet.add(a); }); const areas:string[]=Array.from(areaSet).sort((a,b)=>a.localeCompare(b,'bn'));
 const items=all.filter((c:any)=>{ if(fType&&c.typeSlug!==fType) return false; if(fArea){ const l=c.location||{}; if(![l.area,l.union,l.upazila].filter(Boolean).includes(fArea)) return false; } if(fQ){ const hay=bnNorm([contentTitle(c),c.shortDesc,tBySlug[c.typeSlug].nameBn,locationText(c),(c.tags||[]).join(' ')].join(' ')); if(!hay.includes(fQ)) return false; } return true; });
 return <Shell><main className="max-w-6xl mx-auto p-4"><nav aria-label="breadcrumb" className="text-xs text-gray-500"><Link href="/content" className="font-bold text-brand-700">তথ্য ভাণ্ডার</Link> <span aria-hidden="true">›</span> <span>{title}</span></nav>
 <h1 className="font-black text-xl mt-2">{icon} {title}</h1><p className="text-sm text-gray-500">{desc} মোট {bn(all.length)}টি প্রকাশিত তথ্য{items.length!==all.length?`, ফিল্টারে ${bn(items.length)}টি`:''}</p>
 <form className="card my-3 grid md:grid-cols-4 gap-2" method="get"><div><label className="block text-sm font-bold">ধরন</label><select name="type" defaultValue={fType}><option value="">সব ধরন</option>{types.map((t:any)=>(<option key={t.slug} value={t.slug}>{t.icon} {t.nameBn||t.nameEn}</option>))}</select></div><div><label className="block text-sm font-bold">এলাকা</label><select name="area" defaultValue={fArea}><option value="">সব এলাকা</option>{areas.map(a=>(<option key={a} value={a}>{a}</option>))}</select></div><div className="md:col-span-2"><label className="block text-sm font-bold">নামে খুঁজুন</label><div className="flex gap-2"><input name="q" defaultValue={String(searchParams.q||'')} placeholder="নাম লিখুন…"/><button className="btn shrink-0">🔍 খুঁজুন</button></div></div></form>
 {all.length===0?<EmptyState icon={icon} title={emptyTitle} desc={emptyDesc} href="/content" cta="তথ্য ভাণ্ডার দেখুন"/>:items.length===0?<EmptyState icon="🔍" title="এই ফিল্টারে কিছু পাওয়া যায়নি" desc="ধরন বা এলাকা বদলে আবার চেষ্টা করুন।"/>:
 <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-3">{items.map((c:any)=>{ const t=tBySlug[c.typeSlug]; const img=featuredImage(c); const cardVals=(t.cardFields||[]).map((k:string)=>{ const f=(t.fields||[]).find((x:any)=>x.key===k); return f?fieldDisplay(f,(c.fields||{})[k]):''; }).filter(Boolean).slice(0,2); return <Link key={c.id} href={'/content/'+c.typeSlug+'/'+c.slug} className="card press lift block !p-0 overflow-hidden">{img?<img src={img.url} alt={img.alt||contentTitle(c)} loading="lazy" className="h-36 w-full object-cover"/>:<div className="h-36 w-full grid place-items-center text-5xl" style={{background:'#0a7a5414'}}>{t.icon||'📁'}</div>}<div className="p-3"><div className="flex items-center gap-1.5 flex-wrap"><span className="chip bg-brand-50 text-brand-700">{t.icon} {t.nameBn||t.nameEn}</span>{c.verified&&<VerifiedBadge label="যাচাইকৃত"/>}{(c.location&&locationText(c))&&<span className="text-[11px] text-gray-400">📍 {locationText(c)}</span>}</div><b className="block mt-1.5 leading-snug">{contentTitle(c)}</b>{c.shortDesc&&<p className="text-xs text-gray-500 mt-1 line-clamp-2">{c.shortDesc}</p>}{cardVals.length>0&&<p className="text-[11px] font-bold text-gray-600 mt-1.5">{cardVals.join(' • ')}</p>}<span className="text-xs font-bold text-brand-700 mt-2 inline-block">বিস্তারিত দেখুন →</span></div></Link>; })}</div>}
 {below}
 </main></Shell>; }
