export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,mutateDBAsync,audit} from '@/lib/db'; import {requireRole} from '@/lib/auth'; import {hasPermission} from '@/lib/permissions'; import {listImages,deleteImage} from '@/lib/imageStore'; import {contentTitle} from '@/lib/cms';
// Media library: lists every stored image (bk_images / upload dir) with a real usage scan
// across CMS contents, posts, ads and place art. Delete is BLOCKED while anything references
// the image — the reference must be removed first. (Spec asked for Firebase Storage; this app
// stores media in Firestore bk_images by design — Firebase Storage is Blaze-gated/off.)
async function guard(){ const r:any=await requireRole(['ADMIN','SUPER_ADMIN','MODERATOR']); if(r.error) return r; if(!hasPermission(r.user.role,'media.manage')) return {error:'FORBIDDEN',status:403}; return r; }
function usage(db:any){ const used:any={}; const add=(url:any,label:string)=>{ if(typeof url!=='string') return; const name=url.split('/').pop()||''; if(url.includes('/api/uploads/')&&name) (used[name]=used[name]||[]).push(label); }; (db.contents||[]).forEach((c:any)=>{ (c.images||[]).forEach((i:any)=>add(i.url,'কনটেন্ট: '+contentTitle(c))); if(c.seo&&c.seo.ogImage) add(c.seo.ogImage,'কনটেন্ট OG: '+contentTitle(c)); }); (db.posts||[]).forEach((p:any)=>{ add(p.image,'পোস্ট: '+(p.title||p.id)); (Array.isArray(p.images)?p.images:[]).forEach((u:any)=>add(u,'পোস্ট: '+(p.title||p.id))); }); (db.post_images||[]).forEach((pi:any)=>add(pi.url,'পোস্ট ছবি: '+(pi.postId||pi.id))); (db.advertisements||[]).forEach((a:any)=>add(a.image,'বিজ্ঞাপন: '+(a.title||a.id))); return used; }
export async function GET(){ const r=await guard(); if(r.error) return NextResponse.json({error:r.error},{status:r.status||403}); const db=await readDBAsync(); const used=usage(db); const images=(await listImages()).map((i:any)=>({...i,url:'/api/uploads/'+i.name,usedBy:used[i.name]||[]})); images.sort((a:any,b:any)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))); return NextResponse.json({images,total:images.length,usedCount:images.filter((i:any)=>i.usedBy.length).length}); }
export async function DELETE(req:Request){ const r=await guard(); if(r.error) return NextResponse.json({error:r.error},{status:r.status||403}); const b=await req.json().catch(()=>({})); const name=String(b.name||new URL(req.url).searchParams.get('name')||'').split('/').pop()||''; if(!name) return NextResponse.json({error:'NAME_REQUIRED'},{status:400}); const db=await readDBAsync(); const used=usage(db); if((used[name]||[]).length) return NextResponse.json({error:'MEDIA_IN_USE',message:'এই ছবি ব্যবহৃত হচ্ছে: '+used[name].join('; '),usedBy:used[name]},{status:409}); const removed=await deleteImage(name); if(!removed) return NextResponse.json({error:'NOT_FOUND'},{status:404}); await mutateDBAsync((d:any)=>{ audit(d,r.user.email,'MEDIA_DELETE',name,{}); return true; }); return NextResponse.json({ok:true,deleted:name,freedBytes:removed}); }
