'use client'; import {useState} from 'react'; import {useRouter} from 'next/navigation'; import Link from 'next/link';
const STATUS:any={NEW:'প্রাপ্ত হয়েছে',OPEN:'প্রাপ্ত হয়েছে',RECEIVED:'প্রাপ্ত হয়েছে',IN_PROGRESS:'প্রক্রিয়াধীন',RESOLVED:'সমাধান হয়েছে',REJECTED:'বাতিল'};
const STATUS_CLS:any={NEW:'chip bg-sky-100 text-sky-700',OPEN:'chip bg-sky-100 text-sky-700',RECEIVED:'chip bg-sky-100 text-sky-700',IN_PROGRESS:'chip bg-amber-100 text-amber-700',RESOLVED:'chip bg-emerald-100 text-emerald-700',REJECTED:'chip bg-red-100 text-red-700'};
export default function ComplaintClient({loggedIn,mine}:any){const router=useRouter(); const [msg,setMsg]=useState(''); const [err,setErr]=useState(''); const [busy,setBusy]=useState(false);
 const submit=async(e:any)=>{e.preventDefault(); setErr(''); setMsg(''); const f=new FormData(e.currentTarget); const body={type:String(f.get('type')||'অন্যান্য'),desc:String(f.get('desc')||''),location:String(f.get('location')||''),contact:String(f.get('contact')||'')}; setBusy(true); try{const r=await fetch('/api/complaints',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const j=await r.json(); if(!r.ok){setErr(j.error==='LOGIN_REQUIRED'?'জমা দিতে লগইন করুন':j.error==='DESC_REQUIRED'?'অভিযোগের বিবরণ লিখুন':'জমা দেওয়া যায়নি, আবার চেষ্টা করুন'); return;} setMsg('আপনার অভিযোগ জমা হয়েছে — স্ট্যাটাস: প্রাপ্ত হয়েছে। অ্যাডমিন ডেস্কে পাঠানো হয়েছে।'); e.currentTarget.reset(); router.refresh();}catch{setErr('জমা দেওয়া যায়নি, আবার চেষ্টা করুন');}finally{setBusy(false);}};
 return <div><form className="card" onSubmit={submit}><h1 className="font-black text-xl">নাগরিক অভিযোগ ডেস্ক</h1>
 <label className="block text-sm font-bold mt-3">অভিযোগের ধরন</label><select name="type"><option>রাস্তা</option><option>পানি</option><option>বিদ্যুৎ</option><option>নিরাপত্তা</option><option>অন্যান্য</option></select>
 <label className="block text-sm font-bold mt-3">বিবরণ *</label><textarea name="desc" required placeholder="কী সমস্যা, বিস্তারিত লিখুন" rows={4}/>
 <label className="block text-sm font-bold mt-3">এলাকা</label><input name="location" placeholder="যেমন: কধুরখীল"/>
 <label className="block text-sm font-bold mt-3">যোগাযোগ (ঐচ্ছিক)</label><input name="contact" placeholder="মোবাইল নম্বর"/>
 {err&&<p className="text-red-600 text-sm mt-2">{err}</p>}{msg&&<p className="text-emerald-700 text-sm mt-2">{msg}</p>}
 <button className="btn w-full mt-3" disabled={busy}>{busy?'জমা হচ্ছে…':'জমা দিন'}</button>
 {!loggedIn&&<p className="text-sm text-gray-500 mt-2">অভিযোগ জমা দিতে ও স্ট্যাটাস দেখতে <Link href="/login" className="text-emerald-700 font-bold">লগইন করুন</Link></p>}</form>
 {loggedIn&&(<div className="card mt-4"><h2 className="font-black">আমার অভিযোগসমূহ</h2>{(!mine||mine.length===0)&&<p className="text-sm text-gray-500 mt-1">আপনি এখনো কোনো অভিযোগ জমা দেননি।</p>}{mine&&mine.map((c:any)=>(<div key={c.id} className="border-b py-2"><span className="chip bg-slate-100">{c.type}</span> <span className={STATUS_CLS[c.status]||'chip bg-slate-100'}>{STATUS[c.status]||'প্রাপ্ত হয়েছে'}</span><p className="text-sm mt-1">{c.desc}</p><p className="text-xs text-gray-400">{c.location?`📍 ${c.location} • `:''}{c.createdAt?new Date(c.createdAt).toLocaleDateString('bn-BD'):''}</p></div>))}</div>)}
 </div>}
