import {Shell} from '@/components/ui'; export const metadata={title:'শর্তাবলী — বোয়ালখালী কানেক্ট',description:'বোয়ালখালী কানেক্ট ব্যবহারের নিয়ম ও শর্তাবলী'};
// শর্তাবলী — mirrors the platform's actual rules: moderation before publication,
// poster responsibility, no-guarantee disclaimers for blood/jobs/listings that the
// product already states in its UI. Nothing here promises more than the site does.
export default function P(){ return <Shell><main className="max-w-3xl mx-auto p-4"><h1 className="font-black text-2xl">📜 শর্তাবলী</h1><p className="text-sm text-gray-500 mt-1">সর্বশেষ হালনাগাদ: অক্টোবর ২০২৬</p>
<section className="card mt-4"><h2 className="font-black">পোস্ট ও কনটেন্টের দায়</h2><ul className="mt-2 list-disc space-y-1.5 ps-5 text-sm leading-relaxed"><li>নিজের দেওয়া পোস্ট, ছবি ও তথ্যের সঠিকতার সম্পূর্ণ দায় পোস্টদাতার নিজের।</li><li>সব পোস্ট প্রকাশের আগে মডারেশনের মধ্য দিয়ে যায়; কর্তৃপক্ষ যেকোনো পোস্ট অনুমোদন, প্রত্যাখ্যান বা অপসারণ করতে পারে।</li><li>ভুয়া তথ্য, প্রতারণামূলক বিজ্ঞাপন, অন্যের পরিচয়ে পোস্ট বা আইনবিরুদ্ধ কনটেন্ট কঠোরভাবে নিষিদ্ধ — এমন আচরণে অ্যাকাউন্ট বন্ধ করা হতে পারে।</li></ul></section>
<section className="card mt-3"><h2 className="font-black">রক্তদান সম্পর্কিত সতর্কতা</h2><p className="mt-2 text-sm leading-relaxed">রক্তদাতা তালিকা একটি যোগাযোগের মাধ্যম মাত্র — এই তালিকা দাতার প্রাপ্যতা বা চিকিৎসাগত উপযুক্ততার গ্যারান্টি দেয় না। রক্ত দেওয়ার আগে হাসপাতালে ক্রসম্যাচসহ প্রয়োজনীয় সব পরীক্ষা করে নিন এবং চিকিৎসকের পরামর্শ নিন।</p></section>
<section className="card mt-3"><h2 className="font-black">চাকরি, কেনাবেচা ও ভাড়া</h2><p className="mt-2 text-sm leading-relaxed">চাকরি ও কেনাবেচার তথ্য পোস্টদাতারা দেন; প্ল্যাটফর্ম নিয়োগদাতা বা বিক্রেতার সত্যতার গ্যারান্টি দিতে পারে না। যেকোনো লেনদেনের আগে নিজে যাচাই করুন, অগ্রিম অর্থ পাঠানোর ক্ষেত্রে বিশেষ সতর্ক থাকুন। মেয়াদ শেষ হয়ে যাওয়া পোস্টগুলোকে সেভাবে চিহ্নিত করা হয়।</p></section>
<section className="card mt-3"><h2 className="font-black">তথ্যের নির্ভরযোগ্যতা</h2><p className="mt-2 text-sm leading-relaxed">জরুরি নম্বর হিসেবে শুধু যাচাইকৃত জাতীয় নম্বর (৯৯৯, ১৬২৬৩, ৩৩৩) দেওয়া হয়। যেসব স্থানের আসল ছবি পাওয়া যায়নি সেখানে ইলাস্ট্রেশন ব্যবহার করে <b>“প্রতীকী ছবি (ইলাস্ট্রেশন)”</b> বলে স্পষ্ট লেবেল দেওয়া থাকে। তথ্যে ভুল চোখে পড়লে অভিযোগ পেজে জানান — যাচাই করে সংশোধন করা হবে।</p></section>
<section className="card mt-3"><h2 className="font-black">সেবা পরিবর্তন</h2><p className="mt-2 text-sm leading-relaxed">কর্তৃপক্ষ যেকোনো সময় সেবার যেকোনো অংশ পরিবর্তন বা বন্ধ করতে পারে। শর্তাবলী বদলালে এই পেজেই হালনাগাদ সংস্করণ প্রকাশ করা হবে।</p></section>
</main></Shell>; }
