import crypto from 'crypto'; import {DB_BACKEND,getFirebaseAdmin,readDBAsync,writeDBAsync,mutateDBAsync,id,now} from './db';
// ---- Visitor analytics (spec §33–67) ----
// COUNTING POLICY: one UNIQUE visitor per Asia/Dhaka calendar day. Identity = logged-in user id,
// else the server-issued `bk_vid` cookie (random, httpOnly). The dedupe key stored is
// sha256(identity|day) — irreversible, so daily docs can never reveal who visited, and a visitor
// refreshing / opening many tabs / navigating pages within the same day counts exactly once.
// /admin paths are never counted (tracker skips them too). Bot/crawler/monitor user-agents are
// excluded (isBotUA below — UA keywords only, no fingerprinting). Admins browsing the PUBLIC
// site count like everyone else but are tagged type:'ADMIN' in the raw log.
// CONCURRENCY: day/total/log writes run in ONE Firestore transaction (or under the db
// queue on the file backend via mutateDBAsync), so simultaneous first-visits cannot
// mis-count or double-count — the dedupe check and the increment commit atomically.
// STORAGE: Firestore collections bk_vdays/{YYYY-MM-DD} {count, seen:{sha256:true}} and
// bk_vtotal/main {total, since}; file backend mirrors the same shapes in db.vanalytics.
// RAW IP POLICY (§48): the `seen` hashes cannot be reversed to an IP or identity. Raw IPs live
// ONLY in bk_viplogs (db.vanalytics.logs in file mode) for security/abuse review, are served
// solely behind the analytics.ip.view permission, and are purged after the retention window —
// the aggregate counts (no IPs in them) live forever. IPs come only from platform proxy
// headers (x-forwarded-for first hop / x-real-ip), never from the request body.
export function parseUA(ua:string){ const s=ua.toLowerCase(); let device='ডেস্কটপ'; if(/ipad|tablet|playbook|silk/.test(s)||(/android/.test(s)&&!/mobile/.test(s))) device='ট্যাবলেট'; else if(/mobi|android|iphone|ipod|windows phone/.test(s)) device='মোবাইল'; let os='অন্যান্য'; if(/windows/.test(s)) os='Windows'; else if(/android/.test(s)) os='Android'; else if(/iphone|ipad|ipod/.test(s)) os='iOS'; else if(/mac os x|macintosh/.test(s)) os='macOS'; else if(/linux/.test(s)) os='Linux'; let browser='অন্যান্য'; if(/edg\//.test(s)) browser='Edge'; else if(/opr\/|opera/.test(s)) browser='Opera'; else if(/samsungbrowser/.test(s)) browser='Samsung Internet'; else if(/firefox|fxios/.test(s)) browser='Firefox'; else if(/chrome|crios/.test(s)) browser='Chrome'; else if(/safari/.test(s)) browser='Safari'; return {device,os,browser} }
const BOT_RE=/bot|crawler|crawling|spider|headless|phantom|pingdom|uptime|statuscake|gtmetrix|lighthouse|pagespeed|monitor|curl|wget|python-requests|httpclient/i;
export function isBotUA(ua:string){ return !ua||BOT_RE.test(ua); } // empty UA counts as automated
export function dhakaDay(d:Date=new Date()){ return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(d); }
const sha=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
async function fdb(){ const a=await getFirebaseAdmin(); return a.firestore(); }
function ensureV(db:any){ if(!db.vanalytics||typeof db.vanalytics!=='object'||Array.isArray(db.vanalytics)) db.vanalytics={days:{},total:0,since:null,logs:[]}; const v=db.vanalytics; if(!v.days||typeof v.days!=='object'||Array.isArray(v.days)) v.days={}; if(typeof v.total!=='number') v.total=0; if(!Array.isArray(v.logs)) v.logs=[]; return v; }
export async function recordVisit(o:{user:any,identity:string,ip:string,device:string,browser:string,os:string,country:string|null}):Promise<boolean>{ const day=dhakaDay(); const h=sha(o.identity+'|'+day); const log={id:id('vl'),ip:o.ip,day,at:now(),device:o.device,browser:o.browser,os:o.os,country:o.country||null,type:o.user?(['ADMIN','SUPER_ADMIN','MODERATOR'].includes(o.user.role)?'ADMIN':'USER'):'ANONYMOUS',...(o.user?{userId:o.user.id}:{})};
 if(DB_BACKEND==='firestore'){ const fs=await fdb(); const dref=fs.collection('bk_vdays').doc(day); const tref=fs.collection('bk_vtotal').doc('main'); const lref=fs.collection('bk_viplogs').doc(log.id); return fs.runTransaction(async(tx:any)=>{ const ds=await tx.get(dref); const d:any=ds.exists?ds.data():{count:0,seen:{}}; if(!d.seen||typeof d.seen!=='object') d.seen={}; if(d.seen[h]) return false; const ts=await tx.get(tref); const td:any=ts.exists?ts.data():{total:0,since:null}; d.seen[h]=true; d.count=(Number(d.count)||0)+1; tx.set(dref,d); tx.set(tref,{total:(Number(td.total)||0)+1,since:td.since||now()}); tx.set(lref,log); return true; }); }
 return mutateDBAsync((db:any)=>{ const v=ensureV(db); const d=v.days[day]||(v.days[day]={count:0,seen:{}}); if(d.seen[h]) return false; d.seen[h]=true; d.count=(Number(d.count)||0)+1; v.total=(Number(v.total)||0)+1; if(!v.since) v.since=now(); v.logs.unshift(log); return true; }); }
export async function getDailyMap():Promise<Record<string,number>>{ if(DB_BACKEND==='firestore'){ const fs=await fdb(); const snap=await fs.collection('bk_vdays').get(); const out:Record<string,number>={}; snap.forEach((doc:any)=>{ out[doc.id]=Number((doc.data()||{}).count)||0; }); return out; } const db=await readDBAsync(); const v=ensureV(db); const out:Record<string,number>={}; for(const k of Object.keys(v.days)) out[k]=Number((v.days[k]||{}).count)||0; return out; }
export async function getTotalRec():Promise<{total:number,since:string|null}>{ if(DB_BACKEND==='firestore'){ const fs=await fdb(); const s=await fs.collection('bk_vtotal').doc('main').get(); if(!s.exists) return {total:0,since:null}; const d:any=s.data(); return {total:Number(d.total)||0,since:d.since||null}; } const db=await readDBAsync(); const v=ensureV(db); return {total:Number(v.total)||0,since:v.since||null}; }
export async function getAnalyticsSummary(){ const days=await getDailyMap(); const tr=await getTotalRec(); const today=dhakaDay(); const ym=today.slice(0,7); const yr=today.slice(0,4); let month=0,year=0; for(const k of Object.keys(days)){ if(k.startsWith(ym)) month+=days[k]; if(k.startsWith(yr)) year+=days[k]; } const series=(n:number)=>Array.from({length:n},(_,i)=>{ const day=dhakaDay(new Date(Date.now()-(n-1-i)*864e5)); return {day,count:days[day]||0}; }); const months:Record<string,number>={}; for(const k of Object.keys(days)) months[k.slice(0,7)]=(months[k.slice(0,7)]||0)+days[k]; const monthly=Array.from({length:12},(_,i)=>{ const d=new Date(); d.setDate(1); d.setMonth(d.getMonth()-(11-i)); const key=d.toISOString().slice(0,7); return {ym:key,count:months[key]||0}; }); return {today:days[today]||0,month,year,total:tr.total,since:tr.since,last7:series(7),last30:series(30),monthly}; }
let _pubCache:{at:number,data:any}|null=null; // 60s in-memory aggregate cache (per instance) so
// the public counter/footer never becomes a database read on every page render (§62).
export async function getPublicStats(){ if(_pubCache&&Date.now()-_pubCache.at<60000) return _pubCache.data; const s=await getAnalyticsSummary(); const data={today:s.today,month:s.month,year:s.year,total:s.total}; _pubCache={at:Date.now(),data}; return data; }
export async function listIpLogs(f:{q?:string,type?:string,from?:string,to?:string,page?:number,pageSize?:number}){ let logs:any[]=[]; if(DB_BACKEND==='firestore'){ const fs=await fdb(); const snap=await fs.collection('bk_viplogs').orderBy('at','desc').limit(3000).get(); snap.forEach((doc:any)=>logs.push(doc.data())); } else { const db=await readDBAsync(); logs=ensureV(db).logs.slice(0,3000); }
 const q=String(f.q||'').trim(); const looksIp=/^\d{1,3}(\.\d{1,3}){0,3}$/.test(q); const out=logs.filter((l:any)=>(!f.type||l.type===f.type)&&(!f.from||l.day>=f.from)&&(!f.to||l.day<=f.to)&&(!q||(looksIp?l.ip===q:String(l.userId||'').toLowerCase().includes(q.toLowerCase())))); const total=out.length; const page=Math.max(1,Number(f.page)||1); const pageSize=Math.min(100,Math.max(1,Number(f.pageSize)||25)); return {logs:out.slice((page-1)*pageSize,page*pageSize),total,page,pageSize,pages:Math.max(1,Math.ceil(total/pageSize))}; }
export async function getRetentionDays():Promise<number>{ try{ const db=await readDBAsync(); const n=Number(db&&db.meta&&db.meta.ipLogRetentionDays); return n>=30&&n<=90?n:60; }catch{ return 60 } }
export async function setRetentionDays(n:number){ const db=await readDBAsync(); if(!db.meta||typeof db.meta!=='object'||Array.isArray(db.meta)) db.meta={}; db.meta.ipLogRetentionDays=n; await writeDBAsync(db); return n; }
export async function purgeOldIpLogs(retentionDays:number):Promise<number>{ const cutoff=dhakaDay(new Date(Date.now()-retentionDays*864e5)); if(DB_BACKEND==='firestore'){ const fs=await fdb(); const snap=await fs.collection('bk_viplogs').where('day','<',cutoff).limit(500).get(); if(snap.empty) return 0; const b=fs.batch(); let n=0; snap.forEach((doc:any)=>{ b.delete(doc.ref); n++; }); await b.commit(); return n; } const db=await readDBAsync(); const v=ensureV(db); const before=v.logs.length; v.logs=v.logs.filter((l:any)=>l.day>=cutoff); const n=before-v.logs.length; if(n>0) await writeDBAsync(db); return n; }
