// Universal CMS core (2026-10-09): schema definitions, the 22 built-in content types as DATA,
// schema-generated server validation, and defensive sanitizers so a malformed stored schema
// can never crash a public page. Collections content_types + contents ride the per-record
// store (lib/db HOT_COLLECTIONS) — never the legacy single document.
import {id,now} from './db'; import {FIELD_TYPES,CONTENT_STATUSES,STATUS_LABELS} from './cmsShared'; export {FIELD_TYPES,CONTENT_STATUSES,STATUS_LABELS};
export type CField={key:string,label:string,type:string,required:boolean,defaultValue:any,options:string[],order:number,showInCard:boolean,showInDetail:boolean};
const F=(key:string,label:string,type:string,o:any={}):CField=>({key,label,type,required:!!o.required,defaultValue:o.def??'',options:o.options||[],order:o.order??99,showInCard:!!o.card,showInDetail:o.detail!==false});
const CONTACT=[F('contactPhone','যোগাযোগ নম্বর','Phone',{order:80}),F('email','ইমেইল','Email',{order:81}),F('website','ওয়েবসাইট','URL',{order:82})];
// Type blueprints: [slug, nameBn, nameEn, icon, description, fields]
const T:any[]=[
['place','দর্শনীয় স্থান','Sightseeing Place','🏛️','দর্শনীয় স্থান ও পর্যটন আকর্ষণ',[F('history','বিস্তারিত ইতিহাস','Textarea',{order:1}),F('features','দর্শনীয় বৈশিষ্ট্য','Textarea',{order:2,card:1}),F('entryFee','প্রবেশমূল্য (জানা থাকলে)','Text',{order:3,card:1}),F('openingHours','খোলার সময়','Text',{order:4,card:1}),...CONTACT]],
['tourism-center','পর্যটনকেন্দ্র','Tourism Center','🎡','পর্যটনকেন্দ্র ও বিনোদন স্পট',[F('history','বিস্তারিত','Textarea',{order:1}),F('features','আকর্ষণ ও বৈশিষ্ট্য','Textarea',{order:2,card:1}),F('entryFee','প্রবেশমূল্য (জানা থাকলে)','Text',{order:3,card:1}),F('openingHours','খোলার সময়','Text',{order:4,card:1}),F('facilities','সুযোগ-সুবিধা','Textarea',{order:5}),...CONTACT]],
['school','স্কুল','School','🏫','প্রাথমিক ও মাধ্যমিক বিদ্যালয়',[F('establishedYear','প্রতিষ্ঠার সাল','Number',{order:1,card:1}),F('eiin','EIIN নম্বর','Text',{order:2}),F('institutionType','প্রতিষ্ঠানের ধরন','Select',{order:3,card:1,options:['সরকারি','বেসরকারি','এমপিওভুক্ত']}),F('principalName','প্রধান শিক্ষকের নাম','Text',{order:4}),F('principalInfo','প্রধান শিক্ষক সম্পর্কে','Textarea',{order:5}),...CONTACT]],
['college','কলেজ','College','🎓','উচ্চমাধ্যমিক ও ডিগ্রি কলেজ',[F('establishedYear','প্রতিষ্ঠার সাল','Number',{order:1,card:1}),F('eiin','EIIN নম্বর','Text',{order:2}),F('institutionType','প্রতিষ্ঠানের ধরন','Select',{order:3,card:1,options:['সরকারি','বেসরকারি','এমপিওভুক্ত']}),F('principalName','অধ্যক্ষের নাম','Text',{order:4}),...CONTACT]],
['university','বিশ্ববিদ্যালয়','University','🏛️','বিশ্ববিদ্যালয় ও উচ্চশিক্ষা প্রতিষ্ঠান',[F('establishedYear','প্রতিষ্ঠার সাল','Number',{order:1,card:1}),F('institutionType','প্রতিষ্ঠানের ধরন','Select',{order:2,card:1,options:['সরকারি','বেসরকারি']}),...CONTACT]],
['madrasa','মাদ্রাসা / শিক্ষাপ্রতিষ্ঠান','Madrasa / Institution','🕌','মাদ্রাসা ও অন্যান্য শিক্ষাপ্রতিষ্ঠান',[F('establishedYear','প্রতিষ্ঠার সাল','Number',{order:1,card:1}),F('eiin','EIIN নম্বর','Text',{order:2}),F('institutionType','প্রতিষ্ঠানের ধরন','Select',{order:3,card:1,options:['আলিয়া','কওমি','হাফেজিয়া','এবতেদায়ী','অন্যান্য']}),F('principalName','মুহতামিম / প্রধানের নাম','Text',{order:4}),...CONTACT]],
['hospital','হাসপাতাল','Hospital','🏥','হাসপাতাল ও বড় চিকিৎসা কেন্দ্র',[F('services','সেবার ধরন','Textarea',{order:1,card:1}),F('emergencyPhone','জরুরি যোগাযোগ (যাচাইকৃত)','Phone',{order:2,card:1}),F('openingHours','সেবার সময়','Text',{order:3,card:1}),...CONTACT]],
['clinic','ক্লিনিক','Clinic','🩺','ক্লিনিক ও ছোট চিকিৎসা কেন্দ্র',[F('services','সেবার ধরন','Textarea',{order:1,card:1}),F('emergencyPhone','জরুরি যোগাযোগ (যাচাইকৃত)','Phone',{order:2}),F('openingHours','খোলার সময়','Text',{order:3,card:1}),...CONTACT]],
['doctor','ডাক্তার','Doctor','👨‍⚕️','ডাক্তারের প্রোফাইল',[F('specialty','বিশেষজ্ঞতা','Select',{order:1,card:1,options:['মেডিসিন','শিশু','গাইনি','চক্ষু','দন্ত','হাড়-জোড়','চর্ম','নাক-কান-গলা','সার্জারি','হৃদরোগ','অন্যান্য']}),F('degree','ডিগ্রি','Text',{order:2}),F('chamber','চেম্বার','Text',{order:3,card:1}),F('visitingHours','রোগী দেখার সময়','Text',{order:4,card:1}),F('fee','ফি (৳)','Number',{order:5}),...CONTACT]],
['diagnostic-center','ডায়াগনস্টিক সেন্টার','Diagnostic Center','🔬','প্যাথলজি ও ডায়াগনস্টিক সেন্টার',[F('services','সেবার ধরন','Textarea',{order:1,card:1}),F('testList','উল্লেখযোগ্য পরীক্ষা','Textarea',{order:2}),F('openingHours','খোলার সময়','Text',{order:3,card:1}),...CONTACT]],
['govt-office','সরকারি অফিস','Government Office','🏢','সরকারি অফিস ও সেবা কেন্দ্র',[F('services','সেবাসমূহ','Textarea',{order:1,card:1}),F('officeHours','অফিস সময়','Text',{order:2,card:1}),F('headName','দায়িত্বপ্রাপ্ত কর্মকর্তা','Text',{order:3}),...CONTACT]],
['private-org','বেসরকারি প্রতিষ্ঠান','Private Organization','🏭','বেসরকারি প্রতিষ্ঠান ও সংস্থা',[F('services','সেবাসমূহ','Textarea',{order:1,card:1}),F('officeHours','অফিস সময়','Text',{order:2,card:1}),...CONTACT]],
['business','ব্যবসাপ্রতিষ্ঠান','Business','🏪','দোকান ও ব্যবসাপ্রতিষ্ঠান',[F('businessCategory','ব্যবসার ধরন','Select',{order:1,card:1,options:['খুচরা','পাইকারি','সেবা','উৎপাদন','অনলাইন','অন্যান্য']}),F('services','সেবার বিবরণ','Textarea',{order:2,card:1}),F('businessHours','ব্যবসার সময়','Text',{order:3,card:1}),...CONTACT]],
['restaurant','রেস্টুরেন্ট','Restaurant','🍽️','রেস্টুরেন্ট ও খাবারের দোকান',[F('cuisine','খাবারের ধরন','Text',{order:1,card:1}),F('menu','মেনু / বিশেষ খাবার','Textarea',{order:2,card:1}),F('priceRange','মূল্যস্তর','Select',{order:3,options:['৳','৳৳','৳৳৳']}),F('openingHours','খোলার সময়','Text',{order:4,card:1}),F('delivery','হোম ডেলিভারি আছে','Toggle',{order:5}),...CONTACT]],
['hotel','হোটেল','Hotel','🏨','হোটেল ও আবাসন',[F('roomTypes','রুমের ধরন ও ভাড়া','Textarea',{order:1,card:1}),F('priceRange','মূল্যস্তর','Select',{order:2,card:1,options:['৳','৳৳','৳৳৳']}),F('amenities','সুবিধাসমূহ','MultiSelect',{order:3,options:['ওয়াইফাই','এসি','পার্কিং','রেস্টুরেন্ট','গরম পানি']}),...CONTACT]],
['religious-cultural','ধর্মীয় ও সাংস্কৃতিক স্থান','Religious & Cultural Place','🛕','মসজিদ, মন্দির, মাজার ও সাংস্কৃতিক স্থান',[F('history','বিস্তারিত ইতিহাস','Textarea',{order:1}),F('features','বৈশিষ্ট্য','Textarea',{order:2,card:1}),F('festivals','উৎসব / অনুষ্ঠান','Textarea',{order:3}),F('openingHours','খোলার সময়','Text',{order:4,card:1}),...CONTACT]],
['historical-place','ঐতিহাসিক স্থান','Historical Place','🏺','ঐতিহাসিক স্থান ও নিদর্শন',[F('history','বিস্তারিত ইতিহাস','Textarea',{order:1,card:1}),F('features','বৈশিষ্ট্য','Textarea',{order:2}),F('era','আনুমানিক সাল / সময়কাল','Text',{order:3,card:1}),...CONTACT]],
['park-entertainment','পার্ক ও বিনোদনকেন্দ্র','Park & Entertainment','🌳','পার্ক, মাঠ ও বিনোদনকেন্দ্র',[F('features','আকর্ষণ ও বৈশিষ্ট্য','Textarea',{order:1,card:1}),F('entryFee','প্রবেশমূল্য (জানা থাকলে)','Text',{order:2,card:1}),F('openingHours','খোলার সময়','Text',{order:3,card:1}),F('rides','রাইড / আকর্ষণসমূহ','Textarea',{order:4}),...CONTACT]],
['transport-service','পরিবহনসেবা','Transport Service','🚌','বাস, নৌকা ও অন্যান্য পরিবহনসেবা',[F('routes','রুটসমূহ','Textarea',{order:1,card:1}),F('schedule','সময়সূচী','Textarea',{order:2,card:1}),F('fare','ভাড়া','Text',{order:3}),...CONTACT]],
['emergency-service','জরুরি সেবা','Emergency Service','🚨','জরুরি সেবা (ফায়ার, অ্যাম্বুলেন্স ইত্যাদি)',[F('servicePhone','জরুরি নম্বর','Phone',{order:1,card:1,required:true}),F('altPhone','বিকল্প নম্বর','Phone',{order:2}),F('availability','প্রাপ্যতা','Text',{order:3,card:1}),F('services','সেবার বিবরণ','Textarea',{order:4}),...CONTACT]],
['local-news','স্থানীয় সংবাদ / ঘোষণা','Local News / Notice','📰','স্থানীয় সংবাদ ও ঘোষণা',[F('newsDate','তারিখ','Date',{order:1,card:1}),F('importance','গুরুত্ব','Select',{order:2,card:1,options:['সাধারণ','গুরুত্বপূর্ণ','জরুরি']}),F('source','সূত্র','Text',{order:3})]],
['community-info','কমিউনিটি তথ্য','Community Info','👥','কমিউনিটি ও সামাজিক তথ্য',[F('details','বিস্তারিত','Textarea',{order:1,card:1}),...CONTACT]],
['other','অন্যান্য','Other','📁','অন্যান্য যেকোনো তথ্য',[F('details','বিস্তারিত','Textarea',{order:1,card:1}),...CONTACT]],
];
export function buildBuiltinTypes(userId='system'){ const t=now(); return T.map((x:any,i:number)=>({id:id('ct'),slug:x[0],nameBn:x[1],nameEn:x[2],icon:x[3],description:x[4],publicListing:true,enabled:true,order:i+1,fields:x[5],cardFields:x[5].filter((f:CField)=>f.showInCard).map((f:CField)=>f.key),schemaVersion:1,builtin:true,createdBy:userId,createdAt:t,updatedAt:t})); }
// Insert the 22 built-in types exactly once (when the collection is empty). Mutates db in
// place; the caller persists through mutateDBAsync. Returns true when seeding happened.
export function seedBuiltinTypesIfEmpty(db:any,userId='system'){ if(Array.isArray(db.content_types)&&db.content_types.length===0){ db.content_types.push(...buildBuiltinTypes(userId)); return true; } return false; }
export function slugify(s:any){ let v=String(s||'').toLowerCase().trim().replace(/[\s_]+/g,'-').replace(/[^a-z0-9\u0980-\u09FF-]+/g,'').replace(/-+/g,'-').replace(/^-|-$/g,''); return v||'item'; }
export const SLUG_OK=(s:string)=>/^[a-z0-9\u0980-\u09FF]+(-[a-z0-9\u0980-\u09FF]+)*$/.test(s);
export function contentTitle(c:any){ return (c&&(c.titleBn||c.titleEn))||'(শিরোনামহীন)'; }
const cap=(v:any,n:number)=>String(v??'').slice(0,n);
// Defensive coercion: whatever is stored, public/admin renderers only see this safe shape.
export function sanitizeField(f:any):CField|null{ if(!f||typeof f!=='object'||typeof f.key!=='string'||!/^[a-zA-Z][a-zA-Z0-9_]*$/.test(f.key)||!FIELD_TYPES.includes(f.type)) return null; return {key:f.key,label:cap(f.label||f.key,80),type:f.type,required:!!f.required,defaultValue:f.defaultValue??'',options:Array.isArray(f.options)?f.options.map((o:any)=>cap(o,60)).slice(0,50):[],order:Number.isFinite(+f.order)?+f.order:99,showInCard:!!f.showInCard,showInDetail:f.showInDetail!==false}; }
export function sanitizeContentType(t:any):any|null{ if(!t||typeof t!=='object'||typeof t.slug!=='string'||!t.slug) return null; const seen=new Set<string>(); const fields=(Array.isArray(t.fields)?t.fields:[]).map(sanitizeField).filter((f:any)=>{ if(!f||seen.has(f.key)) return false; seen.add(f.key); return true; }).sort((a:any,b:any)=>a.order-b.order); return {id:String(t.id||''),slug:t.slug,nameBn:cap(t.nameBn,120),nameEn:cap(t.nameEn,120),description:cap(t.description,500),icon:cap(t.icon||'📁',8),publicListing:!!t.publicListing,enabled:t.enabled!==false,order:Number.isFinite(+t.order)?+t.order:99,fields,cardFields:Array.isArray(t.cardFields)?t.cardFields.filter((k:any)=>seen.has(String(k))):fields.filter((f:any)=>f.showInCard).map((f:any)=>f.key),schemaVersion:Number(t.schemaVersion)||1,builtin:!!t.builtin,createdBy:String(t.createdBy||''),createdAt:String(t.createdAt||''),updatedAt:String(t.updatedAt||'')}; }
export function sanitizeContent(c:any):any|null{ if(!c||typeof c!=='object'||!c.id||!c.typeSlug) return null; const st=CONTENT_STATUSES.includes(c.status)?c.status:'DRAFT'; const loc=(c.location&&typeof c.location==='object')?c.location:{}; const seo=(c.seo&&typeof c.seo==='object')?c.seo:{}; return {id:String(c.id),typeSlug:String(c.typeSlug),slug:String(c.slug||''),titleBn:cap(c.titleBn,200),titleEn:cap(c.titleEn,200),shortDesc:cap(c.shortDesc,500),fullDesc:cap(c.fullDesc,20000),categorySlug:cap(c.categorySlug||'',60),subcategorySlug:cap(c.subcategorySlug||'',60),tags:Array.isArray(c.tags)?c.tags.map((t:any)=>cap(t,40)).slice(0,20):[],featured:!!c.featured,status:st,fields:(c.fields&&typeof c.fields==='object'&&!Array.isArray(c.fields))?c.fields:{},images:Array.isArray(c.images)?c.images.filter((i:any)=>i&&typeof i.url==='string').map((i:any)=>({url:cap(i.url,500),caption:cap(i.caption,200),alt:cap(i.alt,200),featured:!!i.featured})).slice(0,20):[],location:{district:cap(loc.district,80),upazila:cap(loc.upazila,80),union:cap(loc.union,80),area:cap(loc.area,120),address:cap(loc.address,300),mapsUrl:cap(loc.mapsUrl,500),lat:(loc.lat===null||loc.lat===undefined||loc.lat==='')?null:Number(loc.lat),lng:(loc.lng===null||loc.lng===undefined||loc.lng==='')?null:Number(loc.lng)},seo:{title:cap(seo.title,200),description:cap(seo.description,400),ogImage:cap(seo.ogImage,500),canonical:cap(seo.canonical,500)},createdBy:String(c.createdBy||''),updatedBy:String(c.updatedBy||''),createdAt:String(c.createdAt||''),updatedAt:String(c.updatedAt||''),publishedAt:c.publishedAt?String(c.publishedAt):null,schemaVersion:Number(c.schemaVersion)||1}; }
const isUrl=(s:string)=>{ try{ const u=new URL(s); return u.protocol==='http:'||u.protocol==='https:'; }catch{ return false; } };
// Schema-generated validation for a content create/update body. Returns {data} or {error,message}.
export function validateContentFields(type:any,raw:any){ const fields:any={}; const src=(raw&&typeof raw==='object'&&!Array.isArray(raw))?raw:{}; for(const f of type.fields){ let v=src[f.key]; if(v===undefined||v===null||v===''){ if(f.required) return {error:'FIELD_REQUIRED',message:`"${f.label}" আবশ্যক`}; if(f.defaultValue!==''&&f.defaultValue!==undefined) fields[f.key]=f.defaultValue; continue; } switch(f.type){ case 'Number':{ const n=Number(v); if(!Number.isFinite(n)) return {error:'INVALID_FIELD',message:`"${f.label}" সংখ্যা হতে হবে`}; fields[f.key]=n; break; } case 'Email':{ v=cap(v,120).trim(); if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v)) return {error:'INVALID_FIELD',message:`"${f.label}" সঠিক ইমেইল নয়`}; fields[f.key]=v; break; } case 'Phone':{ v=cap(v,30).trim(); if(!/^\+?[0-9][0-9\s-]{5,}$/.test(v)) return {error:'INVALID_FIELD',message:`"${f.label}" সঠিক ফোন নম্বর নয়`}; fields[f.key]=v; break; } case 'URL': case 'GoogleMapsURL':{ v=cap(v,500).trim(); if(!isUrl(v)) return {error:'INVALID_FIELD',message:`"${f.label}" সঠিক লিংক (URL) নয়`}; fields[f.key]=v; break; } case 'Date':{ v=cap(v,10); if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v))) return {error:'INVALID_FIELD',message:`"${f.label}" সঠিক তারিখ নয়`}; fields[f.key]=v; break; } case 'Time':{ v=cap(v,5); if(!/^\d{2}:\d{2}$/.test(v)) return {error:'INVALID_FIELD',message:`"${f.label}" সঠিক সময় নয়`}; fields[f.key]=v; break; } case 'Select':{ v=cap(v,60); if(f.options.length&&!f.options.includes(v)) return {error:'INVALID_FIELD',message:`"${f.label}" তালিকা থেকে বেছে নিন`}; fields[f.key]=v; break; } case 'MultiSelect':{ const arr=Array.isArray(v)?v.map((x:any)=>cap(x,60)):[]; if(f.options.length&&arr.some((x:string)=>!f.options.includes(x))) return {error:'INVALID_FIELD',message:`"${f.label}" তালিকা থেকে বেছে নিন`}; fields[f.key]=arr.slice(0,30); break; } case 'Checkbox': case 'Toggle':{ fields[f.key]=!!v; break; } case 'Image': case 'File':{ v=cap(v,500).trim(); if(v&&!(v.startsWith('/api/uploads/')||isUrl(v))) return {error:'INVALID_FIELD',message:`"${f.label}" সঠিক ফাইল/ছবি নয়`}; fields[f.key]=v; break; } case 'MultipleImages':{ const arr=Array.isArray(v)?v.map((x:any)=>cap(x,500)).filter((x:string)=>x.startsWith('/api/uploads/')||isUrl(x)):[]; fields[f.key]=arr.slice(0,20); break; } case 'Location':{ fields[f.key]=cap(v,300); break; } case 'RichText':{ fields[f.key]=cap(v,20000); break; } default:{ fields[f.key]=cap(v,f.type==='Textarea'?5000:300); } } } return {fields}; }
export function validateContentBody(type:any,b:any,db:any,selfId=''){ const titleBn=cap(b.titleBn,200).trim(), titleEn=cap(b.titleEn,200).trim(); if(!titleBn&&!titleEn) return {error:'CMS_TITLE_REQUIRED',message:'অন্তত একটি শিরোনাম (বাংলা বা ইংরেজি) আবশ্যক'}; const slug=cap(b.slug,120).trim()?slugify(b.slug):slugify(titleBn||titleEn); if(!SLUG_OK(slug)) return {error:'INVALID_SLUG',message:'Slug সঠিক নয় (ছোট হাতের অক্ষর, সংখ্যা, বাংলা ও হাইফেন ব্যবহার করুন)'}; if((db.contents||[]).some((c:any)=>c.typeSlug===type.slug&&c.slug===slug&&c.id!==selfId)) return {error:'SLUG_TAKEN',message:'এই টাইপে একই slug আগেই আছে — অন্য slug দিন'}; const fv:any=validateContentFields(type,b.fields||{}); if(fv.error) return fv; const images=(Array.isArray(b.images)?b.images:[]).filter((i:any)=>i&&typeof i.url==='string'&&(i.url.startsWith('/api/uploads/')||isUrl(i.url))).map((i:any)=>({url:cap(i.url,500),caption:cap(i.caption,200),alt:cap(i.alt,200),featured:!!i.featured})).slice(0,20); let featSeen=false; for(const i of images){ if(i.featured){ if(featSeen) i.featured=false; featSeen=true; } } const loc=(b.location&&typeof b.location==='object')?b.location:{}; const lat=(loc.lat===''||loc.lat===null||loc.lat===undefined)?null:Number(loc.lat), lng=(loc.lng===''||loc.lng===null||loc.lng===undefined)?null:Number(loc.lng); if(lat!==null&&(!Number.isFinite(lat)||lat<-90||lat>90)) return {error:'INVALID_FIELD',message:'Latitude সঠিক নয়'}; if(lng!==null&&(!Number.isFinite(lng)||lng<-180||lng>180)) return {error:'INVALID_FIELD',message:'Longitude সঠিক নয়'}; if(loc.mapsUrl&&!isUrl(String(loc.mapsUrl))) return {error:'INVALID_FIELD',message:'Google Maps লিংক সঠিক নয়'}; const seo=(b.seo&&typeof b.seo==='object')?b.seo:{}; return {data:{titleBn,titleEn,slug,shortDesc:cap(b.shortDesc,500),fullDesc:cap(b.fullDesc,20000),categorySlug:cap(b.categorySlug||'',60),subcategorySlug:cap(b.subcategorySlug||'',60),tags:(Array.isArray(b.tags)?b.tags:(typeof b.tags==='string'?b.tags.split(','):[])).map((t:any)=>cap(t,40).trim()).filter(Boolean).slice(0,20),featured:!!b.featured,fields:fv.fields,images,location:{district:cap(loc.district,80),upazila:cap(loc.upazila,80),union:cap(loc.union,80),area:cap(loc.area,120),address:cap(loc.address,300),mapsUrl:cap(loc.mapsUrl,500),lat,lng},seo:{title:cap(seo.title,200),description:cap(seo.description,400),ogImage:cap(seo.ogImage,500),canonical:cap(seo.canonical,500)}}}; }
// Type-builder validation. Returns {data} or {error,message}.
export function validateTypeBody(b:any,db:any,selfId=''){ const nameBn=cap(b.nameBn,120).trim(), nameEn=cap(b.nameEn,120).trim(); if(!nameBn&&!nameEn) return {error:'NAME_REQUIRED',message:'টাইপের নাম (বাংলা বা ইংরেজি) আবশ্যক'}; const slug=slugify(b.slug||nameEn||nameBn); if(!SLUG_OK(slug)) return {error:'INVALID_SLUG',message:'Slug সঠিক নয়'}; if((db.content_types||[]).some((t:any)=>t.slug===slug&&t.id!==selfId)) return {error:'SLUG_TAKEN',message:'এই slug-এ আগেই একটি কনটেন্ট টাইপ আছে'}; const seen=new Set<string>(); const fields:any[]=[]; for(const raw of (Array.isArray(b.fields)?b.fields:[])){ const f=sanitizeField(raw); if(!f) return {error:'INVALID_FIELD',message:'একটি ফিল্ড সঠিক নয় (key ছোট হাতের ইংরেজি অক্ষর দিয়ে শুরু হতে হবে, type তালিকা থেকে নিন)'}; if(seen.has(f.key)) return {error:'INVALID_FIELD',message:`ফিল্ড key "${f.key}" দুইবার ব্যবহার হয়েছে`}; seen.add(f.key); fields.push(f); } fields.sort((a,b2)=>a.order-b2.order); return {data:{slug,nameBn,nameEn,description:cap(b.description,500),icon:cap(b.icon||'📁',8)||'📁',publicListing:!!b.publicListing,enabled:b.enabled!==false,order:Number.isFinite(+b.order)?+b.order:99,fields,cardFields:fields.filter((f:any)=>f.showInCard).map((f:any)=>f.key),schemaVersion:Math.max(1,(Number(b.schemaVersion)||1))}}; }
export function locationText(c:any){ const l=c.location||{}; return [l.area,l.union,l.upazila,l.district].filter(Boolean).join(', '); }
export function featuredImage(c:any){ const im=(c.images||[]).find((i:any)=>i.featured)||(c.images||[])[0]; return im||null; }
export function fieldDisplay(f:CField,v:any):string{ if(v===undefined||v===null||v==='') return ''; if(Array.isArray(v)) return v.join(', '); if(typeof v==='boolean') return v?'হ্যাঁ':'না'; return String(v); }
export function isPublishedVisible(c:any,t:any){ return !!c&&!!t&&c.status==='PUBLISHED'&&t.enabled&&t.publicListing; }
