import {bnNorm} from './search'; import {isExpired,expiryOf} from './expiry';
// ---- Content Health Monitor (Wave 2) ----
// A READ-ONLY scan over the real records (posts, CMS contents, legacy jobs, doctors,
// post reports). It only ever FLAGS issues for a human to review — it never edits,
// hides or deletes anything. Deterministic findings (a date has passed, a field is
// empty) need no label; heuristic ones (possible duplicates) carry an explicit
// confidence: নিশ্চিত = same normalized title AND same area, সম্ভাব্য = same title only.
export type HealthRow={title:string,detail:string,href?:string,adminHref?:string,conf?:'নিশ্চিত'|'সম্ভাব্য'};
export type HealthSection={key:string,label:string,icon:string,total:number,rows:HealthRow[]};
const CAP=25; const daysAgo=(iso:any)=>{ const t=Date.parse(String(iso||'')); return Number.isFinite(t)?Math.floor((Date.now()-t)/864e5):0; };
export function scanContentHealth(db:any):HealthSection[]{ const S:HealthSection[]=[]; const add=(key:string,label:string,icon:string,rows:HealthRow[])=>{ if(rows.length) S.push({key,label,icon,total:rows.length,rows:rows.slice(0,CAP)}); };
 const posts=(db.posts||[]).filter((p:any)=>p&&p.id); const contents=(db.contents||[]).filter((c:any)=>c&&c.id); const types:any={}; (db.content_types||[]).forEach((t:any)=>{ if(t&&t.slug) types[t.slug]=t; }); const tName=(c:any)=>(types[c.typeSlug]&&(types[c.typeSlug].nameBn||types[c.typeSlug].nameEn))||c.typeSlug; const cTitle=(c:any)=>c.titleBn||c.titleEn||'(শিরোনামহীন)'; const cAdmin='/admin/content';
 // 1) Expired listings still carrying an APPROVED / published face (computed, never mutated).
 const exp:HealthRow[]=[]; posts.filter((p:any)=>p.status==='APPROVED'&&isExpired(p)).forEach((p:any)=>exp.push({title:p.title||'(শিরোনামহীন)',detail:'মেয়াদ শেষ: '+expiryOf(p),href:'/post/'+p.id,adminHref:'/admin/moderation'})); (db.jobs||[]).filter((j:any)=>isExpired(j)).forEach((j:any)=>exp.push({title:j.title||'চাকরি',detail:'চাকরির মেয়াদ শেষ: '+expiryOf(j)+(j.company?' • '+j.company:''),href:'/jobs'})); add('expired','মেয়াদোত্তীর্ণ লিস্টিং','⏰',exp);
 // 2) Missing featured image.
 const noImg:HealthRow[]=[]; posts.filter((p:any)=>p.status==='APPROVED'&&!p.image).forEach((p:any)=>noImg.push({title:p.title||'(শিরোনামহীন)',detail:'পোস্টে কোনো ছবি নেই',href:'/post/'+p.id,adminHref:'/admin/moderation'})); contents.filter((c:any)=>c.status==='PUBLISHED'&&!(c.images||[]).length).forEach((c:any)=>noImg.push({title:cTitle(c),detail:tName(c)+' — কোনো ছবি নেই',href:'/content/'+c.typeSlug+'/'+c.slug,adminHref:cAdmin})); add('noimage','ছবি নেই','🖼️',noImg);
 // 3) Missing required-ish fields (contact / area / description), judged per record kind.
 const miss:HealthRow[]=[]; posts.filter((p:any)=>p.status==='APPROVED').forEach((p:any)=>{ const m:string[]=[]; if(!p.phone&&!p.whatsapp) m.push('যোগাযোগের নম্বর'); if(!String(p.location||'').trim()) m.push('এলাকা'); if(!String(p.desc||'').trim()) m.push('বিবরণ'); if(m.length) miss.push({title:p.title||'(শিরোনামহীন)',detail:'নেই: '+m.join(', '),href:'/post/'+p.id,adminHref:'/admin/moderation'}); }); contents.filter((c:any)=>c.status==='PUBLISHED').forEach((c:any)=>{ const m:string[]=[]; if(!String(c.shortDesc||'').trim()&&!String(c.fullDesc||'').trim()) m.push('বিবরণ'); const l=c.location||{}; if(!String(l.area||'').trim()&&!String(l.address||'').trim()) m.push('এলাকা/ঠিকানা'); const t=types[c.typeSlug]; if(t&&(t.fields||[]).some((f:any)=>f.key==='contactPhone')&&!String((c.fields||{}).contactPhone||'').trim()) m.push('যোগাযোগ নম্বর'); if(m.length) miss.push({title:cTitle(c),detail:tName(c)+' — নেই: '+m.join(', '),href:'/content/'+c.typeSlug+'/'+c.slug,adminHref:cAdmin}); }); add('missing','গুরুত্বপূর্ণ তথ্য অসম্পূর্ণ','📝',miss);
 // 4) Near-duplicate titles (heuristic → confidence labelled).
 const dup:HealthRow[]=[]; const grp=(items:any[],key:(x:any)=>string)=>{ const m=new Map<string,any[]>(); items.forEach((x:any)=>{ const k=key(x); if(!k) return; const a=m.get(k)||[]; a.push(x); m.set(k,a); }); return Array.from(m.values()).filter(a=>a.length>1); };
 grp(posts.filter((p:any)=>p.status==='APPROVED'),(p:any)=>bnNorm(p.title)).forEach((g:any[])=>{ const sameLoc=new Set(g.map((p:any)=>bnNorm(p.location))).size===1; dup.push({title:g[0].title||'(শিরোনামহীন)',detail:`একই শিরোনামে ${g.length}টি লাইভ পোস্ট`+(sameLoc?' (একই এলাকা)':' (ভিন্ন এলাকা)'),href:'/post/'+g[0].id,adminHref:'/admin/moderation',conf:sameLoc?'নিশ্চিত':'সম্ভাব্য'}); });
 grp(contents.filter((c:any)=>c.status==='PUBLISHED'),(c:any)=>c.typeSlug+'|'+bnNorm(c.titleBn||c.titleEn)).forEach((g:any[])=>{ const sameArea=new Set(g.map((c:any)=>bnNorm((c.location||{}).area))).size===1; dup.push({title:cTitle(g[0]),detail:`${tName(g[0])} — একই শিরোনামে ${g.length}টি`+(sameArea?' (একই এলাকা)':' (ভিন্ন এলাকা)'),href:'/content/'+g[0].typeSlug+'/'+g[0].slug,adminHref:cAdmin,conf:sameArea?'নিশ্চিত':'সম্ভাব্য'}); }); add('dup','সম্ভাব্য ডুপ্লিকেট','🧬',dup);
 // 5) Published contents that can never appear on the map (no coords, no maps link either).
 const noMap:HealthRow[]=[]; contents.filter((c:any)=>c.status==='PUBLISHED').forEach((c:any)=>{ const l=c.location||{}; const lat=l.lat===null||l.lat===undefined||l.lat===''?null:Number(l.lat); const lng=l.lng===null||l.lng===undefined||l.lng===''?null:Number(l.lng); if(!(Number.isFinite(lat)&&Number.isFinite(lng))&&!String(l.mapsUrl||'').trim()) noMap.push({title:cTitle(c),detail:tName(c)+' — স্থানাঙ্ক নেই, Google Maps লিংকও নেই',href:'/content/'+c.typeSlug+'/'+c.slug,adminHref:cAdmin}); }); add('nomap','মানচিত্রে দেখানো যাবে না','🗺️',noMap);
 // 6) Contents stuck in PENDING review for over a week.
 const stale:HealthRow[]=[]; contents.filter((c:any)=>c.status==='PENDING'&&daysAgo(c.createdAt)>7).forEach((c:any)=>stale.push({title:cTitle(c),detail:`${tName(c)} — ${daysAgo(c.createdAt)} দিন ধরে প্রকাশের অপেক্ষায়`,adminHref:cAdmin})); add('stale','দীর্ঘদিন পেন্ডিং কন্টেন্ট','⌛',stale);
 // 7) Posts drawing repeated OPEN reports (reports collection written by /api/posts/report).
 const rep:HealthRow[]=[]; const byPost=new Map<string,number>(); (db.reports||[]).forEach((r:any)=>{ if(r&&r.postId&&(!r.status||r.status==='OPEN')) byPost.set(r.postId,(byPost.get(r.postId)||0)+1); }); byPost.forEach((n,pid)=>{ if(n>=3){ const p=posts.find((x:any)=>x.id===pid); rep.push({title:(p&&p.title)||pid,detail:`${n}টি খোলা রিপোর্ট`,href:p?'/post/'+pid:undefined,adminHref:'/admin/moderation'}); } }); add('reports','বেশি রিপোর্ট পাওয়া পোস্ট','🚩',rep);
 // 8) Doctors missing the basics a visitor needs (specialty / where they sit).
 const docs:HealthRow[]=[]; (db.doctors||[]).forEach((d:any)=>{ const m:string[]=[]; if(!String(d.specialty||'').trim()) m.push('বিশেষজ্ঞতা'); if(!String(d.chamber||'').trim()&&!String(d.address||'').trim()) m.push('চেম্বার/ঠিকানা'); if(m.length) docs.push({title:d.name||'ডাক্তার',detail:'নেই: '+m.join(', '),href:'/doctors',adminHref:'/admin/doctors'}); }); add('doctors','ডাক্তার এন্ট্রি অসম্পূর্ণ','🩺',docs);
 return S; }
