import fs from 'fs'; import path from 'path'; import crypto from 'crypto';
const ON_VERCEL=!!(process.env.VERCEL||process.env.NETLIFY||process.env.AWS_LAMBDA_FUNCTION_NAME);
export const DB_PATH=process.env.DB_PATH||(ON_VERCEL?'/tmp/boalkhali-db.json':path.join(process.cwd(),'data','db.json'));
export const UPLOAD_DIR=process.env.UPLOAD_DIR||(ON_VERCEL?'/tmp/boalkhali-uploads':path.join(process.cwd(),'public','uploads'));
export const UPLOAD_QUOTA_BYTES=Math.floor((Number(process.env.UPLOAD_QUOTA_GB)||5)*1024*1024*1024); // posting uploads quota: 5 GB (user, 2026-10-08)
// ---- DB backend selection (2026-10-08): Firestore when all 3 service-account env vars are set, else local file ----
// Firestore stores the ENTIRE DB as one JSON string in doc bk_state/main (~22KB today; Firestore doc limit 1MB — revisit if state grows past ~800KB).
export const DB_BACKEND:'firestore'|'file'=(process.env.FIREBASE_PROJECT_ID&&process.env.FIREBASE_CLIENT_EMAIL&&process.env.FIREBASE_PRIVATE_KEY)?'firestore':'file';
let _fsDb:any=null; let _fsInit:Promise<any>|null=null; let _fsCache:{db:any,at:number}|null=null; const FS_TTL_MS=3000;
async function firebaseAdmin():Promise<any>{ try{ const mod:any=await import('firebase-admin'); const admin=mod.default||mod; if(!admin.apps.length){ admin.initializeApp({credential:admin.credential.cert({projectId:process.env.FIREBASE_PROJECT_ID as string,clientEmail:process.env.FIREBASE_CLIENT_EMAIL as string,privateKey:(process.env.FIREBASE_PRIVATE_KEY as string).replace(/\\n/g,'\n')})}); } return admin; }catch(e:any){ throw new Error('FIRESTORE_INIT_FAILED: '+(e?.message||e)); } }
export async function getFirebaseAdmin():Promise<any>{ if(DB_BACKEND!=='firestore') throw new Error('FIREBASE_NOT_CONFIGURED'); return firebaseAdmin(); }
async function firestoreDB():Promise<any>{ if(_fsDb) return _fsDb; if(_fsInit) return _fsInit; _fsInit=(async()=>{ const admin=await firebaseAdmin(); _fsDb=admin.firestore(); return _fsDb; })(); return _fsInit; }
export function uploadUsageBytes(){ try{ return fs.readdirSync(UPLOAD_DIR).reduce((a,f)=>{try{return a+fs.statSync(path.join(UPLOAD_DIR,f)).size}catch{return a}},0);}catch{return 0} }
export type Role='CITIZEN'|'BUSINESS'|'SERVICE_PROVIDER'|'MODERATOR'|'ADMIN'|'SUPER_ADMIN';
export function id(p='id'){return p+'_'+crypto.randomBytes(6).toString('hex')}
export function now(){return new Date().toISOString()}
export const CATEGORIES=[
['house','বাসা ভাড়া','Home','#0a7a54','বাসা / মেস / দোকান'],['market','বাই-সেল','ShoppingBag','#2563eb','মোবাইল / আসবাব / পণ্য'],['doctor','ডাক্তার','Stethoscope','#0d9488','চিকিৎসা সেবা'],['blood','রক্তদান','Droplet','#e11d48','জরুরি রক্ত'],['secret','গোপন তথ্য','ShieldAlert','#dc2626','১০০% গোপনীয় রিপোর্ট'],['food','রেস্টুরেন্ট ও খাবার','UtensilsCrossed','#ea580c','বোয়ালখালীর স্পেশাল স্বাদ'],['transport','বাস ও ট্রেন','Bus','#059669','যাতায়াত ও সময়সূচী'],['jobs','চাকরি ও নিয়োগ','Briefcase','#7c3aed','চাকরি'],['lost','হারানো ও প্রাপ্তি','PackageSearch','#c2410c','হারানো জিনিস'],['legal','আইনগত সহায়তা','Scale','#334155','আইনি সেবা'],['event','অনুষ্ঠান ও ডেকোর','PartyPopper','#a21caf','ইভেন্ট'],['electrician','ইলেকট্রিশিয়ান','Zap','#ca8a04','ওয়্যারিং / ফ্যান / লাইন'],['plumber','প্লাম্বার','Wrench','#0891b2','স্যানিটারি / পাইপলাইন'],['ac','এসি/ফ্রিজ','Wind','#0284c7','সার্ভিসিং / গ্যাস চার্জ'],['driver','ড্রাইভার','Car','#6d28d9','ব্যক্তিগত / রেন্টাল কার'],['tutor','গৃহশিক্ষক','BookOpen','#9333ea','টিউশন / কোচিং'],['vet','পশু চিকিৎসক','PawPrint','#db2777','প্রাণী ও খামার সেবা'],['mason','রাজমিস্ত্রি','Hammer','#b45309','বাড়ি ও কনস্ট্রাকশন'],['mobile','মোবাইল মেকার','Smartphone','#1d4ed8','সার্ভিসিং ও রিপেয়ার']
].map((c,i)=>({id:id('cat'),slug:c[0],name:c[1],icon:c[2],color:c[3],desc:c[4],order:i+1,enabled:true,subcategories:[]}));
export const LOCATIONS=['কধুরখীল','বোয়ালখালী বাজার','বোয়ালখালী বাস স্ট্যান্ড','কালুরঘাট রোড','চৌমুহনী বাজার','বোয়ালখালী সুপার মার্কেট','কধুরখীল মোড়','কালুরঘাট মোড়','ওয়ার্ড ১','ওয়ার্ড ২'].map((n,i)=>({id:id('loc'),name:n,area:n,road:'',landmark:'',lat:22.382+ i*0.001,lng:91.921+i*0.001}));
function seedDB(){
 const adminEmail=(process.env.ADMIN_EMAIL||'admin@boalkhali.local').toLowerCase();
 const hash=(pw:string)=>{const s=crypto.randomBytes(16).toString('hex');const h=crypto.scryptSync(pw,s,64).toString('hex');return s+':'+h};
 const db:any={users:[{id:'u_owner',name:'MD. Habibur Rahman',email:'habiburrahman962540@gmail.com',passwordHash:hash('OwnerDemo123!'),role:'SUPER_ADMIN',membership:'PREMIUM CITIZEN',verified:true,phone:'',area:'বোয়ালখালী',address:'বোয়ালখালী, বাংলাদেশ',privacyMode:false,createdAt:now(),totalPosts:1,publishedPosts:1},{id:'u_admin',name:'Admin',email:adminEmail,passwordHash:hash(process.env.ADMIN_PASSWORD||'admin'),role:'ADMIN',membership:'PREMIUM CITIZEN',verified:true,createdAt:now(),totalPosts:0,publishedPosts:0},{id:'u_citizen',name:'Test Citizen',email:'citizen@boalkhali.local',passwordHash:hash('Citizen123!'),role:'CITIZEN',membership:'FREE',verified:true,createdAt:now(),totalPosts:0,publishedPosts:0}],roles:['CITIZEN','BUSINESS','SERVICE_PROVIDER','MODERATOR','ADMIN','SUPER_ADMIN'],categories:CATEGORIES,subcategories:[],locations:LOCATIONS,feature_flags:CATEGORIES.map(c=>({categorySlug:c.slug,enabled:true,updatedAt:now()})),posts:[],post_images:[],saved_posts:[],restaurants:[],menus:[],doctors:[],blood_donors:[],blood_requests:[],jobs:[],services:[],service_providers:[],lost_found:[],complaints:[],secret_reports:[],emergency_alerts:[],announcements:[{id:id('ann'),title:'স্বাগতম! আমরা আছি আপনার পাশে',body:'বোয়ালখালী কানেক্টে স্বাগতম',active:true,createdAt:now()}],notifications:[],advertisements:[],memberships:[{id:id('mem'),userId:'u_owner',plan:'PREMIUM CITIZEN',status:'ACTIVE',createdAt:now()}],reviews:[],transport_routes:[{id:id('tr'),type:'train',name:'কর্ণফুলী এক্সপ্রেস',route:'বোয়ালখালী → চট্টগ্রাম',time:'08:00',station:'বোয়ালখালী বাস স্ট্যান্ড'},{id:id('tr'),type:'bus',name:'বোয়ালখালী → চট্টগ্রাম বাস',route:'বোয়ালখালী → চট্টগ্রাম',time:'07:30',station:'বাস টার্মিনাল'}],transport_schedules:[],audit_logs:[],system_metrics:[],sessions:[],tokens:[]};
 const P=(o:any)=>({views:0,createdAt:now(),status:'APPROVED',verified:false,promoted:false,...o});
 db.posts.push(P({id:'p_bike',userId:'u_owner',categorySlug:'market',title:'Bajaj Discover 125cc ডিস্ক ব্রেক মোটরসাইকেল',desc:'ভালো কন্ডিশন, সব কাগজ আপডেট',price:88000,location:'বোয়ালখালী বাজার, বোয়ালখালী',landmark:'বোয়ালখালী বাজার',phone:'01712445566',whatsapp:'01712445566',promoted:true,image:'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800'}));
 db.posts.push(P({id:'p_phone',userId:'u_owner',categorySlug:'market',title:'Redmi Note 12 Pro (8GB/128GB) স্মার্টফোন',desc:'ফুল বক্স, অল্প ব্যবহৃত',price:16500,location:'বোয়ালখালী সুপার মার্কেট, বোয়ালখালী',phone:'01712445566',image:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800'}));
 db.posts.push(P({id:'p_house',userId:'u_citizen',categorySlug:'house',title:'কধুরখীল মোড়ে ৩ রুমের ফ্যামিলি বাসা ভাড়া',desc:'৩ রুম + ড্রয়িং, টাইলস, পানির সুবিধা',price:8500,location:'কধুরখীল',subcategory:'ফ্যামিলি বাসা',rooms:'৩ রুম + ড্রয়িং'}));
 db.restaurants.push({id:'r1',name:'বোম্বে সুইটস ও কনফেকশনারি',category:'ঐতিহ্যবাহী মিষ্টি',price:'৩৫০ ৳/কেজি',location:'কালুরঘাট রোড, বোয়ালখালী',verified:true,delivery:false,menu:'চামচম, রসগোল্লা, ক্ষীরভোগ',desc:'খাঁটি গাভীর দুধের চামচম, ক্ষীরসা, কাঁচাগোল্লা ও জিলাপি',image:'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',phone:'01710000001'},{id:'r2',name:'বোয়ালখালী স্পেশাল বিরিয়ানি ও কাচ্চি ঘর',category:'বিরিয়ানি ও কাবাব',price:'১৮০ ৳/প্লেট',location:'উপজেলা মোড়, বোয়ালখালী',verified:true,delivery:true,menu:'শাহী কাচ্চি, বিফ তেহারি, মোরগ পোলাও',desc:'খাসির শাহী কাচ্চি, সরিষার তেলে রান্না বিফ তেহারি',image:'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800',phone:'01710000002'});
 db.jobs.push({id:'j1',title:'চৌমুহনী বাজারের শীর্ষ কাপড়ের শোরুমে সেলস এক্সিকিউটিভ আবশ্যক',company:'আল-মদিনা ফ্যাশন হাউজ',type:'FULL-TIME',salary:'১২,০০০ - ১৫,০০০ ৳ (কমিশনসহ)',deadline:'২০২৬-09-25',location:'চৌমুহনী বাজার ২য় তলা, বোয়ালখালী',verified:true,desc:'গ্রাহকদের সাথে মার্জিত আচরণ ও সেলস হ্যান্ডেল করতে হবে। ন্যূনতম এসএসসি পাস।',phone:'01712445566'},{id:'j2',title:'আধুনিক অফসেট প্রেসে গ্রাফিক্স ডিজাইনার ও কম্পিউটার অপারেটর',company:'বোয়ালখালী ডিজিটাল প্রেস',type:'FULL-TIME',salary:'১৪,০০০ - ১৮,০০০ ৳',deadline:'২০২৬-09-30',location:'কালুরঘাট রোড, বোয়ালখালী',verified:true,desc:'অফসেট প্রেসে কাজের অভিজ্ঞতা থাকতে হবে',phone:'01712445567'});
 db.doctors.push({id:'d1',name:'ডা. আব্দুল করিম',specialty:'মেডিসিন',chamber:'বোয়ালখালী মেডিকেল',address:'বোয়ালখালী সদর রোড',phone:'01710000003',hours:'বিকাল ৪টা - রাত ৯টা',fee:500,verified:true,emergency:true});
 db.blood_requests.push({id:'b1',patient:'মোছাঃ রোকেয়া বেগম (৫৫)',bloodGroup:'B+',location:'বোয়ালখালী হাসপাতাল',urgency:'CRITICAL',contact:'01710000004',status:'ACTIVE',createdAt:now()});
 db.blood_donors.push({id:'bd1',name:'রাহিম উদ্দিন',bloodGroup:'B+',phone:'01710000005',location:'কধুরখীল',available:true,lastDonation:'2026-06-01'});
 db.emergency_alerts.push({id:'e1',title:'জরুরি সতর্কতা',body:'জরুরি প্রয়োজনে যোগাযোগ করুন',severity:'HIGH',active:true,createdAt:now()});
 db.advertisements.push({id:'ad1',title:'মেগা ফ্যাশন পয়েন্ট • ঈদ ও শীতের মেগা ছাড়',body:'সর্বোচ্চ ৫০% পর্যন্ত ছাড়! শীত ও উৎসবের কেনাকাটায় সেরা ছাড়',image:'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',status:'APPROVED',promoted:true,impressions:120,clicks:12,startDate:now(),endDate:now()});
 db.service_providers.push({id:'s1',name:'করিম ইলেকট্রিশিয়ান',service:'ইলেকট্রিশিয়ান',location:'বোয়ালখালী বাজার',phone:'01710000006',experience:'৫ বছর',pricing:'৩০০৳ থেকে',verified:true,rating:4.8},{id:'s2',name:'সুমন প্লাম্বার',service:'প্লাম্বার',location:'কধুরখীল',phone:'01710000007',experience:'৩ বছর',pricing:'২৫০৳ থেকে',verified:false,rating:4.5});
 db.complaints.push({id:'c1',userId:'u_citizen',type:'রাস্তা',desc:'কধুরখীল রাস্তায় পানি জমে আছে',location:'কধুরখীল',status:'NEW',createdAt:now()});
 db.secret_reports.push({id:'sec1',title:'গোপন রিপোর্ট ১',desc:'(Admin only) নাগরিকের গোপন তথ্য',priority:'HIGH',status:'NEW',createdAt:now(),submitterHidden:true});
 db.volunteers=[];
 return db;
}
// Every array collection the codebase reads. Loaded state (file OR Firestore doc) is normalized through
// normalizeDB() so a collection missing from an older/partial stored DB can never crash a page with
// "Cannot read properties of undefined" (root cause of the 2026-10-08 admin 500s: pages read collections
// the seed never created). New collections used anywhere MUST be added here.
export const DB_COLLECTIONS=['users','roles','categories','subcategories','locations','feature_flags','posts','post_images','saved_posts','restaurants','menus','doctors','blood_donors','blood_requests','jobs','services','service_providers','lost_found','complaints','secret_reports','emergency_alerts','announcements','notifications','advertisements','memberships','reviews','transport_routes','transport_schedules','audit_logs','system_metrics','sessions','tokens','volunteers'];
export function normalizeDB(d:any):any{ if(!d||typeof d!=='object'||Array.isArray(d)) d={}; for(const k of DB_COLLECTIONS){ if(!Array.isArray(d[k])) d[k]=[]; } return d; }
function readFileDB():any{ try{ if(!fs.existsSync(DB_PATH)){const d=seedDB(); writeFileDB(d); return d;} return normalizeDB(JSON.parse(fs.readFileSync(DB_PATH,'utf8')));}catch{ const d=seedDB(); writeFileDB(d); return d;}}
function writeFileDB(d:any){ fs.mkdirSync(path.dirname(DB_PATH),{recursive:true}); const t=DB_PATH+'.tmp'; fs.writeFileSync(t,JSON.stringify(d,null,2)); fs.renameSync(t,DB_PATH);}
export async function readDBAsync():Promise<any>{ if(DB_BACKEND==='file') return readFileDB(); if(_fsCache&&Date.now()-_fsCache.at<FS_TTL_MS) return JSON.parse(JSON.stringify(_fsCache.db)); const fsdb=await firestoreDB(); const ref=fsdb.collection('bk_state').doc('main'); let snap:any; try{ snap=await ref.get(); }catch(e:any){ throw new Error('FIRESTORE_READ_FAILED: '+(e?.message||e)); } if(!snap.exists){ const d=seedDB(); await writeDBAsync(d); return d; } let db:any; try{ db=normalizeDB(JSON.parse((snap.data()||{}).json||'')); }catch{ throw new Error('FIRESTORE_STATE_CORRUPT: bk_state/main json field is not valid JSON'); } _fsCache={db,at:Date.now()}; return JSON.parse(JSON.stringify(db)); }
export async function writeDBAsync(d:any):Promise<void>{ if(DB_BACKEND==='file'){ writeFileDB(d); return; } const fsdb=await firestoreDB(); const json=JSON.stringify(d); try{ await fsdb.collection('bk_state').doc('main').set({json,updatedAt:new Date().toISOString()}); }catch(e:any){ throw new Error('FIRESTORE_WRITE_FAILED: '+(e?.message||e)); } _fsCache={db:JSON.parse(json),at:Date.now()}; }
export function audit(db:any,actor:string,action:string,target:string,meta:any={}){ db.audit_logs.unshift({id:id('log'),actor,action,target,metadata:meta,createdAt:now()}); }
export function sanitize(s:any){ return String(s||'').replace(/<[^>]*>/g,'').trim().slice(0,5000); }
