import fs from 'fs'; import path from 'path'; import {DB_BACKEND,UPLOAD_DIR,getFirebaseAdmin,addUploadBytes} from './db';
// Persistent image store. Firestore configured -> chunks in 'bk_images' collection (survives host restarts);
// otherwise local files in UPLOAD_DIR (dev). Same public contract: images are served at /api/uploads/<name>.
export const IMAGE_BACKEND=DB_BACKEND;
const COL='bk_images'; export const CHUNK_B64=700*1024; // base64 chars per chunk doc (Firestore doc limit 1MB; 700KB string + field overhead stays safely under)
export function splitBase64(b64:string,size:number=CHUNK_B64):string[]{ const out:string[]=[]; for(let i=0;i<b64.length;i+=size) out.push(b64.slice(i,i+size)); return out.length?out:['']; }
export function joinBase64(parts:string[]):string{ return parts.join(''); }
const key=(n:string)=>n.split('/').pop() as string;
async function col(){ const admin=await getFirebaseAdmin(); return admin.firestore().collection(COL); }
export async function saveImage(name:string,buf:Buffer,mime:string){ name=key(name); if(DB_BACKEND==='firestore'){ const c=await col(); const parts=splitBase64(buf.toString('base64')); const ops:any[]=[[c.doc(name),{name,mime,size:buf.length,chunks:parts.length,createdAt:new Date().toISOString()}]]; parts.forEach((p,i)=>ops.push([c.doc(name+'#'+i),{data:p}])); for(let i=0;i<ops.length;i+=400){ const b=c.firestore.batch(); ops.slice(i,i+400).forEach((op:any)=>b.set(op[0],op[1])); await b.commit(); } await addUploadBytes(buf.length); return {size:buf.length,chunks:parts.length,backend:'firestore'}; } fs.mkdirSync(UPLOAD_DIR,{recursive:true}); fs.writeFileSync(path.join(UPLOAD_DIR,name),buf); await addUploadBytes(buf.length); return {size:buf.length,chunks:1,backend:'file'}; }
export async function readImage(name:string){ name=key(name); if(DB_BACKEND==='firestore'){ const c=await col(); const m=await c.doc(name).get(); if(!m.exists) return null; const d:any=m.data(); const gs=await Promise.all(Array.from({length:d.chunks||0},(_v,i)=>c.doc(name+'#'+i).get())); if(gs.some(g=>!g.exists)) return null; return {buf:Buffer.from(joinBase64(gs.map(g=>(g.data() as any).data as string)),'base64'),mime:d.mime as string,size:d.size as number}; } const f=path.join(UPLOAD_DIR,name); if(!fs.existsSync(f)) return null; const mime:any={'.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp'}[path.extname(name).toLowerCase()]||'application/octet-stream'; return {buf:fs.readFileSync(f),mime,size:fs.statSync(f).size}; }
export async function deleteImage(name:string){ name=key(name); if(DB_BACKEND==='firestore'){ const c=await col(); const m=await c.doc(name).get(); if(!m.exists) return 0; const d:any=m.data(); const refs:any[]=[c.doc(name)]; for(let i=0;i<(d.chunks||0);i++) refs.push(c.doc(name+'#'+i)); for(let i=0;i<refs.length;i+=400){ const b=c.firestore.batch(); refs.slice(i,i+400).forEach(r=>b.delete(r)); await b.commit(); } await addUploadBytes(-(d.size||0)); return d.size||0; } const f=path.join(UPLOAD_DIR,name); if(!fs.existsSync(f)) return 0; const s=fs.statSync(f).size; fs.unlinkSync(f); await addUploadBytes(-s); return s; }
