// View-model for the public /boalkhali pages, now CMS-driven: PUBLISHED 'place' contents
// from the CMS, with a lib/places.ts fallback that applies ONLY while the CMS places seed
// has never run (db.meta.placesSeedV1 unset) and only for slugs with no content record —
// so a place an admin unpublished or deleted can never reappear from the static data.
// Everything rendered (name, text, images, maps, geo) comes from the stored record.
import {readDBAsync,mutateDBAsync} from './db';
import {sanitizeContent,sanitizeContentType,ensureCmsSeeds,needsCmsSeeds,contentTitle,isPublishedVisible} from './cms';
import {PLACES,placeMapsUrl,placeEmbedUrl} from './places';
import {PLACE_ILLUSTRATIONS} from './placeImages';
export interface VImg{url:string;caption:string;alt:string;ill:boolean;source?:string}
export interface VPlace{slug:string;name:string;area:string;inside:boolean;detail:string;short:string;images:VImg[];mapsUrl:string;embedUrl:string;lat:number|null;lng:number|null}
export async function loadBoalkhaliDb(){ let db=await readDBAsync(); if(needsCmsSeeds(db)){ await mutateDBAsync((d:any)=>{ ensureCmsSeeds(d,'system'); }); db=await readDBAsync(); } return db; }
const ILL_CAPTION='প্রতীকী ছবি (ইলাস্ট্রেশন)';
function firstSentence(t:string){ const first=String(t||'').split('\n')[0]; const i=first.indexOf('।'); return i>40?first.slice(0,i+1):first.slice(0,120); }
const num=(v:any)=>(typeof v==='number'&&Number.isFinite(v))?v:null;
export function placeFromStatic(p:any):VPlace{ const images:VImg[]=p.photos.length?p.photos.map((ph:any)=>({url:ph.url,caption:ph.credit,alt:p.nameBn,ill:false,source:ph.sourcePage})):(PLACE_ILLUSTRATIONS[p.slug]?[{url:'/api/img/place/'+p.slug,caption:ILL_CAPTION,alt:p.nameBn,ill:true}]:[]); const exact=p.precision==='exact'; return {slug:p.slug,name:p.nameBn,area:p.area,inside:!!p.insideBoalkhali,detail:p.detailBn,short:firstSentence(p.detailBn),images,mapsUrl:placeMapsUrl(p),embedUrl:placeEmbedUrl(p),lat:exact?p.lat:null,lng:exact?p.lng:null}; }
export function placeFromContent(c:any):VPlace{ const name=contentTitle(c); const loc=c.location||{}; const detail=String((c.fields&&typeof c.fields.history==='string'&&c.fields.history)||c.fullDesc||c.shortDesc||''); let images:VImg[]=(Array.isArray(c.images)?c.images:[]).map((im:any)=>({url:im.url,caption:im.caption||'',alt:im.alt||name,ill:String(im.url).startsWith('/api/img/place/')})); if(!images.length&&PLACE_ILLUSTRATIONS[c.slug]) images=[{url:'/api/img/place/'+c.slug,caption:ILL_CAPTION,alt:name,ill:true}]; const lat=num(loc.lat), lng=num(loc.lng); let q=''; try{ q=new URL(String(loc.mapsUrl||'')).searchParams.get('query')||''; }catch{} const query=q||encodeURIComponent(name+' '+String(loc.area||'')); const mapsUrl=String(loc.mapsUrl||'')||('https://www.google.com/maps/search/?api=1&query='+((lat!==null&&lng!==null)?lat+','+lng:query)); const embedUrl=(lat!==null&&lng!==null)?('https://www.google.com/maps?q='+lat+','+lng+'&output=embed'):('https://www.google.com/maps?q='+query+'&output=embed'); const area=String(loc.area||'')||[loc.union,loc.upazila].filter(Boolean).join(', '); return {slug:c.slug,name,area,inside:!(Array.isArray(c.tags)&&c.tags.includes('কাছাকাছি')),detail,short:c.shortDesc||firstSentence(detail),images,mapsUrl,embedUrl,lat,lng}; }
// All visible places (published CMS contents + pre-seed static fallback), PLACES order first.
export function resolvePlaces(db:any):VPlace[]{ const type=sanitizeContentType((db.content_types||[]).find((t:any)=>t.slug==='place')); const recs=(db.contents||[]).map((c:any)=>sanitizeContent(c)).filter((c:any)=>c&&c.typeSlug==='place'); const order=new Map<string,number>(PLACES.map((p:any,i:number)=>[p.slug,i])); const views:VPlace[]=[]; const seen=new Set<string>(); for(const c of recs){ if(isPublishedVisible(c,type)){ views.push(placeFromContent(c)); seen.add(c.slug); } } const marker=!!(db.meta&&db.meta.placesSeedV1); if(!marker){ const haveRec=new Set(recs.map((c:any)=>c.slug)); for(const p of PLACES){ if(!haveRec.has(p.slug)&&!seen.has(p.slug)){ views.push(placeFromStatic(p)); seen.add(p.slug); } } } views.sort((a,b)=>{ const ia=order.has(a.slug)?order.get(a.slug)!:999, ib=order.has(b.slug)?order.get(b.slug)!:999; return ia!==ib?ia-ib:a.name.localeCompare(b.name,'bn'); }); return views; }
export function resolvePlace(db:any,slug:string):VPlace|null{ return resolvePlaces(db).find((v:any)=>v.slug===slug)||null; }
