import {readDBAsync,mutateDBAsync} from '@/lib/db'; import {Shell,bn,EmptyState} from '@/components/ui'; import {sanitizeContentType,sanitizeContent,ensureCmsSeeds,needsCmsSeeds,contentTitle,featuredImage,isPublishedVisible} from '@/lib/cms'; import {dateOnly,todayStr,isExpired} from '@/lib/expiry'; import Link from 'next/link'; export const dynamic='force-dynamic'; export const metadata={title:'অনুষ্ঠান ও ইভেন্ট — বোয়ালখালী কানেক্ট',description:'বোয়ালখালীর আসন্ন অনুষ্ঠান, মেলা, ওরশ ও সামাজিক ইভেন্টের তালিকা এবং সাম্প্রতিক ঘোষণা'};
// Honest events (Wave 1): this page used to be a hard-coded placeholder list of
// service names with no data behind it. It now renders ONLY real records: PUBLISHED
// CMS 'event' contents (split আসন্ন/অতীত by their stored eventDate; undated items are
// labeled, never silently dated) plus the site's active announcements. Expired
// announcements (expiresAt in the past, when one is set) never present as current.
async function load(){ let db=await readDBAsync(); if(needsCmsSeeds(db)){ await mutateDBAsync((d:any)=>{ ensureCmsSeeds(d,'system'); }); db=await readDBAsync(); } return db; }
const fmtD=(d:string)=>d?new Date(d+'T00:00:00').toLocaleDateString('bn-BD'):'';
export default async function P(){ const db=await load(); const type=sanitizeContentType((db.content_types||[]).find((t:any)=>t.slug==='event')); const today=todayStr();
 const ev=(db.contents||[]).filter((c:any)=>c&&c.typeSlug==='event').map((c:any)=>sanitizeContent(c)).filter((c:any)=>isPublishedVisible(c,type)).map((c:any)=>({c,d:dateOnly(c.fields&&c.fields.eventDate)})).filter((x:any)=>x.c);
 const upcoming=ev.filter((x:any)=>!x.d||x.d>=today).sort((a:any,b:any)=>(a.d||'9999').localeCompare(b.d||'9999'));
 const past=ev.filter((x:any)=>x.d&&x.d<today).sort((a:any,b:any)=>b.d.localeCompare(a.d));
 const anns=(db.announcements||[]).filter((a:any)=>a.active!==false&&!isExpired(a)).sort((a:any,b:any)=>String(b.createdAt||'').localeCompare(String(a.createdAt||'')));
 const Card=({x}:{x:any})=>{ const c=x.c; const img=featuredImage(c); return <Link href={'/content/event/'+c.slug} className="card block mb-3 press overflow-hidden !p-0">{img&&<img src={img.url} alt={img.alt||contentTitle(c)} loading="lazy" className="h-40 w-full object-cover"/>}<div className="p-4"><div className="flex flex-wrap gap-1.5">{x.d?<span className="chip bg-fuchsia-100 text-fuchsia-800">📅 {fmtD(x.d)}</span>:<span className="chip bg-slate-100">তারিখ দেওয়া হয়নি</span>}{c.fields.eventTime&&<span className="chip bg-slate-100">🕐 {String(c.fields.eventTime)}</span>}{c.fields.venue&&<span className="chip bg-slate-100">📍 {String(c.fields.venue)}</span>}</div><h3 className="font-black mt-2">{contentTitle(c)}</h3>{c.shortDesc&&<p className="text-sm text-gray-600 mt-1">{c.shortDesc}</p>}{c.fields.organizer&&<p className="text-xs text-gray-400 mt-1">আয়োজক: {String(c.fields.organizer)}</p>}</div></Link>; };
 return <Shell><main className="max-w-3xl mx-auto p-4"><h1 className="font-black text-xl">অনুষ্ঠান ও ইভেন্ট</h1><p className="text-sm text-gray-500 mt-1">বোয়ালখালীর আসন্ন অনুষ্ঠান ও সাম্প্রতিক ঘোষণা — সব তথ্যই আসল রেকর্ড থেকে আসছে।</p>
 <h2 className="font-black mt-5 mb-2">🎉 আসন্ন ইভেন্ট ({bn(upcoming.length)}টি)</h2>{upcoming.map((x:any)=><Card key={x.c.id} x={x}/>)}{upcoming.length===0&&<div className="card text-sm text-gray-500">এখনো কোনো আসন্ন ইভেন্ট ঘোষণা হয়নি।</div>}
 {anns.length>0&&<><h2 className="font-black mt-6 mb-2">📢 ঘোষণা</h2>{anns.map((a:any)=>(<div key={a.id} className="card mb-2"><b>{a.title}</b>{a.body&&<p className="text-sm text-gray-600 mt-1">{a.body}</p>}{a.createdAt&&<p className="text-xs text-gray-400 mt-1">প্রকাশ: {new Date(a.createdAt).toLocaleDateString('bn-BD')}</p>}</div>))}</>}
 {past.length>0&&<><h2 className="font-black mt-6 mb-2">🗓️ অতীত ইভেন্ট</h2>{past.map((x:any)=><Card key={x.c.id} x={x}/>)}</>}
 {upcoming.length===0&&anns.length===0&&past.length===0&&<div className="mt-4"><EmptyState icon="🎉" title="এখনো কোনো ইভেন্ট বা ঘোষণা নেই" desc="নতুন কোনো অনুষ্ঠান ঘোষণা হলেই এখানে দেখা যাবে।" href="/" cta="হোমে যান"/></div>}
 </main></Shell>}
