'use client'; import {useState} from 'react'; import {useRouter} from 'next/navigation'; import Link from 'next/link';
const BLOOD_GROUPS=['A+','A-','B+','B-','O+','O-','AB+','AB-'];
const URGENCY:[string,string][]=[['LOW','সাধারণ'],['MEDIUM','মাঝারি'],['HIGH','জরুরি'],['CRITICAL','অত্যন্ত জরুরি']];
const REQ_STATUS:any={OPEN:'চলমান',ACTIVE:'চলমান',FULFILLED:'পূরণ হয়েছে',CANCELLED:'বাতিল',COMPLETED:'পূরণ হয়েছে',CLOSED:'বন্ধ'};
export default function BloodClient({user,locations,myRequests,myDonor}:any){const router=useRouter(); const [dMsg,setDMsg]=useState(''); const [dErr,setDErr]=useState(''); const [rMsg,setRMsg]=useState(''); const [rErr,setRErr]=useState(''); const [busy,setBusy]=useState('');
 if(!user) return <div className="card mt-4"><h2 className="font-black">রক্তদাতা হতে চান? রক্তের প্রয়োজন?</h2><p className="text-sm text-gray-500 mt-1">রক্তদাতা হিসেবে নিবন্ধন করতে বা রক্তের অনুরোধ দিতে লগইন করুন।</p><Link href="/login" className="btn mt-3">লগইন করুন</Link></div>;
 const donorSubmit=async(ev:any)=>{ev.preventDefault(); setDErr(''); setDMsg(''); const f=new FormData(ev.currentTarget); const body={bloodGroup:String(f.get('bloodGroup')||''),phone:String(f.get('phone')||''),area:String(f.get('area')||''),available:f.get('available')==='on',lastDonation:String(f.get('lastDonation')||'')}; setBusy('donor'); try{const r=await fetch('/api/blood/donors',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const j=await r.json(); if(!r.ok){setDErr(j.error==='INVALID_PHONE'?'সঠিক ১১ ডিজিটের মোবাইল নম্বর দিন':j.error==='AREA_REQUIRED'?'এলাকা নির্বাচন করুন':'নিবন্ধন করা যায়নি, আবার চেষ্টা করুন'); return;} setDMsg('আপনার রক্তদাতা তথ্য সংরক্ষণ হয়েছে। ধন্যবাদ!'); router.refresh();}catch{setDErr('নিবন্ধন করা যায়নি, আবার চেষ্টা করুন');}finally{setBusy('');}};
 const reqSubmit=async(ev:any)=>{ev.preventDefault(); setRErr(''); setRMsg(''); const f=new FormData(ev.currentTarget); const body={patient:String(f.get('patient')||''),bloodGroup:String(f.get('bloodGroup')||''),hospital:String(f.get('hospital')||''),area:String(f.get('area')||''),units:Number(f.get('units')||1),contact:String(f.get('contact')||''),urgency:String(f.get('urgency')||'MEDIUM')}; setBusy('req'); try{const r=await fetch('/api/blood/requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const j=await r.json(); if(!r.ok){setRErr(j.error==='INVALID_PHONE'?'সঠিক যোগাযোগের মোবাইল নম্বর দিন':j.error==='LOCATION_REQUIRED'?'হাসপাতাল বা এলাকা দিন':'অনুরোধ দেওয়া যায়নি, আবার চেষ্টা করুন'); return;} setRMsg('আপনার রক্তের অনুরোধ প্রকাশ হয়েছে'); ev.currentTarget.reset(); router.refresh();}catch{setRErr('অনুরোধ দেওয়া যায়নি, আবার চেষ্টা করুন');}finally{setBusy('');}};
 const act=async(rid:string,action:string)=>{setBusy(rid); try{const r=await fetch('/api/blood/requests',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:rid,action})}); if(r.ok) router.refresh();}finally{setBusy('');}};
 return <div>
 <form onSubmit={donorSubmit} className="card mt-4"><h2 className="font-black">🩸 রক্তদাতা হিসেবে নিবন্ধন</h2>
 <label className="block text-sm font-bold mt-3">রক্তের গ্রুপ *</label><select name="bloodGroup" required defaultValue={myDonor?.bloodGroup||user.bloodGroup||''}><option value="">— নির্বাচন করুন —</option>{BLOOD_GROUPS.map(g=><option key={g} value={g}>{g}</option>)}</select>
 <label className="block text-sm font-bold mt-3">মোবাইল নম্বর *</label><input name="phone" required inputMode="tel" placeholder="01XXXXXXXXX" defaultValue={myDonor?.phone||user.phone||''}/>
 <label className="block text-sm font-bold mt-3">এলাকা *</label><select name="area" required defaultValue={myDonor?.location||myDonor?.area||user.area||''}><option value="">— এলাকা নির্বাচন করুন —</option>{locations.map((n:string)=><option key={n} value={n}>{n}</option>)}</select>
 <label className="block text-sm font-bold mt-3">সর্বশেষ রক্তদানের তারিখ (ঐচ্ছিক)</label><input name="lastDonation" type="date" defaultValue={myDonor?.lastDonation||''}/>
 <label className="flex items-center gap-2 mt-3 text-sm font-bold"><input type="checkbox" name="available" defaultChecked={myDonor?!!myDonor.available:true} className="!w-auto"/> এখন রক্তদানে সক্ষম আছি</label>
 {dErr&&<p className="text-red-600 text-sm mt-2">{dErr}</p>}{dMsg&&<p className="text-emerald-700 text-sm mt-2">{dMsg}</p>}
 <button className="btn w-full mt-3 !bg-red-600" disabled={busy==='donor'}>{busy==='donor'?'সংরক্ষণ হচ্ছে…':(myDonor?'তথ্য আপডেট করুন':'রক্তদাতা হিসেবে নিবন্ধন করুন')}</button></form>
 <form onSubmit={reqSubmit} className="card mt-4"><h2 className="font-black">🚨 রক্তের অনুরোধ দিন</h2>
 <label className="block text-sm font-bold mt-3">রোগীর নাম (ঐচ্ছিক)</label><input name="patient" placeholder="না দিলে গোপন থাকবে"/>
 <label className="block text-sm font-bold mt-3">রক্তের গ্রুপ *</label><select name="bloodGroup" required defaultValue=""><option value="">— নির্বাচন করুন —</option>{BLOOD_GROUPS.map(g=><option key={g} value={g}>{g}</option>)}</select>
 <label className="block text-sm font-bold mt-3">হাসপাতাল</label><input name="hospital" placeholder="যেমন: বোয়ালখালী হাসপাতাল"/>
 <label className="block text-sm font-bold mt-3">এলাকা</label><select name="area" defaultValue=""><option value="">— এলাকা নির্বাচন করুন —</option>{locations.map((n:string)=><option key={n} value={n}>{n}</option>)}</select>
 <div className="grid grid-cols-2 gap-2"><div><label className="block text-sm font-bold mt-3">ব্যাগ/ইউনিট</label><input name="units" type="number" min={1} max={20} defaultValue={1}/></div><div><label className="block text-sm font-bold mt-3">জরুরিতা</label><select name="urgency" defaultValue="MEDIUM">{URGENCY.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div></div>
 <label className="block text-sm font-bold mt-3">যোগাযোগের মোবাইল *</label><input name="contact" required inputMode="tel" placeholder="01XXXXXXXXX" defaultValue={user.phone||''}/>
 {rErr&&<p className="text-red-600 text-sm mt-2">{rErr}</p>}{rMsg&&<p className="text-emerald-700 text-sm mt-2">{rMsg}</p>}
 <button className="btn w-full mt-3 !bg-red-600" disabled={busy==='req'}>{busy==='req'?'প্রকাশ হচ্ছে…':'অনুরোধ প্রকাশ করুন'}</button></form>
 {myRequests&&myRequests.length>0&&(<div className="card mt-4"><h2 className="font-black">আমার রক্তের অনুরোধসমূহ</h2>{myRequests.map((r:any)=>(<div key={r.id} className="border-b py-2"><span className="chip bg-red-600 text-white">{r.bloodGroup}</span> <b>{r.patient}</b> <span className="chip bg-slate-100">{REQ_STATUS[r.status]||r.status}</span><p className="text-sm">{r.location} • {r.units||1} ব্যাগ • {r.contact}</p>{(r.status==='OPEN'||r.status==='ACTIVE')&&(<div className="flex gap-2 mt-2"><button className="btn !py-1" disabled={busy===r.id} onClick={()=>act(r.id,'fulfill')}>পূরণ হয়েছে</button><button className="btn !py-1 !bg-slate-600" disabled={busy===r.id} onClick={()=>act(r.id,'cancel')}>বাতিল</button></div>)}</div>))}</div>)}
 </div>}
