'use client'; import {Shell} from '@/components/ui'; import {useState} from 'react'; import Link from 'next/link';
// Honest two-path recovery (A-06): the server tells us which kind of account this is.
// Firebase accounts really get a Firebase reset mail; DB-password accounts file an admin
// reset request instead of being told a lie. Copy matches what actually happens.
export default function P(){ const [busy,setBusy]=useState(false); const [msg,setMsg]=useState(''); const [err,setErr]=useState('');
 const submit=async(ev:any)=>{ ev.preventDefault(); setMsg(''); setErr(''); const ident=String(new FormData(ev.currentTarget).get('identifier')||'').trim(); if(!ident){ setErr('ইমেইল বা ফোন নম্বর দিন'); return; } setBusy(true); try{ const r=await fetch('/api/auth/forgot',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identifier:ident})}); const j=await r.json().catch(()=>({})); if(!r.ok){ setErr('হয়নি — কিছুক্ষণ পর আবার চেষ্টা করুন'); setBusy(false); return; }
  if(j.mode==='firebase'){ try{ const {resetPassword}=await import('@/lib/firebaseClient'); await resetPassword(j.email); setMsg('✅ Firebase থেকে পাসওয়ার্ড রিসেটের ইমেইল পাঠানো হয়েছে — আপনার ইনবক্স (ও স্প্যাম ফোল্ডার) দেখুন। লিংক থেকে নতুন পাসওয়ার্ড দিয়ে এখানে লগইন করুন।'); }catch{ setErr('রিসেট ইমেইল পাঠানো যায়নি — ইমেইলটি যাচাই করে আবার চেষ্টা করুন, অথবা অ্যাডমিনের সহায়তা নিন।'); } }
  else if(j.mode==='admin'){ setMsg('ℹ️ আপনার অ্যাকাউন্টটি ইমেইল লিংক দিয়ে রিসেট করা যায় না, তাই অ্যাডমিনের কাছে পাসওয়ার্ড রিসেটের অনুরোধ '+(j.already?'আগে থেকেই পাঠানো আছে':'পাঠানো হয়েছে')+'। অ্যাডমিন নতুন পাসওয়ার্ড সেট করে দিলে আগের মতোই লগইন করতে পারবেন। জরুরি হলে সাইটের যোগাযোগের মাধ্যমে অ্যাডমিনকে জানান।'); }
  else setErr('এই ইমেইল/ফোন নম্বরে কোনো অ্যাকাউন্ট পাওয়া যায়নি — বানান যাচাই করে আবার চেষ্টা করুন।');
 }catch{ setErr('নেটওয়ার্ক সমস্যা — আবার চেষ্টা করুন'); } setBusy(false); };
 return <Shell><main className="max-w-md mx-auto p-4"><form className="card" onSubmit={submit}><h1 className="font-black text-xl">পাসওয়ার্ড ভুলে গেছেন?</h1><p className="text-sm text-gray-500 mt-1">আপনার অ্যাকাউন্টের ইমেইল বা ফোন নম্বর দিন। অ্যাকাউন্টের ধরন অনুযায়ী রিসেটের উপায় দেখানো হবে।</p><label className="block text-sm font-bold mt-3">ইমেইল / ফোন নম্বর<input name="identifier" type="text" required placeholder="you@example.com অথবা 01XXXXXXXXX" autoComplete="username"/></label>{err&&<p className="text-red-600 text-sm mt-2">{err}</p>}{msg&&<p className="text-emerald-700 text-sm mt-2">{msg}</p>}<button className="btn w-full mt-3" disabled={busy}>{busy?'যাচাই হচ্ছে…':'এগিয়ে যান'}</button><Link href="/login" className="btn w-full mt-3 !bg-slate-700 text-center">লগইনে ফিরুন</Link></form></main></Shell>}
