export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,writeDBAsync,mutateDBAsync,sanitize,id,now,audit} from '@/lib/db'; import {currentUser,requireRole,rateLimit} from '@/lib/auth'; import {hasPermission} from '@/lib/permissions';
const BLOOD_GROUPS=['A+','A-','B+','B-','O+','O-','AB+','AB-']; const URGENCY=['LOW','MEDIUM','HIGH','CRITICAL'];
const isOpen=(r:any)=>r.status==='OPEN'||r.status==='ACTIVE';
export async function GET(){ const user=await currentUser(); const db=await readDBAsync(); const requests=db.blood_requests.filter(isOpen); const mine=user?db.blood_requests.filter((r:any)=>r.userId===user.id).sort((a:any,b:any)=>String(b.createdAt).localeCompare(String(a.createdAt))):[]; return NextResponse.json({requests,mine}) }
export async function DELETE(req:Request){ const r=await requireRole(['ADMIN','SUPER_ADMIN']); if((r as any).error) return NextResponse.json(r,{status:(r as any).status}); if(!hasPermission((r as any).user.role,'blood.manage')) return NextResponse.json({error:'FORBIDDEN'},{status:403}); const reqId=new URL(req.url).searchParams.get('id')||''; if(!reqId) return NextResponse.json({error:'ID_REQUIRED'},{status:400}); const out:any=await mutateDBAsync((db:any)=>{ const q=db.blood_requests.find((x:any)=>x.id===reqId); if(!q) return {e:404,error:'NOT_FOUND'}; db.blood_requests=db.blood_requests.filter((x:any)=>x.id!==reqId); audit(db,(r as any).user.email,'BLOOD_REQUEST_DELETE',reqId,{bloodGroup:q.bloodGroup}); return {ok:true,deleted:reqId}; }); if(out.e) return NextResponse.json({error:out.error},{status:out.e}); return NextResponse.json(out); }
export async function POST(req:Request){ if(!rateLimit('breq',20)) return NextResponse.json({error:'RATE_LIMIT'},{status:429}); const user=await currentUser(); if(!user) return NextResponse.json({error:'LOGIN_REQUIRED'},{status:401}); const b=await req.json(); const db=await readDBAsync();
 if(b.action){ const r=db.blood_requests.find((x:any)=>x.id===b.id); if(!r) return NextResponse.json({error:'NOT_FOUND'},{status:404}); if(r.userId!==user.id) return NextResponse.json({error:'FORBIDDEN'},{status:403}); if(b.action==='fulfill') r.status='FULFILLED'; else if(b.action==='cancel') r.status='CANCELLED'; else return NextResponse.json({error:'INVALID_ACTION'},{status:400}); r.updatedAt=now(); audit(db,user.email,'BLOOD_REQUEST_'+String(b.action).toUpperCase(),r.id); await writeDBAsync(db); return NextResponse.json({ok:true,request:r}); }
 const bloodGroup=String(b.bloodGroup||''); if(!BLOOD_GROUPS.includes(bloodGroup)) return NextResponse.json({error:'INVALID_BLOOD_GROUP'},{status:400}); const contact=sanitize(b.contact||b.phone).replace(/[\s-]/g,''); if(!/^01[3-9]\d{8}$/.test(contact)) return NextResponse.json({error:'INVALID_PHONE'},{status:400}); const hospital=sanitize(b.hospital); const area=sanitize(b.area||b.location); const location=[hospital,area].filter(Boolean).join(' • '); if(!location) return NextResponse.json({error:'LOCATION_REQUIRED'},{status:400}); const units=Math.max(1,Math.min(20,Number(b.units||1)||1)); const urgency=URGENCY.includes(String(b.urgency||''))?String(b.urgency):'MEDIUM'; const r={id:id('br'),userId:user.id,patient:sanitize(b.patient)||'অজ্ঞাত রোগী',bloodGroup,hospital,area,location,units,contact,urgency,status:'ACTIVE',createdAt:now()}; db.blood_requests.unshift(r); audit(db,user.email,'BLOOD_REQUEST_CREATE',r.id); await writeDBAsync(db); return NextResponse.json({ok:true,request:r}) }
