import {CmsHub} from '@/components/CmsHub'; import {readDBAsync} from '@/lib/db'; import {currentUser} from '@/lib/auth'; import {hasPermission} from '@/lib/permissions'; import {sanitizeContent,contentTitle} from '@/lib/cms'; import {BusinessOwner} from '@/components/BusinessOwner'; import Link from 'next/link'; export const dynamic='force-dynamic'; export const metadata={title:'স্থানীয় ব্যবসা — বোয়ালখালী কানেক্ট',description:'বোয়ালখালীর দোকান ও ব্যবসাপ্রতিষ্ঠানের তথ্য — ধরন ও এলাকা দিয়ে খুঁজুন',alternates:{canonical:'/businesses'}};
// Local Business hub (CMS 'business' contents) + owner mini-dashboard (Wave 3):
// a logged-in owner sees THEIR business records with status, persisted views and
// verification state, and can apply for the ✓ badge — the badge itself is only ever
// written by the admin review route.
export default async function P({searchParams}:{searchParams:any}){ const me:any=await currentUser(); let below:any=null;
 if(!me) below=<section className="card mt-3 text-sm">নিজের ব্যবসার যাচাইয়ের আবেদন করতে <Link href="/login?next=/businesses" className="font-bold text-brand-700">লগইন করুন</Link>।</section>;
 else { const db=await readDBAsync(); const reqs=(db.business_verifications||[]).filter((v:any)=>v&&v.userId===me.id); const items=(db.contents||[]).filter((c:any)=>c&&c.typeSlug==='business'&&c.createdBy===me.id).map((c:any)=>sanitizeContent(c)).filter(Boolean).map((c:any)=>{ const latest=reqs.filter((v:any)=>v.contentId===c.id).sort((a:any,b:any)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]; const verState=c.verified?'verified':latest?(latest.status==='PENDING'?'pending':latest.status==='REJECTED'?'rejected':'none'):'none'; return {id:c.id,title:contentTitle(c),slug:c.slug,status:c.status,views:c.views||0,verState,reviewNote:latest?(latest.reviewNote||''):'' ,verifiedAt:c.verifiedAt?String(c.verifiedAt):''}; }); below=<BusinessOwner items={items} canEdit={hasPermission(me.role,'content.edit')}/>; }
 return <CmsHub typeSlugs={['business']} title="স্থানীয় ব্যবসা" icon="🏪" desc="বোয়ালখালীর দোকান ও ব্যবসাপ্রতিষ্ঠান — ধরন ও এলাকা অনুযায়ী খুঁজুন।" emptyTitle="এখনো কোনো ব্যবসাপ্রতিষ্ঠানের তথ্য প্রকাশিত হয়নি" emptyDesc="অ্যাডমিন প্যানেল থেকে তথ্য প্রকাশ হলেই এখানে দেখা যাবে। নিজের ব্যবসা যোগ করতে অ্যাডমিনের সঙ্গে যোগাযোগ করুন।" searchParams={searchParams} below={below}/>; }
