'use client'; import {Shell,bn,EmptyState,SkeletonList} from '@/components/ui'; import {useEffect,useState} from 'react'; import Link from 'next/link'; import {errMsg} from '@/lib/errMsg';
const SL:any={PENDING:['অপেক্ষমাণ','bg-amber-100 text-amber-800'],APPROVED:['অনুমোদিত','bg-emerald-100 text-emerald-800'],REJECTED:['বাতিল','bg-red-100 text-red-700'],SUSPENDED:['স্থগিত','bg-slate-200 text-slate-700']};
export default function P(){ const [posts,setPosts]=useState<any[]|null>(null); const [needLogin,setNeedLogin]=useState(false); const [editId,setEditId]=useState(''); const [msg,setMsg]=useState('');
 const load=async()=>{ const r=await fetch('/api/posts/mine'); if(r.status===401){setNeedLogin(true); setPosts([]); return} const j=await r.json(); setPosts(j.posts||[]) };
 useEffect(()=>{load()},[]);
 const act=async(p:any,action:string)=>{ if(action==='delete'&&!confirm('নিশ্চিত? এই পোস্টটি স্থায়ীভাবে মুছে যাবে।'))return; const r=await fetch('/api/posts/mine',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:p.id,action})}); const j=await r.json(); setMsg(r.ok?(action==='delete'?'পোস্ট মুছে ফেলা হয়েছে':action==='sold'?'বিক্রি হয়েছে হিসেবে চিহ্নিত হয়েছে':'পোস্ট আবার সক্রিয় করা হয়েছে'):('ব্যর্থ: '+errMsg(j.error))); load() };
 const save=async(e:any,p:any)=>{ e.preventDefault(); const f=new FormData(e.currentTarget); const body:any=Object.fromEntries(f); body.id=p.id; body.hidePhone=f.get('hidePhone')==='on'; body.price=Number(body.price||0); const r=await fetch('/api/posts/mine',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const j=await r.json(); if(r.ok){ setMsg(j.remoderation?'সম্পাদনা সংরক্ষিত — পোস্টটি আবার মডারেশনের অপেক্ষায় পাঠানো হয়েছে (অপেক্ষমাণ)':'সম্পাদনা সংরক্ষিত হয়েছে'); setEditId(''); load() } else setMsg('ব্যর্থ: '+errMsg(j.error)) };
 if(needLogin) return <Shell><main className="max-w-3xl mx-auto p-4"><div className="card text-center"><h1 className="font-black text-xl">আমার পোস্টসমূহ</h1><p className="text-sm text-gray-500 mt-2">আপনার পোস্ট দেখতে ও সম্পাদনা করতে লগইন করুন</p><Link href="/login" className="btn mt-3 inline-block">লগইন করুন</Link></div></main></Shell>;
 return <Shell><main className="max-w-3xl mx-auto p-4"><div className="flex items-center justify-between"><h1 className="font-black text-xl">আমার পোস্টসমূহ</h1><Link href="/create" className="btn !py-2">+ নতুন পোস্ট</Link></div>{msg&&<p className="card mt-3 text-sm">{msg}</p>}
 {posts===null&&<div className="mt-3"><SkeletonList count={3}/></div>}
 {posts!==null&&posts.length===0&&<div className="mt-3"><EmptyState icon="📝" title="এখনো কোনো পোস্ট দেননি" desc="আপনার প্রথম পোস্টটি দিন — বোয়ালখালীর সবাই দেখবে।" href="/create" cta="নতুন পোস্ট করুন"/></div>}
 {posts?.map((p:any)=>(<div key={p.id} className="card mt-3"><div className="flex gap-2 flex-wrap items-center"><b>{p.title}</b><span className={'chip '+(SL[p.status]?SL[p.status][1]:'bg-slate-100')}>{SL[p.status]?SL[p.status][0]:p.status}</span>{p.sold&&<span className="chip bg-red-600 text-white">বিক্রি হয়েছে</span>}{p.hidePhone&&<span className="chip bg-slate-100">ফোন লুকানো</span>}</div>
 <p className="text-xs text-gray-400 mt-1">{bn(p.price)} ৳ • {p.location} • {p.createdAt?new Date(p.createdAt).toLocaleDateString('bn-BD'):''}</p>
 {p.status==='REJECTED'&&<div className="bg-red-50 border border-red-200 text-red-700 text-sm rounded-xl p-3 mt-2"><b>বাতিলের কারণ:</b> {p.rejectReason||'কারণ জানানো হয়নি'}<p className="text-xs mt-1">পোস্টটি সম্পাদনা করে ঠিক করলে আবার মডারেশনে যাবে।</p></div>}
 <div className="flex gap-2 flex-wrap mt-3"><Link href={'/post/'+p.id} className="chip bg-emerald-100">পোস্ট দেখুন</Link><button onClick={()=>setEditId(editId===p.id?'':p.id)} className="chip bg-blue-100">সম্পাদনা</button>{!p.sold?<button onClick={()=>act(p,'sold')} className="chip bg-red-100">বিক্রি হয়েছে চিহ্নিত করুন</button>:<button onClick={()=>act(p,'active')} className="chip bg-emerald-100">আবার সক্রিয় করুন</button>}<button onClick={()=>act(p,'delete')} className="chip bg-slate-200">মুছে ফেলুন</button></div>
 {editId===p.id&&(<form onSubmit={(e)=>save(e,p)} className="mt-3 space-y-2 bg-slate-50 p-3 rounded-xl"><label>শিরোনাম<input name="title" defaultValue={p.title} required/></label><label>বিবরণ<textarea name="desc" defaultValue={p.desc} rows={3} required/></label><label>দাম (টাকা)<input name="price" type="number" defaultValue={p.price}/></label><label>এলাকা<input name="location" defaultValue={p.location}/></label><label>মোবাইল<input name="phone" defaultValue={p.phone}/></label><label>হোয়াটসঅ্যাপ<input name="whatsapp" defaultValue={p.whatsapp}/></label><label>ছবির লিংক<input name="image" defaultValue={p.image}/></label><label className="flex gap-2 items-center"><input type="checkbox" name="hidePhone" defaultChecked={!!p.hidePhone} className="!w-auto"/> ফোন নম্বর লুকান</label><div className="flex gap-2"><button className="btn">সংরক্ষণ করুন</button><button type="button" onClick={()=>setEditId('')} className="chip bg-slate-200">বাতিল</button></div></form>)}
 </div>))}
 </main></Shell>}
