import {readDBAsync,CATEGORIES} from '@/lib/db'; import {requireAdminPage} from '@/lib/auth'; import {bn} from '@/components/ui'; import {searchInsights} from '@/lib/searchLog'; import {isExpired} from '@/lib/expiry'; import Link from 'next/link'; export const dynamic='force-dynamic';
// Development Insights (Wave 2): every number on this page is computed live from the real
// database — search logs (bk_search_logs, term+count+day only), post counts, persisted
// post views, CMS published counts. Nothing is sampled, estimated or hard-coded; when a
// section has no data yet it says so honestly instead of inventing a chart.
export default async function P(){ await requireAdminPage('search.analytics'); const db=await readDBAsync(); const ins=searchInsights(db,30); const zeroPct=ins.total?Math.round(ins.zeroTotal/ins.total*100):0; const catName:any={}; for(const c of CATEGORIES) catName[c.slug]=c.name; for(const c of (db.categories||[])) if(c&&c.slug) catName[c.slug]=c.name||catName[c.slug];
 const livePosts=(db.posts||[]).filter((p:any)=>p.status==='APPROVED'&&!isExpired(p)); const catCount:any={}; livePosts.forEach((p:any)=>{ catCount[p.categorySlug]=(catCount[p.categorySlug]||0)+1; }); const popCats=Object.entries(catCount).map(([slug,n]:any)=>({slug,name:catName[slug]||slug,n})).sort((a:any,b:any)=>b.n-a.n).slice(0,10); const maxCat=popCats.length?popCats[0].n:1;
 const pubByType:any={}; (db.contents||[]).forEach((c:any)=>{ if(c.status==='PUBLISHED') pubByType[c.typeSlug]=(pubByType[c.typeSlug]||0)+1; }); const emptyTypes=(db.content_types||[]).filter((t:any)=>t&&t.enabled!==false&&t.publicListing&&!(pubByType[t.slug]>0)); const emptyCats=(db.categories||[]).filter((c:any)=>c&&c.enabled!==false&&!(catCount[c.slug]>0));
 const viewLeaders=(db.posts||[]).filter((p:any)=>p.status==='APPROVED'&&(Number(p.views)||0)>0).sort((a:any,b:any)=>(Number(b.views)||0)-(Number(a.views)||0)).slice(0,10); const totalViews=(db.posts||[]).reduce((a:number,p:any)=>a+(Number(p.views)||0),0);
 const kpi=(v:any,l:string)=>(<div className="card"><p className="text-3xl font-black num">{bn(v)}</p><p className="text-sm font-bold">{l}</p></div>); const fmtDay=(d:string)=>d?new Date(d+'T00:00:00').toLocaleDateString('bn-BD'):''; const maxTop=ins.topTerms.length?ins.topTerms[0].count:1;
 return <div><h1 className="font-black text-xl">ডেভেলপমেন্ট ইনসাইটস — মানুষ কী খুঁজছে, কী পাচ্ছে না</h1>
 <p className="text-xs text-gray-500 mt-1">সব হিসাব সরাসরি ডাটাবেস থেকে (গত ৩০ দিনের সার্চ লগ)। সার্চ লগে শুধু শব্দ, ফলাফলের সংখ্যা আর তারিখ থাকে — কোনো ইউজার/IP নয়।</p>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-3">{kpi(ins.total,'মোট সার্চ (৩০ দিন)')}{kpi(ins.zeroTotal,`শূন্য-ফলাফল সার্চ (${bn(zeroPct)}%)`)}{kpi(livePosts.length,'লাইভ (অনুমোদিত) পোস্ট')}{kpi(totalViews,'মোট পোস্ট ভিউ')}</div>
 <div className="card mt-3"><b>🔎 সবচেয়ে বেশি খোঁজা শব্দ (গত ৩০ দিন)</b>{ins.topTerms.length===0?<p className="text-sm text-gray-500 mt-2">এখনো কোনো সার্চ লগ জমা হয়নি — সাইটে সার্চ হলেই এখানে আসল তথ্য জমতে শুরু করবে।</p>:<div className="mt-2">{ins.topTerms.slice(0,15).map((s:any)=>(<div key={s.term} className="flex items-center gap-3 py-1.5 border-b last:border-0"><span className="flex-1 font-bold text-sm truncate">{s.term}</span><span className="hidden md:block w-40 bg-emerald-50 rounded-full h-2"><span className="block bg-emerald-500 h-2 rounded-full" style={{width:Math.max(4,s.count/maxTop*100)+'%'}}/></span><span className="text-sm font-black num w-14 text-right">{bn(s.count)} বার</span><span className="text-[11px] text-gray-400 w-24 text-right">শেষ: {fmtDay(s.lastDay)}</span></div>))}</div>}</div>
 <div className="card mt-3 border-amber-200 bg-amber-50/60"><b>🚫 যেসব খোঁজায় কিছুই পাওয়া যায়নি</b><p className="text-xs text-gray-500 mt-1"><b>পরামর্শ:</b> এসব বিষয়ে কন্টেন্ট যোগ করুন — মানুষ খুঁজছে, কিন্তু সাইটে নেই। এটাই সবচেয়ে কাজের তালিকা।</p>{ins.zeroTerms.length===0?<p className="text-sm text-gray-500 mt-2">সুখবর — গত ৩০ দিনে কোনো সার্চই খালি হাতে ফেরেনি (অথবা এখনো লগ জমা হয়নি)।</p>:<div className="mt-2">{ins.zeroTerms.slice(0,15).map((s:any)=>(<div key={s.term} className="flex items-center gap-3 py-1.5 border-b border-amber-100 last:border-0"><span className="flex-1 font-bold text-sm truncate">{s.term}</span>{s.count>s.zeroCount&&<span className="text-[11px] text-gray-400">মোট {bn(s.count)} বার খোঁজা</span>}<span className="text-sm font-black num text-red-600">{bn(s.zeroCount)} বার খালি</span><span className="text-[11px] text-gray-400 w-24 text-right">শেষ: {fmtDay(s.lastDay)}</span></div>))}</div>}</div>
 <div className="card mt-3"><b>📂 জনপ্রিয় ক্যাটাগরি (লাইভ পোস্টের সংখ্যা অনুযায়ী)</b>{popCats.length===0?<p className="text-sm text-gray-500 mt-2">কোনো লাইভ পোস্ট নেই।</p>:<div className="mt-2">{popCats.map((c:any)=>(<div key={c.slug} className="flex items-center gap-3 py-1.5 border-b last:border-0"><Link href={'/category/'+c.slug} className="flex-1 font-bold text-sm text-brand-700 truncate">{c.name}</Link><span className="hidden md:block w-40 bg-emerald-50 rounded-full h-2"><span className="block bg-emerald-500 h-2 rounded-full" style={{width:Math.max(4,c.n/maxCat*100)+'%'}}/></span><span className="text-sm font-black num">{bn(c.n)}টি</span></div>))}</div>}</div>
 <div className="grid md:grid-cols-2 gap-3 mt-3"><div className="card"><b>👁️ সবচেয়ে বেশি দেখা পোস্ট</b>{viewLeaders.length===0?<p className="text-sm text-gray-500 mt-2">এখনো কোনো পোস্টে ভিউ জমা হয়নি।</p>:<div className="mt-2">{viewLeaders.map((p:any)=>(<div key={p.id} className="flex items-center gap-2 py-1.5 border-b last:border-0"><Link href={'/post/'+p.id} className="flex-1 font-bold text-sm text-brand-700 truncate">{p.title}</Link><span className="text-[11px] text-gray-400">{catName[p.categorySlug]||p.categorySlug}</span><span className="text-sm font-black num">{bn(p.views||0)} বার</span></div>))}</div>}</div>
 <div className="card"><b>🧩 অসম্পূর্ণ বিভাগ (কন্টেন্ট যোগ করা দরকার)</b>{emptyTypes.length===0&&emptyCats.length===0?<p className="text-sm text-gray-500 mt-2">সব বিভাগেই অন্তত কিছু প্রকাশিত কন্টেন্ট আছে।</p>:<div className="mt-2 space-y-1">{emptyTypes.map((t:any)=>(<p key={t.slug} className="text-sm py-1 border-b last:border-0">📚 <b>{t.nameBn||t.nameEn}</b> — প্রকাশিত কন্টেন্ট ০টি <Link href="/admin/content" className="text-brand-700 font-bold">যোগ করুন →</Link></p>))}{emptyCats.map((c:any)=>(<p key={c.slug} className="text-sm py-1 border-b last:border-0">📂 <b>{c.name}</b> — লাইভ পোস্ট ০টি</p>))}</div>}</div></div>
 <p className="text-[11px] text-gray-400 mt-3">সার্চ লগ সর্বোচ্চ {bn(2000)}টি সাম্প্রতিক রেকর্ড রাখা হয় (পুরনো স্বয়ংক্রিয়ভাবে ঝরে যায়)। হিসাবগুলো মাপা তথ্য; কোনো অনুমান বা AI-সাজেশন এখানে মেশানো হয়নি।</p></div>; }
