import {readDBAsync,mutateDBAsync} from '@/lib/db'; import {Shell,bn,EmptyState,VerifiedBadge} from '@/components/ui'; import {sanitizeContentType,sanitizeContent,ensureCmsSeeds,needsCmsSeeds,featuredImage,locationText,fieldDisplay,contentTitle} from '@/lib/cms'; import {bnNorm} from '@/lib/search'; import DirectoryMapLazy from '@/components/DirectoryMapLazy'; import Link from 'next/link'; export const dynamic='force-dynamic'; export const metadata={title:'ডিরেক্টরি ও মানচিত্র — বোয়ালখালী কানেক্ট',description:'বোয়ালখালীর দর্শনীয় স্থান, স্কুল, হাসপাতাল, ব্যবসা ও সেবাপ্রতিষ্ঠানের একীভূত ডিরেক্টরি ও মানচিত্র',alternates:{canonical:'/directory'}};
// Unified Directory (Wave 2): one filterable list over PUBLISHED CMS contents
// (places, schools, hospitals, businesses, doctor profiles…) plus an OSM/MapLibre map.
// The map shows pins ONLY for records with stored numeric coordinates — nothing is
// geocoded, guessed or invented. News/events types are announcements, not directory
// entries, so they stay on their own pages.
const EXCLUDE=new Set(['local-news','event']);
export default async function P({searchParams}:{searchParams:any}){ let db=await readDBAsync(); if(needsCmsSeeds(db)){ await mutateDBAsync((d:any)=>{ ensureCmsSeeds(d,'system'); }); db=await readDBAsync(); }
 const types=(db.content_types||[]).map((t:any)=>sanitizeContentType(t)).filter((t:any)=>t&&t.enabled&&t.publicListing&&!EXCLUDE.has(t.slug)).sort((a:any,b:any)=>a.order-b.order); const tBySlug:any={}; types.forEach((t:any)=>{ tBySlug[t.slug]=t; });
 const all=(db.contents||[]).map((c:any)=>sanitizeContent(c)).filter((c:any)=>c&&c.status==='PUBLISHED'&&tBySlug[c.typeSlug]);
 const fType=String(searchParams.type||''); const fArea=String(searchParams.area||''); const fQ=bnNorm(searchParams.q||'');
 const areaSet=new Set<string>(); all.forEach((c:any)=>{ const a=String((c.location||{}).area||(c.location||{}).union||'').trim(); if(a) areaSet.add(a); }); const areas:string[]=Array.from(areaSet).sort((a,b)=>a.localeCompare(b,'bn'));
 const items=all.filter((c:any)=>{ if(fType&&c.typeSlug!==fType) return false; if(fArea){ const l=c.location||{}; if(![l.area,l.union,l.upazila].filter(Boolean).includes(fArea)) return false; } if(fQ){ const hay=bnNorm([contentTitle(c),c.shortDesc,tBySlug[c.typeSlug].nameBn,locationText(c),(c.tags||[]).join(' ')].join(' ')); if(!hay.includes(fQ)) return false; } return true; });
 const hrefOf=(c:any)=>c.typeSlug==='place'?'/boalkhali/'+c.slug:'/content/'+c.typeSlug+'/'+c.slug;
 const markers=items.filter((c:any)=>{ const l=c.location||{}; return l.lat!==null&&l.lng!==null&&Number.isFinite(l.lat)&&Number.isFinite(l.lng); }).map((c:any)=>({id:c.id,title:contentTitle(c),typeName:tBySlug[c.typeSlug].nameBn||c.typeSlug,area:(c.location||{}).area||'',lat:Number(c.location.lat),lng:Number(c.location.lng),href:hrefOf(c)}));
 return <Shell><main className="max-w-6xl mx-auto p-4"><h1 className="font-black text-xl">🧭 ডিরেক্টরি ও মানচিত্র</h1><p className="text-sm text-gray-500">বোয়ালখালীর স্থান, প্রতিষ্ঠান ও সেবা — এক জায়গায়। মোট {bn(all.length)}টি প্রকাশিত তথ্য{items.length!==all.length?`, ফিল্টারে ${bn(items.length)}টি`:''} • মানচিত্রে পিন {bn(markers.length)}টি (যেসব রেকর্ডে সঠিক স্থানাঙ্ক সংরক্ষিত আছে শুধু সেগুলোর)</p>
 <form className="card my-3 grid md:grid-cols-4 gap-2" method="get"><div><label className="block text-sm font-bold">বিভাগ</label><select name="type" defaultValue={fType}><option value="">সব বিভাগ</option>{types.map((t:any)=>(<option key={t.slug} value={t.slug}>{t.icon} {t.nameBn||t.nameEn}</option>))}</select></div><div><label className="block text-sm font-bold">এলাকা</label><select name="area" defaultValue={fArea}><option value="">সব এলাকা</option>{areas.map(a=>(<option key={a} value={a}>{a}</option>))}</select></div><div className="md:col-span-2"><label className="block text-sm font-bold">নামে খুঁজুন</label><div className="flex gap-2"><input name="q" defaultValue={String(searchParams.q||'')} placeholder="যেমন: স্কুল, হাসপাতাল, মাজার…"/><button className="btn shrink-0">🔍 খুঁজুন</button></div></div></form>
 <div className="card"><div className="flex items-center justify-between gap-2"><b>🗺️ মানচিত্র</b><span className="text-[11px] text-gray-400">{bn(markers.length)}টি পিন</span></div><div className="mt-2"><DirectoryMapLazy markers={markers}/></div><p className="text-[11px] text-gray-400 mt-1">শুধু যেসব রেকর্ডে যাচাইকৃত স্থানাঙ্ক সংরক্ষিত আছে, সেগুলোই পিন হিসেবে দেখানো হয় — এলাকা-পর্যায়ের স্থানগুলো অনুমান করে পিন দেওয়া হয় না, সেগুলো নিচের তালিকায় আছে।</p></div>
 {items.length===0?<div className="mt-3"><EmptyState icon="🧭" title="এই ফিল্টারে কিছু পাওয়া যায়নি" desc="বিভাগ বা এলাকা বদলে আবার চেষ্টা করুন।" href="/directory" cta="সব ডিরেক্টরি দেখুন"/></div>:
 <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-3">{items.map((c:any)=>{ const t=tBySlug[c.typeSlug]; const img=featuredImage(c); const cardVals=(t.cardFields||[]).map((k:string)=>{ const f=(t.fields||[]).find((x:any)=>x.key===k); return f?fieldDisplay(f,(c.fields||{})[k]):''; }).filter(Boolean).slice(0,2); return <Link key={c.id} href={hrefOf(c)} className="card press lift block !p-0 overflow-hidden">{img?<img src={img.url} alt={img.alt||contentTitle(c)} loading="lazy" className="h-36 w-full object-cover"/>:<div className="h-36 w-full grid place-items-center text-5xl" style={{background:'#0a7a5414'}}>{t.icon||'📁'}</div>}<div className="p-3"><div className="flex items-center gap-1.5 flex-wrap"><span className="chip bg-brand-50 text-brand-700">{t.icon} {t.nameBn||t.nameEn}</span>{c.verified&&<VerifiedBadge label="যাচাইকৃত"/>}{(c.location&&locationText(c))&&<span className="text-[11px] text-gray-400">📍 {locationText(c)}</span>}</div><b className="block mt-1.5 leading-snug">{contentTitle(c)}</b>{c.shortDesc&&<p className="text-xs text-gray-500 mt-1 line-clamp-2">{c.shortDesc}</p>}{cardVals.length>0&&<p className="text-[11px] font-bold text-gray-600 mt-1.5">{cardVals.join(' • ')}</p>}<span className="text-xs font-bold text-brand-700 mt-2 inline-block">বিস্তারিত দেখুন →</span></div></Link>; })}</div>}
 <div className="card mt-3 flex flex-wrap items-center gap-2"><span className="text-sm">🩺 ডাক্তারদের আলাদা পূর্ণাঙ্গ ডিরেক্টরি:</span><Link href="/doctors" className="chip press bg-brand-50 text-brand-700 font-bold">সব ডাক্তার দেখুন →</Link><span className="text-sm ms-2">📚 বিভাগ অনুযায়ী ব্রাউজ:</span><Link href="/content" className="chip press bg-brand-50 text-brand-700 font-bold">তথ্য ভাণ্ডার →</Link></div>
 </main></Shell>; }
