export const dynamic='force-dynamic';
import {NextResponse} from 'next/server'; import {readDBAsync,mutateDBAsync,sanitize,sanitizeBusinessVerification,id,now,audit} from '@/lib/db'; import {currentUser,rateLimit} from '@/lib/auth'; import {sanitizeContent,contentTitle} from '@/lib/cms';
// Business verification — owner side (Wave 3). A logged-in user may ask for the
// ✓ যাচাইকৃত badge on a CMS 'business' content THEY created (createdBy). Owners can
// never set `verified` themselves: this route only creates a PENDING request; the
// badge is written by the admin review route (/api/admin/verifications).
export async function GET(){ const u=await currentUser(); if(!u) return NextResponse.json({error:'LOGIN_REQUIRED'},{status:401}); const db=await readDBAsync(); const byId:any={}; (db.contents||[]).forEach((c:any)=>{ byId[c.id]=c; }); const requests=(db.business_verifications||[]).filter((v:any)=>v&&v.userId===u.id).map(sanitizeBusinessVerification).filter(Boolean).map((v:any)=>({ ...v,contentSlug:byId[v.contentId]?byId[v.contentId].slug:'',contentStatus:byId[v.contentId]?byId[v.contentId].status:'' })); return NextResponse.json({requests}); }
export async function POST(req:Request){ const u=await currentUser(); if(!u) return NextResponse.json({error:'LOGIN_REQUIRED'},{status:401}); if(!rateLimit('bizverify:'+u.id,10)) return NextResponse.json({error:'RATE_LIMIT',message:'অনেকবার চেষ্টা হয়েছে — কিছুক্ষণ পরে আবার চেষ্টা করুন'},{status:429}); const b=await req.json().catch(()=>({})); const contentId=String(b.contentId||''); if(!contentId) return NextResponse.json({error:'CONTENT_REQUIRED',message:'ব্যবসা নির্বাচন করুন'},{status:400});
 const out:any=await mutateDBAsync((db:any)=>{ const c=(db.contents||[]).find((x:any)=>x.id===contentId); if(!c||c.typeSlug!=='business') return {e:404,error:'CONTENT_NOT_FOUND',message:'ব্যবসাপ্রতিষ্ঠানটি পাওয়া যায়নি'}; if(c.createdBy!==u.id) return {e:403,error:'NOT_OWNER',message:'শুধু নিজের ব্যবসার জন্যই যাচাইয়ের আবেদন করা যায়'}; if(c.verified===true) return {e:409,error:'ALREADY_VERIFIED',message:'এই ব্যবসাটি ইতিমধ্যে যাচাইকৃত'}; if((db.business_verifications||[]).some((v:any)=>v&&v.contentId===c.id&&v.status==='PENDING')) return {e:409,error:'ALREADY_PENDING',message:'এই ব্যবসার যাচাইয়ের আবেদন ইতিমধ্যে অপেক্ষমাণ আছে'}; const rec=sanitizeBusinessVerification({id:id('bv'),userId:u.id,contentId:c.id,businessName:contentTitle(sanitizeContent(c)),note:sanitize(b.note),status:'PENDING',reviewerId:'',reviewNote:'',createdAt:now(),reviewedAt:null}); if(!Array.isArray(db.business_verifications)) db.business_verifications=[]; db.business_verifications.unshift(rec); for(const a of db.users.filter((x:any)=>['ADMIN','SUPER_ADMIN'].includes(x.role))) db.notifications.unshift({id:id('n'),userId:a.id,type:'BUSINESS_VERIFY_PENDING',contentId:c.id,title:'নতুন ব্যবসা যাচাইয়ের আবেদন',body:rec.businessName+' — '+(u.name||u.email),read:false,createdAt:now()}); audit(db,u.email,'BUSINESS_VERIFY_REQUEST',c.id); return {ok:true,request:rec}; });
 if(out.e) return NextResponse.json(out,{status:out.e}); return NextResponse.json(out); }
