import {readDBAsync} from '@/lib/db'; import {requireAdminPage} from '@/lib/auth'; import {bn} from '@/components/ui'; import {scanContentHealth} from '@/lib/contentHealth'; import Link from 'next/link'; export const dynamic='force-dynamic';
// Content Health Monitor (Wave 2): a review queue computed live from the real records.
// READ-ONLY by construction — this page never edits, hides or deletes anything; each row
// simply links to where an admin can fix the record by hand. Heuristic findings carry a
// confidence badge (নিশ্চিত / সম্ভাব্য); factual ones (expired date, empty field) need none.
export default async function P(){ await requireAdminPage('content.view'); const db=await readDBAsync(); const S=scanContentHealth(db); const total=S.reduce((a,s)=>a+s.total,0);
 return <div><h1 className="font-black text-xl">কনটেন্ট হেলথ মনিটর</h1>
 <p className="text-xs text-gray-500 mt-1">ডাটাবেসের আসল রেকর্ড স্ক্যান করে তৈরি লাইভ প্রতিবেদন। <b>এই পেজ কিছুই স্বয়ংক্রিয়ভাবে বদলায় বা মোছে না</b> — প্রতিটি সারি শুধু পর্যালোচনার জন্য; ঠিক করতে হলে সারির লিংকে গিয়ে নিজে সম্পাদনা করুন।</p>
 {S.length===0?<div className="card mt-4 text-center py-10"><div className="text-4xl">✅</div><h3 className="font-display mt-2 text-lg font-bold">কোনো সমস্যা ধরা পড়েনি</h3><p className="text-sm text-gray-500 mt-1">মেয়াদোত্তীর্ণ, অসম্পূর্ণ, ডুপ্লিকেট বা দীর্ঘদিন-পেন্ডিং — কোনো রেকর্ডেই আপাতত সমস্যা নেই।</p></div>:
 <><div className="flex flex-wrap gap-2 mt-3">{S.map(s=>(<a key={s.key} href={'#'+s.key} className="chip press bg-white border">{s.icon} {s.label}: <b className="num">{bn(s.total)}</b></a>))}<span className="chip bg-red-50 text-red-700 border border-red-100">মোট {bn(total)}টি বিষয়</span></div>
 {S.map(s=>(<div key={s.key} id={s.key} className="card mt-3"><b>{s.icon} {s.label}</b> <span className="text-xs text-gray-400">({bn(s.total)}টি{s.total>s.rows.length?`, প্রথম ${bn(s.rows.length)}টি দেখানো হচ্ছে`:''})</span><div className="mt-2">{s.rows.map((r,i)=>(<div key={i} className="flex flex-wrap items-center gap-2 py-2 border-b last:border-0"><span className="flex-1 min-w-[180px]"><b className="text-sm">{r.title}</b><span className="block text-xs text-gray-500">{r.detail}</span></span>{r.conf&&<span className={`chip ${r.conf==='নিশ্চিত'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-700'}`}>{r.conf}</span>}{r.href&&<Link href={r.href} className="chip press bg-slate-100">👁️ দেখুন</Link>}{r.adminHref&&<Link href={r.adminHref} className="chip press bg-emerald-600 text-white">✏️ ঠিক করুন</Link>}</div>))}</div></div>))}</>}
 <p className="text-[11px] text-gray-400 mt-3">ডুপ্লিকেট শনাক্তকরণ শিরোনাম-ভিত্তিক অনুমান — তাই সেখানে <b>নিশ্চিত/সম্ভাব্য</b> আত্মবিশ্বাস দেখানো হয়েছে; চূড়ান্ত সিদ্ধান্ত সবসময় মানুষের।</p></div>; }
