'use client'; import {useEffect,useState} from 'react'; import {errMsg} from '@/lib/errMsg';
export function ShareBtn(){ const [ok,setOk]=useState(false); return <button className="btn !bg-slate-700" onClick={async()=>{ try{ await navigator.clipboard.writeText(location.href); setOk(true); setTimeout(()=>setOk(false),2000);}catch{ setOk(false)} }}>{ok?'✅ লিংক কপি হয়েছে':'🔗 শেয়ার'}</button> }
export function ReportForm({postId}:{postId:string}){ const [show,setShow]=useState(false); const [msg,setMsg]=useState(''); const send=async(e:any)=>{ e.preventDefault(); const f=new FormData(e.currentTarget); const r=await fetch('/api/posts/report',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({postId,reason:f.get('reason'),details:f.get('details')})}); const j=await r.json(); if(r.ok){ setMsg('✅ রিপোর্ট জমা হয়েছে — অ্যাডমিন যাচাই করবেন।'); setShow(false);} else setMsg('❌ '+errMsg(j.error)) };
 return <div className="mt-3"><button className="chip bg-red-100 text-red-700" onClick={()=>setShow(!show)}>🚩 রিপোর্ট করুন</button>{msg&&<p className="text-sm mt-2">{msg}</p>}{show&&(<form onSubmit={send} className="mt-2 space-y-2 bg-red-50 p-3 rounded-xl"><label>কারণ<select name="reason"><option>প্রতারণা</option><option>ভুল তথ্য</option><option>অশালীন</option><option>অন্যান্য</option></select></label><label>বিস্তারিত (ঐচ্ছিক)<textarea name="details" rows={2}/></label><button className="btn !bg-red-600">রিপোর্ট পাঠান</button></form>)}</div> }
export function Comments({postId}:{postId:string}){ const [list,setList]=useState<any[]>([]); const [me,setMe]=useState<string>(''); const [msg,setMsg]=useState('');
 const load=async()=>{ const r=await fetch('/api/posts/comments?postId='+postId); const j=await r.json(); setList(j.comments||[]) };
 useEffect(()=>{ load(); fetch('/api/auth/me').then(r=>r.json()).then(j=>setMe(j.user?j.user.id:'')) },[postId]);
 const add=async(e:any)=>{ e.preventDefault(); const f=new FormData(e.currentTarget); const r=await fetch('/api/posts/comments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({postId,text:f.get('text')})}); const j=await r.json(); if(r.ok){ (e.currentTarget as HTMLFormElement).reset(); load(); } else setMsg('❌ '+errMsg(j.error)) };
 const del=async(cid:string)=>{ if(!confirm('নিশ্চিত? মন্তব্যটি মুছে যাবে।'))return; const r=await fetch('/api/posts/comments',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id:cid})}); if(r.ok) load(); else setMsg('❌ মুছতে ব্যর্থ হয়েছে') };
 return <div className="card mt-4"><h2 className="font-black">💬 মন্তব্য ও প্রশ্ন ({list.length})</h2>{msg&&<p className="text-sm mt-1">{msg}</p>}
 {list.map((c:any)=>(<div key={c.id} className="border-b py-2"><div className="flex justify-between"><b className="text-sm">{c.author}</b><span className="text-xs text-gray-400">{c.createdAt?new Date(c.createdAt).toLocaleString('bn-BD'):''}</span></div><p className="text-sm">{c.text}</p>{me&&c.userId===me&&<button className="text-xs text-red-600" onClick={()=>del(c.id)}>মুছে ফেলুন</button>}</div>))}
 {list.length===0&&<p className="text-sm text-gray-500 mt-2">এখনো কোনো মন্তব্য নেই — প্রথম মন্তব্যটি করুন।</p>}
 <form onSubmit={add} className="mt-3 flex gap-2"><input name="text" placeholder="প্রশ্ন বা মন্তব্য লিখুন..." required className="flex-1"/><button className="btn">পাঠান</button></form></div> }
